```{r}
library("caret")
library("ggplot2")
library("dplyr")
library("mice")
Sys.setenv(TZ='UTC')
setwd("/Users/jwang/Desktop/Patient Matching/")

# Read tab-delimited input using header row labels and interpret Python None strings as R NA values
expert_df = tbl_df(read.csv("expert_2013only.csv",header=TRUE,sep=",",na.strings="None", stringsAsFactors=FALSE));
everyone_df = tbl_df(read.csv("everyone_2013only.csv",header=TRUE,sep=",",na.strings="None",stringsAsFactors=FALSE));

# Add labels: 1 = expert, 0 = everyone
expert_df = data.frame(expert_df, label="expert")
dim(expert_df)
everyone_df = data.frame(everyone_df, label="everyone")
dim(everyone_df)

# Combine into one dataframe
df_raw <- rbind(expert_df[,c(1,6:52)], everyone_df[,c(1,6:52)])

# Ensure legitimate variable names
colnames(df_raw) <- make.names(colnames(df_raw))

# Remove features with near-zero variance
#nzv <- nearZeroVar(df_raw)
#df <- df_raw[,-nzv]

# Convert T/F = 1/0 (Columns 18:45)
for (col_id in 18:45) {
  df_raw[,col_id] <- factor(ifelse(df_raw[,col_id]=="True", 1, 0))
}

# Remove features with too much NA/missing data (by manual inspection)
df = df_raw[,c(1:3,6:48)]

# Remove lab tests to reduce bias: columns 7-15 in df
df = df[,c(1:6, 16:46)]

# Impute the remaining NA values: predictive mean imputation
md.pattern(df);
md_data <- mice(df,m=1,maxit=5,meth='pmm',seed=500);
df <- complete(md_data,1);

```

```{r}
# # Propensity Scoring: Gradient Boosted Tree Model
# library(gbm)
# set.seed(1) 
# interaction.depth <- c(3) # complexity of the tree
# n.minobsinnode <- c(3) # minimum observations per node
# shrinkage <- c(0.1) # learning rate
# n.trees = seq(from=5, to=250, by=5) # number of iterations
# 
# grid <- expand.grid(interaction.depth = interaction.depth, n.minobsinnode = n.minobsinnode, shrinkage=shrinkage, n.trees=n.trees)
# 
# control <- trainControl(method = "cv",
#                         number = 4,
#                         ## Estimate class probabilities
#                         classProbs = TRUE,
#                         ## Evaluate performance using 
#                         ## the following function
#                         summaryFunction = twoClassSummary)
# 
# label <- factor(ifelse(df[,46]=="expert", 1, 0)) #Expert = 1, Everyone = 0
# features <- df[,c(-1, -46)]; 
# 
# gbm.fit <- train(label ~ ., data = data.matrix(features), 
#                  method = "gbm", 
#                  trControl = control, 
#                  tuneGrid = grid,
#                  ## Specify which metric to optimize
#                  metric = "ROC",
#                  maximize = TRUE)
# plot(gbm.fit)
# 
# # Find max AUC (note: "ROC" refers to AUC metric) and corresponding optimal parameters
# parameters <- gbm.fit$results %>%
#   arrange(desc(ROC))
# opt_parameters <- parameters[1,c(1:7)]
# print(opt_parameters)

```

```{r}
# Propensity Scoring: Logistic Regression
label <- factor(ifelse(df[,37]=="expert", 1, 0)) #Expert = 1, Everyone = 0
glm.fit <- glm(label ~.,family=binomial(link='logit'),data=df[,c(-1, -37)])

# Propensity Estimation 
features <- df[,c(-1)]
expert_features <- features %>%
  filter(label == "expert")
expert_features <- expert_features[,c(-36)] # remove label

everyone_features <- features %>%
  filter(label == "everyone")
everyone_features <- everyone_features[,c(-36)] # remove label

pred_expert <- predict(glm.fit, newdata=expert_features, type="response")
pred_everyone <- predict(glm.fit, newdata=everyone_features, type="response")

# Overlap Plot
# note that logit = log(p/(1-p))
require(car)
logit_expert <- as.numeric(logit(pred_expert))
logit_everyone <- as.numeric(logit(pred_everyone))
histdata <- data.frame(rbind.data.frame(cbind.data.frame(logit=logit_expert,label="Expert"), cbind.data.frame(logit=logit_everyone,label="Everyone")))

ggplot(histdata, aes(x=logit, fill=label)) + geom_histogram(alpha=0.2, position="identity")

```

```{r}
# Caliper Matching
# caliper = the maximum tolerated difference between matched subjects in a "non-perfect" matching 
library(Matching)

# conduct matching w/o replacement on logit of propensity
temp <- data.frame(rbind.data.frame(cbind.data.frame(logit=logit_expert,label=1), cbind.data.frame(logit=logit_everyone,label=0)))
matches <- Match(X=temp$logit, Tr=temp$label, caliper=0.25, replace=FALSE)

# number of patients in matched set
treated <- matches$index.treated
control <- matches$index.control
length(treated)
length(control)

```

```{r}
# Examine Matching Results
expert_full <- df %>% 
  filter(label == "expert")

everyone_full <- df %>% 
  filter(label == "everyone")

df_full <- rbind.data.frame(expert_full, everyone_full)
# treated = expert (1), control = everyone (0)
df_matched <- rbind.data.frame(df_full[treated,], df_full[control,])

# Output to CSV
write.csv(df_matched, file = "matched.csv")

# Before and After Comparisons
expert_matched <- df_matched %>%
  filter(label == "expert")
expert_matched <- expert_matched[,c(-1,-37)]
everyone_matched <- df_matched %>%
  filter(label == "everyone")
everyone_matched <- everyone_matched[,c(-1,-37)]

expert_unmatched <-expert_features
everyone_unmatched <- everyone_features

#summary(expert_matched)
#summary(expert_unmatched)

print("UNMATCHED")
print("EXPERT")
print("EVERYONE")
print("****")

for (i in 1:35) {
  print(colnames(expert_matched)[i])
  if (i < 6 || i > 33) { #mean
    print(mean(expert_unmatched[,i]))
    print(sd(expert_unmatched[,i]))
    print(mean(everyone_unmatched[,i]))
    print(sd(everyone_unmatched[,i]))
    #print(wilcox.test(expert_unmatched[,i], everyone_unmatched[,i], alternative = "two.sided")$p.value)
    print(t.test(expert_unmatched[,i], everyone_unmatched[,i])$p.value)
    print("****")
  }
  else { # fraction
    print(length(expert_unmatched[,i][expert_unmatched[,i] == 1])/dim(expert_unmatched)[1])
    print(length(everyone_unmatched[,i][everyone_unmatched[,i] == 1])/dim(everyone_unmatched)[1])
    #print(chisq.test(table(expert_unmatched[,i], everyone_unmatched[,i]))$p.value)
    print(t.test(as.numeric(expert_unmatched[,i]), as.numeric(everyone_unmatched[,i]))$p.value)
    print("****")
  }
}

print("MATCHED")
print("EXPERT")
print("EVERYONE")
print("****")

for (i in 1:35) {
  print(colnames(expert_matched)[i])
  if (i < 6 || i > 33) { #mean
    print(mean(expert_matched[,i]))
    print(sd(expert_matched[,i]))
    print(mean(everyone_matched[,i]))
    print(sd(everyone_matched[,i]))
    #print(wilcox.test(expert_matched[,i], everyone_matched[,i], alternative = "two.sided")$p.value)
    print(t.test(expert_matched[,i], everyone_matched[,i])$p.value)
    print("****")
  }
  else { # fraction
    print(length(expert_matched[,i][expert_matched[,i] == 1])/dim(expert_matched)[1])
    print(length(everyone_matched[,i][everyone_matched[,i] == 1])/dim(everyone_matched)[1])
    #print(chisq.test(table(expert_matched[,i], everyone_matched[,i]))$p.value)
    print(t.test(as.numeric(expert_matched[,i]), as.numeric(everyone_matched[,i]))$p.value)
    print("****")
  }
}

```