
*The below dnrvars file was created in R and is different from parent file in the following ways
1. Subset of only those with no prior DNR order (i.e., starts LST while Full Code)
2. Selected variables only included;


proc import datafile="Q:/Datasets/HM/Jonathan Chen-DNR/dnrvars.csv" out=alldnr
    dbms=csv replace;
	getnames=yes;
	datarow=2;
	guessingrows=32767456;
run;

data alldnr;set alldnr;
rename Glasgow_Coma_Scale_Score_last=gcss_last;
end_day=curr_day+1;
run;

%macro locf(data,group1,group2,varname);
proc sort data=&data;
by &group1 &group2;run;

data &data;
set &data;by &group1 &group2;
retain locf_&varname;
if first.&group1 then locf_&varname=&varname;
else if &varname^= . then locf_&varname=&varname;
run;
%mend locf;
*****************************************************************;
************************************************************************************************************************;

%locf(alldnr,patid,curr_day,GCSS_last)
*****************************************************************;
************************************************************************************************************************;
/*
proc freq data=meannorm;
where curr_day=1;
where also AnyDNR_postTimeDays<daysUntilEnd+1;
tables anydnr_post;
run;
/*/

data meannorm;set alldnr;
if locf_Temp_last=. Then locf_Temp_last=98.6;
if locf_BP_High_Systolic_last=. Then locf_BP_High_Systolic_last=110;
if locf_Pulse_last=. Then locf_Pulse_last=80;
if locf_Resp_last=. Then locf_Resp_last=16;
if locf_PO2A_last=. Then locf_PO2A_last=95;
if locf_PHA_last=. Then locf_PHA_last=7.4;
if locf_NA_last=. Then locf_NA_last=145;
if locf_K_last=. Then locf_K_last=4.5;
if locf_CR_last=. Then locf_CR_last=0.8;
if locf_HCT_last=. Then locf_HCT_last=42;
if locf_WBC_last=. Then locf_WBC_last=8;
if locf_GCSS_last=. Then locf_GCSS_last=15;
if locf_BUN_last=. Then locf_BUN_last=15;
if locf_TBIL_last=. Then locf_TBIL_last=1;
if locf_CO2_last=. Then locf_CO2_last=24;
run;
data maxnorm;set alldnr;
if locf_Temp_last=. Then locf_Temp_last=101;
if locf_BP_High_Systolic_last=. Then locf_BP_High_Systolic_last=199;
if locf_Pulse_last=. Then locf_Pulse_last=109;
if locf_Resp_last=. Then locf_Resp_last=24;
if locf_PO2A_last=. Then locf_PO2A_last=100;
if locf_PHA_last=. Then locf_PHA_last=7.49;
if locf_NA_last=. Then locf_NA_last=149;
if locf_K_last=. Then locf_K_last=5.4;
if locf_CR_last=. Then locf_CR_last=1.4;
if locf_HCT_last=. Then locf_HCT_last=45.9;
if locf_WBC_last=. Then locf_WBC_last=14.9;
if locf_GCSS_last=. Then locf_GCSS_last=15;*no change;
if locf_BUN_last=. Then locf_BUN_last=28;
if locf_TBIL_last=. Then locf_TBIL_last=4;
if locf_CO2_last=. Then locf_CO2_last=24;*no change;
run;

data minnorm;set alldnr;
if locf_Temp_last=. Then locf_Temp_last=96.8;
if locf_BP_High_Systolic_last=. Then locf_BP_High_Systolic_last=100;
if locf_Pulse_last=. Then locf_Pulse_last=70;
if locf_Resp_last=. Then locf_Resp_last=12;
if locf_PO2A_last=. Then locf_PO2A_last=70;
if locf_PHA_last=. Then locf_PHA_last=7.33;
if locf_NA_last=. Then locf_NA_last=130;
if locf_K_last=. Then locf_K_last=3.5;
if locf_CR_last=. Then locf_CR_last=0.6;
if locf_HCT_last=. Then locf_HCT_last=30;
if locf_WBC_last=. Then locf_WBC_last=3;
if locf_GCSS_last=. Then locf_GCSS_last=15;*no change;
if locf_BUN_last=. Then locf_BUN_last=28;
if locf_TBIL_last=. Then locf_TBIL_last=1;*no change;
if locf_CO2_last=. Then locf_CO2_last=20;
run;


************Forest Plots****************;

proc import datafile="Q:/Datasets/HM/Jonathan Chen-DNR/Aug_datasets/cox_forest.csv" out=forest
    dbms=csv replace;
	getnames=yes;
	datarow=2;
	guessingrows=32767456;
run;


data forest;set forest;
length label $30;
If term='ageYears' then label='Age';
If term='inc' then label='Income';
If term='self_payTRUE' then label='Uninsured';
If term='Female_preTRUE' then label='Female';
If term='RaceUnknown_preTRUE' then label='Unknown ';
If term='RaceAsian_preTRUE' then label='Asian';
If term='RaceBlack_preTRUE' then label='African-American';
If term='all_latinosTRUE' then label='Latinos';
If term='RaceOther_preTRUE' then label='Other';
If term='RacePacificIslander_preTRUE' then label='Pacific islander';
If term='RaceNativeAmerican_preTRUE' then label='Native American';
If term='AnyVasoactive_preTRUE' then label='Vasoactive';
If term='AnyVentilator_preTRUE' then label='Ventilator';
If term='AnyCRRT_preTRUE' then label='CCRT';
If term='Charlson_Cerebrovascular_preTRUE' then label='Cerebrovascular Disease';
If term='Charlson_CHF_preTRUE' then label='Congestive Heart Failure';
If term='Charlson_COPD_preTRUE' then label='COPD';
If term='Charlson_Dementia_preTRUE' then label='Dementia';
If term='Charlson_Diabetes_preTRUE' then label='Diabetes';
If term='Charlson_DiabetesComplications_TRUE' then label='DiabetesComplications';
If term='Charlson_HemiplegiaParaplegia_pTRUE' then label='Hemiplagia/Paraplegia';
If term='Charlson_LiverMild_preTRUE' then label='Mild Liver Disease';
If term='Charlson_LiverModSevere_preTRUE' then label='Moderate to Severe Liver Disease';
If term='Charlson_Malignancy_preTRUE' then label='Malignancy';
If term='Charlson_MalignancyMetastatic_pTRUE' then label='Metastatic Malignancy';
If term='Charlson_MI_preTRUE' then label='Myocardial Infarction';
If term='Charlson_PepticUlcer_preTRUE' then label='Peptic Ulcer';
If term='Charlson_PeripheralVascular_preTRUE' then label='Peripheral Vascular Disease';
If term='Charlson_Renal_preTRUE' then label='Renal Disease';
If term='Charlson_Rheumatic_preTRUE' then label='Rheumatic Disease';
If term='TT_Cardiology_preTRUE' then label='Cardiology Service';
If term='TT_CCU_HF_preTRUE' then label='Cardiac Care Unit-Heart Failure';
If term='TT_CCU_preTRUE' then label='Cardiac Care Unit';
If term='TT_HemeOnc_preTRUE' then label='Hemetalogy Oncology Service';
If term='TT_Medicine_preTRUE' then label='Medicine Service';
If term='TT_MICU_preTRUE' then label='Medical ICU';
If term='TT_Neurology_preTRUE' then label='Neorology Service';
If term='TT_SICU_preTRUE' then label='Surgical ICU';
If term='TT_SurgerySpecialty_preTRUE' then label='Surgery Service';
If term='TT_Transplant_preTRUE' then label='Transplant';
If term='TT_Trauma_preTRUE' then label='Trauma';
If term='TT_CVICU_preTRUE' then label='Cardiovascular ICU';
If term='locf_CO2_last' then label='Bicarbonate';
If term='locf_BUN_last' then label='Blood Urea Nitrogen';
If term='locf_CR_last' then label='Creatinine';
If term='locf_GCSS_last' then label='Glasgow Coma Score';
If term='locf_HCT_last' then label='Hematocrit';
If term='locf_PO2A_last' then label='Partial O2';
If term='locf_PHA_last' then label='PH ';
If term='locf_K_last' then label='Potassium';
If term='locf_Pulse_last' then label='Pulse';
If term='locf_Resp_last' then label='Respiration Rate';
If term='locf_NA_last' then label='Sodium';
If term='locf_BP_High_Systolic_last' then label='Systolic Blood Pressure';
If term='locf_Temp_last' then label='Temperature';
If term='locf_TBIL_last' then label='Total billirubin';
If term='locf_WBC_last' then label='White blood cells';
If term='ageYears' then order=1;
If term='inc' then order=3;
If term='self_payTRUE' then order=4;
If term='Female_preTRUE' then order=2;
If term='RaceUnknown_preTRUE' then order=11;
If term='RaceAsian_preTRUE' then order=6;
If term='RaceBlack_preTRUE' then order=5;
If term='all_latinosTRUE' then order=7;
If term='RaceOther_preTRUE' then order=10;
If term='RacePacificIslander_preTRUE' then order=8;
If term='RaceNativeAmerican_preTRUE' then order=9;
If term='AnyVasoactive_preTRUE' then order=13;
If term='AnyVentilator_preTRUE' then order=12;
If term='AnyCRRT_preTRUE' then order=14;
If term='Charlson_Cerebrovascular_preTRUE' then order=15;
If term='Charlson_CHF_preTRUE' then order=16;
If term='Charlson_COPD_preTRUE' then order=17;
If term='Charlson_Dementia_preTRUE' then order=18;
If term='Charlson_Diabetes_preTRUE' then order=19;
If term='Charlson_DiabetesComplications_TRUE' then order=20;
If term='Charlson_HemiplegiaParaplegia_pTRUE' then order=21;
If term='Charlson_LiverMild_preTRUE' then order=22;
If term='Charlson_LiverModSevere_preTRUE' then order=23;
If term='Charlson_Malignancy_preTRUE' then order=24;
If term='Charlson_MalignancyMetastatic_pTRUE' then order=25;
If term='Charlson_MI_preTRUE' then order=26;
If term='Charlson_PepticUlcer_preTRUE' then order=27;
If term='Charlson_PeripheralVascular_preTRUE' then order=28;
If term='Charlson_Renal_preTRUE' then order=29;
If term='Charlson_Rheumatic_preTRUE' then order=30;
If term='TT_Cardiology_preTRUE' then order=31;
If term='TT_CCU_HF_preTRUE' then order=32;
If term='TT_CCU_preTRUE' then order=33;
If term='TT_HemeOnc_preTRUE' then order=34;
If term='TT_Medicine_preTRUE' then order=35;
If term='TT_MICU_preTRUE' then order=36;
If term='TT_Neurology_preTRUE' then order=37;
If term='TT_SICU_preTRUE' then order=38;
If term='TT_SurgerySpecialty_preTRUE' then order=39;
If term='TT_Transplant_preTRUE' then order=40;
If term='TT_Trauma_preTRUE' then order=41;
If term='TT_CVICU_preTRUE' then order=42;
If term='locf_CO2_last' then order=43;
If term='locf_BUN_last' then order=44;
If term='locf_CR_last' then order=45;
If term='locf_GCSS_last' then order=46;
If term='locf_HCT_last' then order=47;
If term='locf_PO2A_last' then order=48;
If term='locf_PHA_last' then order=49;
If term='locf_K_last' then order=50;
If term='locf_Pulse_last' then order=51;
If term='locf_Resp_last' then order=52;
If term='locf_NA_last' then order=53;
If term='locf_BP_High_Systolic_last' then order=54;
If term='locf_Temp_last' then order=55;
If term='locf_TBIL_last' then order=56;
If term='locf_WBC_last' then order=57;
run;

proc sort data=forest; by set order;run;

ods graphics on /width=20in height=12in; 
proc sgpanel data=forest;where set in ("minlocfit" "maxlocfit" "meanlocfit" "fixedfit");
panelby set/columns=4;
scatter  x=expcoef y=label / xerrorlower=explcl            
xerrorupper=expucl  markerattrs=(symbol=DiamondFilled size=8);  
refline 1 / axis=x;
colaxis grid ;
rowaxis VALUEATTRS=(Family=Arial Size=8 Style=Italic );*Weight=Bold);
run;

***To compare estimates for each term;
ods graphics on /width=16in height=10in; 
proc sgpanel data=forest;
panelby label/columns=4 rows=2;
scatter  x=expcoef y=set / xerrorlower=explcl            
xerrorupper=expucl  markerattrs=(symbol=DiamondFilled size=8);  
refline 1 / axis=x;
colaxis grid ;
rowaxis VALUEATTRS=(Family=Arial Size=8 Style=Italic );*Weight=Bold);
run;


****************************************comfort care forest***********************************************;

proc import datafile="Q:/Datasets/HM/Jonathan Chen-DNR/Aug_datasets/cc_cox_forest.csv" out=ccforest
    dbms=csv replace;
	getnames=yes;
	datarow=2;
	guessingrows=32767456;
run;

data ccforest;set ccforest;
length label $30;
If term='ageYears' then label='Age';
If term='inc' then label='Income';
If term='self_payTRUE' then label='Uninsured';
If term='Female_preTRUE' then label='Female';
If term='RaceUnknown_preTRUE' then label='Unknown ';
If term='RaceAsian_preTRUE' then label='Asian';
If term='RaceBlack_preTRUE' then label='African-American';
If term='all_latinosTRUE' then label='Latinos';
If term='RaceOther_preTRUE' then label='Other';
If term='RacePacificIslander_preTRUE' then label='Pacific islander';
If term='RaceNativeAmerican_preTRUE' then label='Native American';
If term='AnyVasoactive_preTRUE' then label='Vasoactive';
If term='AnyVentilator_preTRUE' then label='Ventilator';
If term='AnyCRRT_preTRUE' then label='CCRT';
If term='Charlson_Cerebrovascular_preTRUE' then label='Cerebrovascular Disease';
If term='Charlson_CHF_preTRUE' then label='Congestive Heart Failure';
If term='Charlson_COPD_preTRUE' then label='COPD';
If term='Charlson_Dementia_preTRUE' then label='Dementia';
If term='Charlson_Diabetes_preTRUE' then label='Diabetes';
If term='Charlson_DiabetesComplications_TRUE' then label='DiabetesComplications';
If term='Charlson_HemiplegiaParaplegia_pTRUE' then label='Hemiplagia/Paraplegia';
If term='Charlson_LiverMild_preTRUE' then label='Mild Liver Disease';
If term='Charlson_LiverModSevere_preTRUE' then label='Moderate to Severe Liver Disease';
If term='Charlson_Malignancy_preTRUE' then label='Malignancy';
If term='Charlson_MalignancyMetastatic_pTRUE' then label='Metastatic Malignancy';
If term='Charlson_MI_preTRUE' then label='Myocardial Infarction';
If term='Charlson_PepticUlcer_preTRUE' then label='Peptic Ulcer';
If term='Charlson_PeripheralVascular_preTRUE' then label='Peripheral Vascular Disease';
If term='Charlson_Renal_preTRUE' then label='Renal Disease';
If term='Charlson_Rheumatic_preTRUE' then label='Rheumatic Disease';
If term='TT_Cardiology_preTRUE' then label='Cardiology Service';
If term='TT_CCU_HF_preTRUE' then label='Cardiac Care Unit-Heart Failure';
If term='TT_CCU_preTRUE' then label='Cardiac Care Unit';
If term='TT_HemeOnc_preTRUE' then label='Hemetalogy Oncology Service';
If term='TT_Medicine_preTRUE' then label='Medicine Service';
If term='TT_MICU_preTRUE' then label='Medical ICU';
If term='TT_Neurology_preTRUE' then label='Neorology Service';
If term='TT_SICU_preTRUE' then label='Surgical ICU';
If term='TT_SurgerySpecialty_preTRUE' then label='Surgery Service';
If term='TT_Transplant_preTRUE' then label='Transplant';
If term='TT_Trauma_preTRUE' then label='Trauma';
If term='TT_CVICU_preTRUE' then label='Cardiovascular ICU';
If term='locf_CO2_last' then label='Bicarbonate';
If term='locf_BUN_last' then label='Blood Urea Nitrogen';
If term='locf_CR_last' then label='Creatinine';
If term='locf_GCSS_last' then label='Glasgow Coma Score';
If term='locf_HCT_last' then label='Hematocrit';
If term='locf_PO2A_last' then label='Partial O2';
If term='locf_PHA_last' then label='PH ';
If term='locf_K_last' then label='Potassium';
If term='locf_Pulse_last' then label='Pulse';
If term='locf_Resp_last' then label='Respiration Rate';
If term='locf_NA_last' then label='Sodium';
If term='locf_BP_High_Systolic_last' then label='Systolic Blood Pressure';
If term='locf_Temp_last' then label='Temperature';
If term='locf_TBIL_last' then label='Total billirubin';
If term='locf_WBC_last' then label='White blood cells';
If term='ageYears' then order=1;
If term='inc' then order=3;
If term='self_payTRUE' then order=4;
If term='Female_preTRUE' then order=2;
If term='RaceUnknown_preTRUE' then order=11;
If term='RaceAsian_preTRUE' then order=6;
If term='RaceBlack_preTRUE' then order=5;
If term='all_latinosTRUE' then order=7;
If term='RaceOther_preTRUE' then order=10;
If term='RacePacificIslander_preTRUE' then order=8;
If term='RaceNativeAmerican_preTRUE' then order=9;
If term='AnyVasoactive_preTRUE' then order=13;
If term='AnyVentilator_preTRUE' then order=12;
If term='AnyCRRT_preTRUE' then order=14;
If term='Charlson_Cerebrovascular_preTRUE' then order=15;
If term='Charlson_CHF_preTRUE' then order=16;
If term='Charlson_COPD_preTRUE' then order=17;
If term='Charlson_Dementia_preTRUE' then order=18;
If term='Charlson_Diabetes_preTRUE' then order=19;
If term='Charlson_DiabetesComplications_TRUE' then order=20;
If term='Charlson_HemiplegiaParaplegia_pTRUE' then order=21;
If term='Charlson_LiverMild_preTRUE' then order=22;
If term='Charlson_LiverModSevere_preTRUE' then order=23;
If term='Charlson_Malignancy_preTRUE' then order=24;
If term='Charlson_MalignancyMetastatic_pTRUE' then order=25;
If term='Charlson_MI_preTRUE' then order=26;
If term='Charlson_PepticUlcer_preTRUE' then order=27;
If term='Charlson_PeripheralVascular_preTRUE' then order=28;
If term='Charlson_Renal_preTRUE' then order=29;
If term='Charlson_Rheumatic_preTRUE' then order=30;
If term='TT_Cardiology_preTRUE' then order=31;
If term='TT_CCU_HF_preTRUE' then order=32;
If term='TT_CCU_preTRUE' then order=33;
If term='TT_HemeOnc_preTRUE' then order=34;
If term='TT_Medicine_preTRUE' then order=35;
If term='TT_MICU_preTRUE' then order=36;
If term='TT_Neurology_preTRUE' then order=37;
If term='TT_SICU_preTRUE' then order=38;
If term='TT_SurgerySpecialty_preTRUE' then order=39;
If term='TT_Transplant_preTRUE' then order=40;
If term='TT_Trauma_preTRUE' then order=41;
If term='TT_CVICU_preTRUE' then order=42;
If term='locf_CO2_last' then order=43;
If term='locf_BUN_last' then order=44;
If term='locf_CR_last' then order=45;
If term='locf_GCSS_last' then order=46;
If term='locf_HCT_last' then order=47;
If term='locf_PO2A_last' then order=48;
If term='locf_PHA_last' then order=49;
If term='locf_K_last' then order=50;
If term='locf_Pulse_last' then order=51;
If term='locf_Resp_last' then order=52;
If term='locf_NA_last' then order=53;
If term='locf_BP_High_Systolic_last' then order=54;
If term='locf_Temp_last' then order=55;
If term='locf_TBIL_last' then order=56;
If term='locf_WBC_last' then order=57;
run;

proc sort data=ccforest; by set order;run;

ods graphics on /width=20in height=12in; 
proc sgpanel data=ccforest;where set in ("cc_minlocfit" "cc_maxlocfit" "cc_meanlocfit" "cc_fixedfit");
panelby set/columns=4;
scatter  x=expcoef y=label / xerrorlower=explcl            
xerrorupper=expucl  markerattrs=(symbol=DiamondFilled size=8);  
refline 1 / axis=x;
colaxis grid ;
rowaxis VALUEATTRS=(Family=Arial Size=8 Style=Italic );*Weight=Bold);
run;

***To compare estimates for each term;
ods graphics on /width=16in height=10in; 
proc sgpanel data=ccforest;
panelby label/columns=4 rows=2;
scatter  x=expcoef y=set / xerrorlower=explcl            
xerrorupper=expucl  markerattrs=(symbol=DiamondFilled size=8);  
refline 1 / axis=x;
colaxis grid ;
rowaxis VALUEATTRS=(Family=Arial Size=8 Style=Italic );*Weight=Bold);
run;

