nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read1.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read2.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read3.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read4.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read5.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read6.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read7.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read8.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read1.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read2.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read3.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read4.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read5.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read6.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read7.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read8.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read1.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read2.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read3.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read4.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read5.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read6.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read7.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read8.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read1.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read2.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read3.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read4.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read5.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read6.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read7.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read8.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read1.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read2.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read3.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read4.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read5.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read6.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read7.py &> results.log
nohup python2 -u CDSS/scripts/DevWorkshop/GoogleCloudPlatform/batch/cloud_read8.py &> results.log
