-- Medication Order Data Table.  Source headers need " removed, lower-case, and make sure refills column is numeric
-- 	Remove " marks and lower-case header lines
--	(Refills should be numeric 0 not char o.  Just swap "o" for "0")  (Entry 436981419... refills should be numeric, not "prn")
CREATE TABLE IF NOT EXISTS stride_order_med
(
	order_med_id BIGINT NOT NULL,
	pat_id TEXT,
	pat_enc_csn_id BIGINT,
	ordering_datetime TIMESTAMP,
	hosp_admsn_time TIMESTAMP,
	hosp_dischrg_time TIMESTAMP,
	order_class TEXT,
	medication_id INTEGER,
	description TEXT,
	sig TEXT,
	quantity TEXT,
	refills INTEGER,
	start_date TIMESTAMP,
	end_date TIMESTAMP,
	dispense_as_written_yn TEXT,
	reason_for_discontinuation TEXT,
	enc_type_c INTEGER,
	encounter_type TEXT,
	patient_location TEXT,
	login_department TEXT,
	display_name TEXT,
	hv_hospitalist_yn TEXT,
	med_route TEXT,
	discontinue_time TIMESTAMP,
	changed_from_order_med_id BIGINT,
	reason_pended_med_refused TEXT,
	hv_discr_freq_id BIGINT,
	discr_freq_name TEXT,
	discr_freq_display_name TEXT,
	discr_freq_type TEXT,
	discr_freq_number_of_times INTEGER,
	freq_time_unit TEXT,
	prn_yn TEXT,
	freq_duplicate_dose_interval INTEGER,
	freq_missed_dose_interval INTEGER,
	freqency_or_period TEXT,
	hv_discrete_dose TEXT,
	hv_dose_unit TEXT,
	non_formulary_yn TEXT,
	order_status TEXT,
	min_discrete_dose FLOAT,
	max_discrete_dose FLOAT,
	dose_unit TEXT,
	is_pending_ord_yn TEXT,
	modify_track TEXT,
	med_comments TEXT,
	usr_select_medicn_id INTEGER,
	lastdose TEXT,
	amb_med_disp_name TEXT,
	refills_remaining INTEGER,
	rule_based_order_transmittl_yn TEXT,
	outpat_orderstat_before_admsn TEXT,
	last_dose_time TEXT,
	pend_approve_flag TEXT,
	prn_comment TEXT,
	med_dis_disp_qty INTEGER,
	med_dis_disp_unit TEXT,
	CONSTRAINT stride_order_med_pkey PRIMARY KEY (order_med_id)
);
-- ALTER TABLE stride_order_med ADD CONSTRAINT stride_order_med_pkey PRIMARY KEY (order_med_id);
CREATE INDEX IF NOT EXISTS index_stride_order_med_pat_id ON stride_order_med(SUBSTRING(pat_id, 1, 16));
CREATE INDEX IF NOT EXISTS index_stride_order_med_ordering_datetime ON stride_order_med(ordering_datetime);
CREATE INDEX IF NOT EXISTS index_stride_order_med_pat_enc_csn_id ON stride_order_med(pat_enc_csn_id);
CREATE INDEX IF NOT EXISTS index_stride_order_med_medication_id ON stride_order_med(medication_id);
