--The goal is to create the microbiology_cultures_prior_med table, which includes binary indicators for specific medication 
exposure within various time frames.


######## Steps ##########

####################################################################################################################
--1. Creating the microbiology_cultures_prior_antibiotics_extracted Table.  To extract microbiology cultures and their 
    -- associated medications, along with the time frames of medication exposure.
####################################################################################################################

CREATE OR REPLACE TABLE `som-nero-phi-jonc101.antimicrobial_stewardship.microbiology_cultures_prior_antibiotics_extracted` AS
WITH microbiology_cultures AS (
    SELECT DISTINCT
        anon_id,
        pat_enc_csn_id_coded,
        order_proc_id_coded,
        order_time_jittered_utc
    FROM 
        `som-nero-phi-jonc101.antimicrobial_stewardship.microbiology_cultures_cohort`
),

cleaned_medications AS (
    SELECT 
        mc.anon_id,
        mc.pat_enc_csn_id_coded,
        mc.order_proc_id_coded,
        mc.order_time_jittered_utc,
        mo.ordering_date_jittered_utc,
        INITCAP(TRIM(
            REGEXP_REPLACE(
                REGEXP_REPLACE(
                    LOWER(mm.name),
                    'penicillin[^a-z].*$', 'penicillin'
                ),
                '^[^a-z]*|\\s+\\S*[^a-z\\s]+.*$|\\.+$', ''
            )
        )) AS medication_name
    FROM 
        microbiology_cultures mc
    INNER JOIN 
        `som-nero-phi-jonc101.shc_core_2023.order_med` mo
    ON 
        mc.anon_id = mo.anon_id
    LEFT JOIN 
        `som-nero-phi-jonc101.shc_core_2023.mapped_meds` mm
    ON 
        mo.med_description = mm.name
),

prior_antibiotics_exposure AS (
    SELECT 
        cm.anon_id,
        cm.pat_enc_csn_id_coded,
        cm.order_proc_id_coded,
        cm.order_time_jittered_utc,
        cm.medication_name,
        CASE 
            WHEN TIMESTAMP_DIFF(cm.order_time_jittered_utc, cm.ordering_date_jittered_utc, DAY) <= 7 THEN '7'
            WHEN TIMESTAMP_DIFF(cm.order_time_jittered_utc, cm.ordering_date_jittered_utc, DAY) <= 14 THEN '14'
            WHEN TIMESTAMP_DIFF(cm.order_time_jittered_utc, cm.ordering_date_jittered_utc, DAY) <= 30 THEN '30'
            WHEN TIMESTAMP_DIFF(cm.order_time_jittered_utc, cm.ordering_date_jittered_utc, DAY) <= 90 THEN '90'
            WHEN TIMESTAMP_DIFF(cm.order_time_jittered_utc, cm.ordering_date_jittered_utc, DAY) <= 180 THEN '180'
            ELSE 'ALL'
        END AS time_frame
    FROM 
        cleaned_medications cm
)

SELECT * FROM prior_antibiotics_exposure;


#######################################################################################################################################
-- 2. Cleaning the Extracted Data. Filters the extracted data and keeps only the rows from the list of antibiotics provided.
#######################################################################################################################################

CREATE OR REPLACE TABLE `som-nero-phi-jonc101.antimicrobial_stewardship.microbiology_cultures_prior_antibiotics_cleaned` AS
WITH antibiotic_list AS (
    SELECT antibiotic_name
    FROM `som-nero-phi-jonc101.antimicrobial_stewardship.temp_antibiotics`
)

SELECT 
    pae.anon_id,
    pae.pat_enc_csn_id_coded,
    pae.order_proc_id_coded,
    pae.order_time_jittered_utc,
    pae.medication_name,
    pae.time_frame
FROM 
    `som-nero-phi-jonc101.antimicrobial_stewardship.microbiology_cultures_prior_antibiotics_extracted` pae
INNER JOIN 
    antibiotic_list al
ON 
    pae.medication_name = al.antibiotic_name;


#######################################################################################################################################
-- 3. Generating the Final SQL Query using Python To create the final table microbiology_cultures_prior_med with binary indicators for 
   -- each antibiotic and each time frame.
#######################################################################################################################################

-- Create the pivoted table with binary indicators
CREATE OR REPLACE TABLE `som-nero-phi-jonc101.antimicrobial_stewardship.microbiology_cultures_prior_med` AS
WITH
-- Select all necessary fields and create binary indicators for each antibiotic and time frame
binary_indicators AS (
    SELECT
        anon_id,
        pat_enc_csn_id_coded,
        order_proc_id_coded,
        order_time_jittered_utc,
        medication_name,
        time_frame,
        CASE WHEN time_frame = '7' THEN 1 ELSE 0 END AS medication_7_days,
        CASE WHEN time_frame = '14' THEN 1 ELSE 0 END AS medication_14_days,
        CASE WHEN time_frame = '30' THEN 1 ELSE 0 END AS medication_30_days,
        CASE WHEN time_frame = '90' THEN 1 ELSE 0 END AS medication_90_days,
        CASE WHEN time_frame = '180' THEN 1 ELSE 0 END AS medication_180_days,
        CASE WHEN time_frame = 'ALL' THEN 1 ELSE 0 END AS medication_all_time
    FROM
        `som-nero-phi-jonc101.antimicrobial_stewardship.microbiology_cultures_prior_antibiotics_cleaned`
)
-- Pivot the table to create separate columns for each antibiotic and time frame
SELECT
    anon_id,
    pat_enc_csn_id_coded,
    order_proc_id_coded,
    order_time_jittered_utc,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS NIT_7_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS NIT_14_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS NIT_30_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS NIT_90_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS NIT_180_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS NIT_all_time,
    MAX(CASE WHEN medication_name = 'Cephalexin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEP_7_days,
    MAX(CASE WHEN medication_name = 'Cephalexin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEP_14_days,
    MAX(CASE WHEN medication_name = 'Cephalexin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEP_30_days,
    MAX(CASE WHEN medication_name = 'Cephalexin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEP_90_days,
    MAX(CASE WHEN medication_name = 'Cephalexin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEP_180_days,
    MAX(CASE WHEN medication_name = 'Cephalexin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEP_all_time,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam-Dextrs' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS PIP_7_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam-Dextrs' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS PIP_14_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam-Dextrs' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS PIP_30_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam-Dextrs' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS PIP_90_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam-Dextrs' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS PIP_180_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam-Dextrs' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS PIP_all_time,
    MAX(CASE WHEN medication_name = 'Sulfamethoxazole-Trimethoprim' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS SUL_7_days,
    MAX(CASE WHEN medication_name = 'Sulfamethoxazole-Trimethoprim' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS SUL_14_days,
    MAX(CASE WHEN medication_name = 'Sulfamethoxazole-Trimethoprim' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS SUL_30_days,
    MAX(CASE WHEN medication_name = 'Sulfamethoxazole-Trimethoprim' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS SUL_90_days,
    MAX(CASE WHEN medication_name = 'Sulfamethoxazole-Trimethoprim' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS SUL_180_days,
    MAX(CASE WHEN medication_name = 'Sulfamethoxazole-Trimethoprim' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS SUL_all_time,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin Hcl' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CIP_7_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin Hcl' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CIP_14_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin Hcl' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CIP_30_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin Hcl' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CIP_90_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin Hcl' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CIP_180_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin Hcl' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CIP_all_time,
    MAX(CASE WHEN medication_name = 'Cefazolin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF_7_days,
    MAX(CASE WHEN medication_name = 'Cefazolin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF_14_days,
    MAX(CASE WHEN medication_name = 'Cefazolin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF_30_days,
    MAX(CASE WHEN medication_name = 'Cefazolin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF_90_days,
    MAX(CASE WHEN medication_name = 'Cefazolin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF_180_days,
    MAX(CASE WHEN medication_name = 'Cefazolin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF_all_time,
    MAX(CASE WHEN medication_name = 'Cefazolin In Dextrose' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF1_7_days,
    MAX(CASE WHEN medication_name = 'Cefazolin In Dextrose' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF1_14_days,
    MAX(CASE WHEN medication_name = 'Cefazolin In Dextrose' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF1_30_days,
    MAX(CASE WHEN medication_name = 'Cefazolin In Dextrose' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF1_90_days,
    MAX(CASE WHEN medication_name = 'Cefazolin In Dextrose' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF1_180_days,
    MAX(CASE WHEN medication_name = 'Cefazolin In Dextrose' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF1_all_time,
    MAX(CASE WHEN medication_name = 'Levofloxacin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS LEV_7_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS LEV_14_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS LEV_30_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS LEV_90_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS LEV_180_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS LEV_all_time,
    MAX(CASE WHEN medication_name = 'Azithromycin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AZI_7_days,
    MAX(CASE WHEN medication_name = 'Azithromycin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AZI_14_days,
    MAX(CASE WHEN medication_name = 'Azithromycin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AZI_30_days,
    MAX(CASE WHEN medication_name = 'Azithromycin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AZI_90_days,
    MAX(CASE WHEN medication_name = 'Azithromycin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AZI_180_days,
    MAX(CASE WHEN medication_name = 'Azithromycin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AZI_all_time,
    MAX(CASE WHEN medication_name = 'Amoxicillin-Pot Clavulanate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AMO_7_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin-Pot Clavulanate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AMO_14_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin-Pot Clavulanate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AMO_30_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin-Pot Clavulanate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AMO_90_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin-Pot Clavulanate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AMO_180_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin-Pot Clavulanate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AMO_all_time,
    MAX(CASE WHEN medication_name = 'Metronidazole In Nacl' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MET_7_days,
    MAX(CASE WHEN medication_name = 'Metronidazole In Nacl' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MET_14_days,
    MAX(CASE WHEN medication_name = 'Metronidazole In Nacl' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MET_30_days,
    MAX(CASE WHEN medication_name = 'Metronidazole In Nacl' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MET_90_days,
    MAX(CASE WHEN medication_name = 'Metronidazole In Nacl' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MET_180_days,
    MAX(CASE WHEN medication_name = 'Metronidazole In Nacl' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MET_all_time,
    MAX(CASE WHEN medication_name = 'Ceftriaxone' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF2_7_days,
    MAX(CASE WHEN medication_name = 'Ceftriaxone' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF2_14_days,
    MAX(CASE WHEN medication_name = 'Ceftriaxone' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF2_30_days,
    MAX(CASE WHEN medication_name = 'Ceftriaxone' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF2_90_days,
    MAX(CASE WHEN medication_name = 'Ceftriaxone' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF2_180_days,
    MAX(CASE WHEN medication_name = 'Ceftriaxone' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF2_all_time,
    MAX(CASE WHEN medication_name = 'Vancomycin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS VAN_7_days,
    MAX(CASE WHEN medication_name = 'Vancomycin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS VAN_14_days,
    MAX(CASE WHEN medication_name = 'Vancomycin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS VAN_30_days,
    MAX(CASE WHEN medication_name = 'Vancomycin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS VAN_90_days,
    MAX(CASE WHEN medication_name = 'Vancomycin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS VAN_180_days,
    MAX(CASE WHEN medication_name = 'Vancomycin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS VAN_all_time,
    MAX(CASE WHEN medication_name = 'Levofloxacin In' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS LEV1_7_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin In' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS LEV1_14_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin In' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS LEV1_30_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin In' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS LEV1_90_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin In' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS LEV1_180_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin In' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS LEV1_all_time,
    MAX(CASE WHEN medication_name = 'Vancomycin In Dextrose' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS VAN1_7_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In Dextrose' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS VAN1_14_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In Dextrose' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS VAN1_30_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In Dextrose' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS VAN1_90_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In Dextrose' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS VAN1_180_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In Dextrose' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS VAN1_all_time,
    MAX(CASE WHEN medication_name = 'Metronidazole' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MET1_7_days,
    MAX(CASE WHEN medication_name = 'Metronidazole' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MET1_14_days,
    MAX(CASE WHEN medication_name = 'Metronidazole' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MET1_30_days,
    MAX(CASE WHEN medication_name = 'Metronidazole' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MET1_90_days,
    MAX(CASE WHEN medication_name = 'Metronidazole' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MET1_180_days,
    MAX(CASE WHEN medication_name = 'Metronidazole' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MET1_all_time,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin In' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CIP1_7_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin In' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CIP1_14_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin In' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CIP1_30_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin In' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CIP1_90_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin In' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CIP1_180_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin In' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CIP1_all_time,
    MAX(CASE WHEN medication_name = 'Doxycycline Hyclate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS DOX_7_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Hyclate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS DOX_14_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Hyclate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS DOX_30_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Hyclate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS DOX_90_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Hyclate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS DOX_180_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Hyclate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS DOX_all_time,
    MAX(CASE WHEN medication_name = 'Cefpodoxime' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF3_7_days,
    MAX(CASE WHEN medication_name = 'Cefpodoxime' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF3_14_days,
    MAX(CASE WHEN medication_name = 'Cefpodoxime' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF3_30_days,
    MAX(CASE WHEN medication_name = 'Cefpodoxime' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF3_90_days,
    MAX(CASE WHEN medication_name = 'Cefpodoxime' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF3_180_days,
    MAX(CASE WHEN medication_name = 'Cefpodoxime' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF3_all_time,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS PIP1_7_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS PIP1_14_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS PIP1_30_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS PIP1_90_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS PIP1_180_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS PIP1_all_time,
    MAX(CASE WHEN medication_name = 'Rifaximin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS RIF_7_days,
    MAX(CASE WHEN medication_name = 'Rifaximin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS RIF_14_days,
    MAX(CASE WHEN medication_name = 'Rifaximin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS RIF_30_days,
    MAX(CASE WHEN medication_name = 'Rifaximin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS RIF_90_days,
    MAX(CASE WHEN medication_name = 'Rifaximin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS RIF_180_days,
    MAX(CASE WHEN medication_name = 'Rifaximin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS RIF_all_time,
    MAX(CASE WHEN medication_name = 'Vancomycin-Diluent Combo' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS VAN2_7_days,
    MAX(CASE WHEN medication_name = 'Vancomycin-Diluent Combo' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS VAN2_14_days,
    MAX(CASE WHEN medication_name = 'Vancomycin-Diluent Combo' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS VAN2_30_days,
    MAX(CASE WHEN medication_name = 'Vancomycin-Diluent Combo' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS VAN2_90_days,
    MAX(CASE WHEN medication_name = 'Vancomycin-Diluent Combo' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS VAN2_180_days,
    MAX(CASE WHEN medication_name = 'Vancomycin-Diluent Combo' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS VAN2_all_time,
    MAX(CASE WHEN medication_name = 'Clindamycin In' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CLI_7_days,
    MAX(CASE WHEN medication_name = 'Clindamycin In' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CLI_14_days,
    MAX(CASE WHEN medication_name = 'Clindamycin In' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CLI_30_days,
    MAX(CASE WHEN medication_name = 'Clindamycin In' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CLI_90_days,
    MAX(CASE WHEN medication_name = 'Clindamycin In' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CLI_180_days,
    MAX(CASE WHEN medication_name = 'Clindamycin In' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CLI_all_time,
    MAX(CASE WHEN medication_name = 'Amoxicillin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AMO1_7_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AMO1_14_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AMO1_30_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AMO1_90_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AMO1_180_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AMO1_all_time,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin Macrocrystal' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS NIT1_7_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin Macrocrystal' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS NIT1_14_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin Macrocrystal' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS NIT1_30_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin Macrocrystal' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS NIT1_90_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin Macrocrystal' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS NIT1_180_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin Macrocrystal' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS NIT1_all_time,
    MAX(CASE WHEN medication_name = 'Macrobid' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MAC_7_days,
    MAX(CASE WHEN medication_name = 'Macrobid' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MAC_14_days,
    MAX(CASE WHEN medication_name = 'Macrobid' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MAC_30_days,
    MAX(CASE WHEN medication_name = 'Macrobid' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MAC_90_days,
    MAX(CASE WHEN medication_name = 'Macrobid' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MAC_180_days,
    MAX(CASE WHEN medication_name = 'Macrobid' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MAC_all_time,
    MAX(CASE WHEN medication_name = 'Gentamicin-Sodium Citrate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS GEN_7_days,
    MAX(CASE WHEN medication_name = 'Gentamicin-Sodium Citrate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS GEN_14_days,
    MAX(CASE WHEN medication_name = 'Gentamicin-Sodium Citrate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS GEN_30_days,
    MAX(CASE WHEN medication_name = 'Gentamicin-Sodium Citrate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS GEN_90_days,
    MAX(CASE WHEN medication_name = 'Gentamicin-Sodium Citrate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS GEN_180_days,
    MAX(CASE WHEN medication_name = 'Gentamicin-Sodium Citrate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS GEN_all_time,
    MAX(CASE WHEN medication_name = 'Cefdinir' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF4_7_days,
    MAX(CASE WHEN medication_name = 'Cefdinir' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF4_14_days,
    MAX(CASE WHEN medication_name = 'Cefdinir' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF4_30_days,
    MAX(CASE WHEN medication_name = 'Cefdinir' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF4_90_days,
    MAX(CASE WHEN medication_name = 'Cefdinir' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF4_180_days,
    MAX(CASE WHEN medication_name = 'Cefdinir' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF4_all_time,
    MAX(CASE WHEN medication_name = 'Clindamycin Phosphate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CLI1_7_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Phosphate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CLI1_14_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Phosphate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CLI1_30_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Phosphate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CLI1_90_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Phosphate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CLI1_180_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Phosphate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CLI1_all_time,
    MAX(CASE WHEN medication_name = 'Cefoxitin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF5_7_days,
    MAX(CASE WHEN medication_name = 'Cefoxitin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF5_14_days,
    MAX(CASE WHEN medication_name = 'Cefoxitin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF5_30_days,
    MAX(CASE WHEN medication_name = 'Cefoxitin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF5_90_days,
    MAX(CASE WHEN medication_name = 'Cefoxitin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF5_180_days,
    MAX(CASE WHEN medication_name = 'Cefoxitin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF5_all_time,
    MAX(CASE WHEN medication_name = 'Cipro' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CIP2_7_days,
    MAX(CASE WHEN medication_name = 'Cipro' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CIP2_14_days,
    MAX(CASE WHEN medication_name = 'Cipro' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CIP2_30_days,
    MAX(CASE WHEN medication_name = 'Cipro' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CIP2_90_days,
    MAX(CASE WHEN medication_name = 'Cipro' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CIP2_180_days,
    MAX(CASE WHEN medication_name = 'Cipro' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CIP2_all_time,
    MAX(CASE WHEN medication_name = 'Clindamycin Hcl' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CLI2_7_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Hcl' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CLI2_14_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Hcl' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CLI2_30_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Hcl' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CLI2_90_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Hcl' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CLI2_180_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Hcl' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CLI2_all_time,
    MAX(CASE WHEN medication_name = 'Vancomycin In' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS VAN3_7_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS VAN3_14_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS VAN3_30_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS VAN3_90_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS VAN3_180_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS VAN3_all_time,
    MAX(CASE WHEN medication_name = 'Moxifloxacin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MOX_7_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MOX_14_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MOX_30_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MOX_90_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MOX_180_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MOX_all_time,
    MAX(CASE WHEN medication_name = 'Gentamicin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS GEN1_7_days,
    MAX(CASE WHEN medication_name = 'Gentamicin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS GEN1_14_days,
    MAX(CASE WHEN medication_name = 'Gentamicin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS GEN1_30_days,
    MAX(CASE WHEN medication_name = 'Gentamicin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS GEN1_90_days,
    MAX(CASE WHEN medication_name = 'Gentamicin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS GEN1_180_days,
    MAX(CASE WHEN medication_name = 'Gentamicin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS GEN1_all_time,
    MAX(CASE WHEN medication_name = 'Linezolid' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS LIN_7_days,
    MAX(CASE WHEN medication_name = 'Linezolid' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS LIN_14_days,
    MAX(CASE WHEN medication_name = 'Linezolid' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS LIN_30_days,
    MAX(CASE WHEN medication_name = 'Linezolid' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS LIN_90_days,
    MAX(CASE WHEN medication_name = 'Linezolid' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS LIN_180_days,
    MAX(CASE WHEN medication_name = 'Linezolid' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS LIN_all_time,
    MAX(CASE WHEN medication_name = 'Zithromax' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS ZIT_7_days,
    MAX(CASE WHEN medication_name = 'Zithromax' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS ZIT_14_days,
    MAX(CASE WHEN medication_name = 'Zithromax' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS ZIT_30_days,
    MAX(CASE WHEN medication_name = 'Zithromax' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS ZIT_90_days,
    MAX(CASE WHEN medication_name = 'Zithromax' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS ZIT_180_days,
    MAX(CASE WHEN medication_name = 'Zithromax' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS ZIT_all_time,
    MAX(CASE WHEN medication_name = 'Erythromycin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS ERY_7_days,
    MAX(CASE WHEN medication_name = 'Erythromycin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS ERY_14_days,
    MAX(CASE WHEN medication_name = 'Erythromycin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS ERY_30_days,
    MAX(CASE WHEN medication_name = 'Erythromycin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS ERY_90_days,
    MAX(CASE WHEN medication_name = 'Erythromycin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS ERY_180_days,
    MAX(CASE WHEN medication_name = 'Erythromycin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS ERY_all_time,
    MAX(CASE WHEN medication_name = 'Bactrim Ds' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS BAC_7_days,
    MAX(CASE WHEN medication_name = 'Bactrim Ds' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS BAC_14_days,
    MAX(CASE WHEN medication_name = 'Bactrim Ds' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS BAC_30_days,
    MAX(CASE WHEN medication_name = 'Bactrim Ds' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS BAC_90_days,
    MAX(CASE WHEN medication_name = 'Bactrim Ds' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS BAC_180_days,
    MAX(CASE WHEN medication_name = 'Bactrim Ds' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS BAC_all_time,
    MAX(CASE WHEN medication_name = 'Fosfomycin Tromethamine' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS FOS_7_days,
    MAX(CASE WHEN medication_name = 'Fosfomycin Tromethamine' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS FOS_14_days,
    MAX(CASE WHEN medication_name = 'Fosfomycin Tromethamine' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS FOS_30_days,
    MAX(CASE WHEN medication_name = 'Fosfomycin Tromethamine' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS FOS_90_days,
    MAX(CASE WHEN medication_name = 'Fosfomycin Tromethamine' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS FOS_180_days,
    MAX(CASE WHEN medication_name = 'Fosfomycin Tromethamine' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS FOS_all_time,
    MAX(CASE WHEN medication_name = 'Cefepime' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF6_7_days,
    MAX(CASE WHEN medication_name = 'Cefepime' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF6_14_days,
    MAX(CASE WHEN medication_name = 'Cefepime' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF6_30_days,
    MAX(CASE WHEN medication_name = 'Cefepime' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF6_90_days,
    MAX(CASE WHEN medication_name = 'Cefepime' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF6_180_days,
    MAX(CASE WHEN medication_name = 'Cefepime' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF6_all_time,
    MAX(CASE WHEN medication_name = 'Keflex' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS KEF_7_days,
    MAX(CASE WHEN medication_name = 'Keflex' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS KEF_14_days,
    MAX(CASE WHEN medication_name = 'Keflex' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS KEF_30_days,
    MAX(CASE WHEN medication_name = 'Keflex' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS KEF_90_days,
    MAX(CASE WHEN medication_name = 'Keflex' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS KEF_180_days,
    MAX(CASE WHEN medication_name = 'Keflex' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS KEF_all_time,
    MAX(CASE WHEN medication_name = 'Colistin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS COL_7_days,
    MAX(CASE WHEN medication_name = 'Colistin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS COL_14_days,
    MAX(CASE WHEN medication_name = 'Colistin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS COL_30_days,
    MAX(CASE WHEN medication_name = 'Colistin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS COL_90_days,
    MAX(CASE WHEN medication_name = 'Colistin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS COL_180_days,
    MAX(CASE WHEN medication_name = 'Colistin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS COL_all_time,
    MAX(CASE WHEN medication_name = 'Doxycycline Monohydrate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS DOX1_7_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Monohydrate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS DOX1_14_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Monohydrate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS DOX1_30_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Monohydrate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS DOX1_90_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Monohydrate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS DOX1_180_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Monohydrate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS DOX1_all_time,
    MAX(CASE WHEN medication_name = 'Levaquin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS LEV2_7_days,
    MAX(CASE WHEN medication_name = 'Levaquin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS LEV2_14_days,
    MAX(CASE WHEN medication_name = 'Levaquin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS LEV2_30_days,
    MAX(CASE WHEN medication_name = 'Levaquin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS LEV2_90_days,
    MAX(CASE WHEN medication_name = 'Levaquin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS LEV2_180_days,
    MAX(CASE WHEN medication_name = 'Levaquin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS LEV2_all_time,
    MAX(CASE WHEN medication_name = 'Clarithromycin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CLA_7_days,
    MAX(CASE WHEN medication_name = 'Clarithromycin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CLA_14_days,
    MAX(CASE WHEN medication_name = 'Clarithromycin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CLA_30_days,
    MAX(CASE WHEN medication_name = 'Clarithromycin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CLA_90_days,
    MAX(CASE WHEN medication_name = 'Clarithromycin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CLA_180_days,
    MAX(CASE WHEN medication_name = 'Clarithromycin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CLA_all_time,
    MAX(CASE WHEN medication_name = 'Rifampin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS RIF1_7_days,
    MAX(CASE WHEN medication_name = 'Rifampin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS RIF1_14_days,
    MAX(CASE WHEN medication_name = 'Rifampin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS RIF1_30_days,
    MAX(CASE WHEN medication_name = 'Rifampin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS RIF1_90_days,
    MAX(CASE WHEN medication_name = 'Rifampin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS RIF1_180_days,
    MAX(CASE WHEN medication_name = 'Rifampin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS RIF1_all_time,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CIP3_7_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CIP3_14_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CIP3_30_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CIP3_90_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CIP3_180_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CIP3_all_time,
    MAX(CASE WHEN medication_name = 'Cefuroxime Axetil' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF7_7_days,
    MAX(CASE WHEN medication_name = 'Cefuroxime Axetil' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF7_14_days,
    MAX(CASE WHEN medication_name = 'Cefuroxime Axetil' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF7_30_days,
    MAX(CASE WHEN medication_name = 'Cefuroxime Axetil' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF7_90_days,
    MAX(CASE WHEN medication_name = 'Cefuroxime Axetil' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF7_180_days,
    MAX(CASE WHEN medication_name = 'Cefuroxime Axetil' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF7_all_time,
    MAX(CASE WHEN medication_name = 'Augmentin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AUG_7_days,
    MAX(CASE WHEN medication_name = 'Augmentin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AUG_14_days,
    MAX(CASE WHEN medication_name = 'Augmentin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AUG_30_days,
    MAX(CASE WHEN medication_name = 'Augmentin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AUG_90_days,
    MAX(CASE WHEN medication_name = 'Augmentin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AUG_180_days,
    MAX(CASE WHEN medication_name = 'Augmentin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AUG_all_time,
    MAX(CASE WHEN medication_name = 'Cefadroxil' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF8_7_days,
    MAX(CASE WHEN medication_name = 'Cefadroxil' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF8_14_days,
    MAX(CASE WHEN medication_name = 'Cefadroxil' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF8_30_days,
    MAX(CASE WHEN medication_name = 'Cefadroxil' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF8_90_days,
    MAX(CASE WHEN medication_name = 'Cefadroxil' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF8_180_days,
    MAX(CASE WHEN medication_name = 'Cefadroxil' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF8_all_time,
    MAX(CASE WHEN medication_name = 'Methenamine Hippurate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MET2_7_days,
    MAX(CASE WHEN medication_name = 'Methenamine Hippurate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MET2_14_days,
    MAX(CASE WHEN medication_name = 'Methenamine Hippurate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MET2_30_days,
    MAX(CASE WHEN medication_name = 'Methenamine Hippurate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MET2_90_days,
    MAX(CASE WHEN medication_name = 'Methenamine Hippurate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MET2_180_days,
    MAX(CASE WHEN medication_name = 'Methenamine Hippurate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MET2_all_time,
    MAX(CASE WHEN medication_name = 'Ertapenem' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS ERT_7_days,
    MAX(CASE WHEN medication_name = 'Ertapenem' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS ERT_14_days,
    MAX(CASE WHEN medication_name = 'Ertapenem' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS ERT_30_days,
    MAX(CASE WHEN medication_name = 'Ertapenem' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS ERT_90_days,
    MAX(CASE WHEN medication_name = 'Ertapenem' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS ERT_180_days,
    MAX(CASE WHEN medication_name = 'Ertapenem' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS ERT_all_time,
    MAX(CASE WHEN medication_name = 'Linezolid In Dextrose' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS LIN1_7_days,
    MAX(CASE WHEN medication_name = 'Linezolid In Dextrose' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS LIN1_14_days,
    MAX(CASE WHEN medication_name = 'Linezolid In Dextrose' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS LIN1_30_days,
    MAX(CASE WHEN medication_name = 'Linezolid In Dextrose' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS LIN1_90_days,
    MAX(CASE WHEN medication_name = 'Linezolid In Dextrose' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS LIN1_180_days,
    MAX(CASE WHEN medication_name = 'Linezolid In Dextrose' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS LIN1_all_time,
    MAX(CASE WHEN medication_name = 'Ofloxacin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS OFL_7_days,
    MAX(CASE WHEN medication_name = 'Ofloxacin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS OFL_14_days,
    MAX(CASE WHEN medication_name = 'Ofloxacin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS OFL_30_days,
    MAX(CASE WHEN medication_name = 'Ofloxacin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS OFL_90_days,
    MAX(CASE WHEN medication_name = 'Ofloxacin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS OFL_180_days,
    MAX(CASE WHEN medication_name = 'Ofloxacin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS OFL_all_time,
    MAX(CASE WHEN medication_name = 'Penicillin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS PEN_7_days,
    MAX(CASE WHEN medication_name = 'Penicillin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS PEN_14_days,
    MAX(CASE WHEN medication_name = 'Penicillin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS PEN_30_days,
    MAX(CASE WHEN medication_name = 'Penicillin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS PEN_90_days,
    MAX(CASE WHEN medication_name = 'Penicillin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS PEN_180_days,
    MAX(CASE WHEN medication_name = 'Penicillin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS PEN_all_time,
    MAX(CASE WHEN medication_name = 'Silver Sulfadiazine' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS SIL_7_days,
    MAX(CASE WHEN medication_name = 'Silver Sulfadiazine' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS SIL_14_days,
    MAX(CASE WHEN medication_name = 'Silver Sulfadiazine' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS SIL_30_days,
    MAX(CASE WHEN medication_name = 'Silver Sulfadiazine' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS SIL_90_days,
    MAX(CASE WHEN medication_name = 'Silver Sulfadiazine' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS SIL_180_days,
    MAX(CASE WHEN medication_name = 'Silver Sulfadiazine' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS SIL_all_time,
    MAX(CASE WHEN medication_name = 'Dapsone' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS DAP_7_days,
    MAX(CASE WHEN medication_name = 'Dapsone' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS DAP_14_days,
    MAX(CASE WHEN medication_name = 'Dapsone' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS DAP_30_days,
    MAX(CASE WHEN medication_name = 'Dapsone' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS DAP_90_days,
    MAX(CASE WHEN medication_name = 'Dapsone' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS DAP_180_days,
    MAX(CASE WHEN medication_name = 'Dapsone' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS DAP_all_time,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin-Dexamethasone' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CIP4_7_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin-Dexamethasone' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CIP4_14_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin-Dexamethasone' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CIP4_30_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin-Dexamethasone' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CIP4_90_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin-Dexamethasone' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CIP4_180_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin-Dexamethasone' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CIP4_all_time,
    MAX(CASE WHEN medication_name = 'Ampicillin Sodium' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AMP_7_days,
    MAX(CASE WHEN medication_name = 'Ampicillin Sodium' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AMP_14_days,
    MAX(CASE WHEN medication_name = 'Ampicillin Sodium' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AMP_30_days,
    MAX(CASE WHEN medication_name = 'Ampicillin Sodium' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AMP_90_days,
    MAX(CASE WHEN medication_name = 'Ampicillin Sodium' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AMP_180_days,
    MAX(CASE WHEN medication_name = 'Ampicillin Sodium' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AMP_all_time,
    MAX(CASE WHEN medication_name = 'Isoniazid' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS ISO_7_days,
    MAX(CASE WHEN medication_name = 'Isoniazid' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS ISO_14_days,
    MAX(CASE WHEN medication_name = 'Isoniazid' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS ISO_30_days,
    MAX(CASE WHEN medication_name = 'Isoniazid' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS ISO_90_days,
    MAX(CASE WHEN medication_name = 'Isoniazid' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS ISO_180_days,
    MAX(CASE WHEN medication_name = 'Isoniazid' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS ISO_all_time,
    MAX(CASE WHEN medication_name = 'Bactrim' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS BAC1_7_days,
    MAX(CASE WHEN medication_name = 'Bactrim' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS BAC1_14_days,
    MAX(CASE WHEN medication_name = 'Bactrim' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS BAC1_30_days,
    MAX(CASE WHEN medication_name = 'Bactrim' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS BAC1_90_days,
    MAX(CASE WHEN medication_name = 'Bactrim' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS BAC1_180_days,
    MAX(CASE WHEN medication_name = 'Bactrim' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS BAC1_all_time,
    MAX(CASE WHEN medication_name = 'Fidaxomicin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS FID_7_days,
    MAX(CASE WHEN medication_name = 'Fidaxomicin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS FID_14_days,
    MAX(CASE WHEN medication_name = 'Fidaxomicin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS FID_30_days,
    MAX(CASE WHEN medication_name = 'Fidaxomicin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS FID_90_days,
    MAX(CASE WHEN medication_name = 'Fidaxomicin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS FID_180_days,
    MAX(CASE WHEN medication_name = 'Fidaxomicin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS FID_all_time,
    MAX(CASE WHEN medication_name = 'Aztreonam In' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AZT_7_days,
    MAX(CASE WHEN medication_name = 'Aztreonam In' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AZT_14_days,
    MAX(CASE WHEN medication_name = 'Aztreonam In' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AZT_30_days,
    MAX(CASE WHEN medication_name = 'Aztreonam In' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AZT_90_days,
    MAX(CASE WHEN medication_name = 'Aztreonam In' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AZT_180_days,
    MAX(CASE WHEN medication_name = 'Aztreonam In' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AZT_all_time,
    MAX(CASE WHEN medication_name = 'Ethambutol' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS ETH_7_days,
    MAX(CASE WHEN medication_name = 'Ethambutol' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS ETH_14_days,
    MAX(CASE WHEN medication_name = 'Ethambutol' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS ETH_30_days,
    MAX(CASE WHEN medication_name = 'Ethambutol' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS ETH_90_days,
    MAX(CASE WHEN medication_name = 'Ethambutol' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS ETH_180_days,
    MAX(CASE WHEN medication_name = 'Ethambutol' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS ETH_all_time,
    MAX(CASE WHEN medication_name = 'Tobramycin Sulfate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS TOB_7_days,
    MAX(CASE WHEN medication_name = 'Tobramycin Sulfate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS TOB_14_days,
    MAX(CASE WHEN medication_name = 'Tobramycin Sulfate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS TOB_30_days,
    MAX(CASE WHEN medication_name = 'Tobramycin Sulfate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS TOB_90_days,
    MAX(CASE WHEN medication_name = 'Tobramycin Sulfate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS TOB_180_days,
    MAX(CASE WHEN medication_name = 'Tobramycin Sulfate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS TOB_all_time,
    MAX(CASE WHEN medication_name = 'Cefepime In' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF9_7_days,
    MAX(CASE WHEN medication_name = 'Cefepime In' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF9_14_days,
    MAX(CASE WHEN medication_name = 'Cefepime In' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF9_30_days,
    MAX(CASE WHEN medication_name = 'Cefepime In' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF9_90_days,
    MAX(CASE WHEN medication_name = 'Cefepime In' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF9_180_days,
    MAX(CASE WHEN medication_name = 'Cefepime In' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF9_all_time,
    MAX(CASE WHEN medication_name = 'Ampicillin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AMP1_7_days,
    MAX(CASE WHEN medication_name = 'Ampicillin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AMP1_14_days,
    MAX(CASE WHEN medication_name = 'Ampicillin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AMP1_30_days,
    MAX(CASE WHEN medication_name = 'Ampicillin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AMP1_90_days,
    MAX(CASE WHEN medication_name = 'Ampicillin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AMP1_180_days,
    MAX(CASE WHEN medication_name = 'Ampicillin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AMP1_all_time,
    MAX(CASE WHEN medication_name = 'Minocycline' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MIN_7_days,
    MAX(CASE WHEN medication_name = 'Minocycline' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MIN_14_days,
    MAX(CASE WHEN medication_name = 'Minocycline' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MIN_30_days,
    MAX(CASE WHEN medication_name = 'Minocycline' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MIN_90_days,
    MAX(CASE WHEN medication_name = 'Minocycline' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MIN_180_days,
    MAX(CASE WHEN medication_name = 'Minocycline' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MIN_all_time,
    MAX(CASE WHEN medication_name = 'Ceftazidime-Dextrose' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF10_7_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime-Dextrose' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF10_14_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime-Dextrose' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF10_30_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime-Dextrose' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF10_90_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime-Dextrose' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF10_180_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime-Dextrose' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF10_all_time,
    MAX(CASE WHEN medication_name = 'Aztreonam' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AZT1_7_days,
    MAX(CASE WHEN medication_name = 'Aztreonam' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AZT1_14_days,
    MAX(CASE WHEN medication_name = 'Aztreonam' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AZT1_30_days,
    MAX(CASE WHEN medication_name = 'Aztreonam' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AZT1_90_days,
    MAX(CASE WHEN medication_name = 'Aztreonam' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AZT1_180_days,
    MAX(CASE WHEN medication_name = 'Aztreonam' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AZT1_all_time,
    MAX(CASE WHEN medication_name = 'Xifaxan' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS XIF_7_days,
    MAX(CASE WHEN medication_name = 'Xifaxan' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS XIF_14_days,
    MAX(CASE WHEN medication_name = 'Xifaxan' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS XIF_30_days,
    MAX(CASE WHEN medication_name = 'Xifaxan' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS XIF_90_days,
    MAX(CASE WHEN medication_name = 'Xifaxan' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS XIF_180_days,
    MAX(CASE WHEN medication_name = 'Xifaxan' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS XIF_all_time,
    MAX(CASE WHEN medication_name = 'Erythromycin Ethylsuccinate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS ERY1_7_days,
    MAX(CASE WHEN medication_name = 'Erythromycin Ethylsuccinate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS ERY1_14_days,
    MAX(CASE WHEN medication_name = 'Erythromycin Ethylsuccinate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS ERY1_30_days,
    MAX(CASE WHEN medication_name = 'Erythromycin Ethylsuccinate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS ERY1_90_days,
    MAX(CASE WHEN medication_name = 'Erythromycin Ethylsuccinate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS ERY1_180_days,
    MAX(CASE WHEN medication_name = 'Erythromycin Ethylsuccinate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS ERY1_all_time,
    MAX(CASE WHEN medication_name = 'Gentamicin In Nacl' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS GEN2_7_days,
    MAX(CASE WHEN medication_name = 'Gentamicin In Nacl' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS GEN2_14_days,
    MAX(CASE WHEN medication_name = 'Gentamicin In Nacl' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS GEN2_30_days,
    MAX(CASE WHEN medication_name = 'Gentamicin In Nacl' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS GEN2_90_days,
    MAX(CASE WHEN medication_name = 'Gentamicin In Nacl' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS GEN2_180_days,
    MAX(CASE WHEN medication_name = 'Gentamicin In Nacl' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS GEN2_all_time,
    MAX(CASE WHEN medication_name = 'Meropenem' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MER_7_days,
    MAX(CASE WHEN medication_name = 'Meropenem' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MER_14_days,
    MAX(CASE WHEN medication_name = 'Meropenem' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MER_30_days,
    MAX(CASE WHEN medication_name = 'Meropenem' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MER_90_days,
    MAX(CASE WHEN medication_name = 'Meropenem' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MER_180_days,
    MAX(CASE WHEN medication_name = 'Meropenem' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MER_all_time,
    MAX(CASE WHEN medication_name = 'Gatifloxacin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS GAT_7_days,
    MAX(CASE WHEN medication_name = 'Gatifloxacin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS GAT_14_days,
    MAX(CASE WHEN medication_name = 'Gatifloxacin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS GAT_30_days,
    MAX(CASE WHEN medication_name = 'Gatifloxacin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS GAT_90_days,
    MAX(CASE WHEN medication_name = 'Gatifloxacin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS GAT_180_days,
    MAX(CASE WHEN medication_name = 'Gatifloxacin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS GAT_all_time,
    MAX(CASE WHEN medication_name = 'Flagyl' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS FLA_7_days,
    MAX(CASE WHEN medication_name = 'Flagyl' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS FLA_14_days,
    MAX(CASE WHEN medication_name = 'Flagyl' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS FLA_30_days,
    MAX(CASE WHEN medication_name = 'Flagyl' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS FLA_90_days,
    MAX(CASE WHEN medication_name = 'Flagyl' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS FLA_180_days,
    MAX(CASE WHEN medication_name = 'Flagyl' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS FLA_all_time,
    MAX(CASE WHEN medication_name = 'Macrodantin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MAC1_7_days,
    MAX(CASE WHEN medication_name = 'Macrodantin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MAC1_14_days,
    MAX(CASE WHEN medication_name = 'Macrodantin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MAC1_30_days,
    MAX(CASE WHEN medication_name = 'Macrodantin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MAC1_90_days,
    MAX(CASE WHEN medication_name = 'Macrodantin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MAC1_180_days,
    MAX(CASE WHEN medication_name = 'Macrodantin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MAC1_all_time,
    MAX(CASE WHEN medication_name = 'Amikacin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AMI_7_days,
    MAX(CASE WHEN medication_name = 'Amikacin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AMI_14_days,
    MAX(CASE WHEN medication_name = 'Amikacin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AMI_30_days,
    MAX(CASE WHEN medication_name = 'Amikacin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AMI_90_days,
    MAX(CASE WHEN medication_name = 'Amikacin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AMI_180_days,
    MAX(CASE WHEN medication_name = 'Amikacin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AMI_all_time,
    MAX(CASE WHEN medication_name = 'Trimethoprim' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS TRI_7_days,
    MAX(CASE WHEN medication_name = 'Trimethoprim' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS TRI_14_days,
    MAX(CASE WHEN medication_name = 'Trimethoprim' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS TRI_30_days,
    MAX(CASE WHEN medication_name = 'Trimethoprim' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS TRI_90_days,
    MAX(CASE WHEN medication_name = 'Trimethoprim' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS TRI_180_days,
    MAX(CASE WHEN medication_name = 'Trimethoprim' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS TRI_all_time,
    MAX(CASE WHEN medication_name = 'Tobramycin-Dexamethasone' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS TOB1_7_days,
    MAX(CASE WHEN medication_name = 'Tobramycin-Dexamethasone' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS TOB1_14_days,
    MAX(CASE WHEN medication_name = 'Tobramycin-Dexamethasone' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS TOB1_30_days,
    MAX(CASE WHEN medication_name = 'Tobramycin-Dexamethasone' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS TOB1_90_days,
    MAX(CASE WHEN medication_name = 'Tobramycin-Dexamethasone' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS TOB1_180_days,
    MAX(CASE WHEN medication_name = 'Tobramycin-Dexamethasone' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS TOB1_all_time,
    MAX(CASE WHEN medication_name = 'Dicloxacillin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS DIC_7_days,
    MAX(CASE WHEN medication_name = 'Dicloxacillin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS DIC_14_days,
    MAX(CASE WHEN medication_name = 'Dicloxacillin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS DIC_30_days,
    MAX(CASE WHEN medication_name = 'Dicloxacillin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS DIC_90_days,
    MAX(CASE WHEN medication_name = 'Dicloxacillin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS DIC_180_days,
    MAX(CASE WHEN medication_name = 'Dicloxacillin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS DIC_all_time,
    MAX(CASE WHEN medication_name = 'Moxifloxacin-Sod.Chloride(Iso)' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MOX1_7_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin-Sod.Chloride(Iso)' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MOX1_14_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin-Sod.Chloride(Iso)' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MOX1_30_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin-Sod.Chloride(Iso)' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MOX1_90_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin-Sod.Chloride(Iso)' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MOX1_180_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin-Sod.Chloride(Iso)' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MOX1_all_time,
    MAX(CASE WHEN medication_name = 'Hiprex' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS HIP_7_days,
    MAX(CASE WHEN medication_name = 'Hiprex' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS HIP_14_days,
    MAX(CASE WHEN medication_name = 'Hiprex' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS HIP_30_days,
    MAX(CASE WHEN medication_name = 'Hiprex' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS HIP_90_days,
    MAX(CASE WHEN medication_name = 'Hiprex' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS HIP_180_days,
    MAX(CASE WHEN medication_name = 'Hiprex' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS HIP_all_time,
    MAX(CASE WHEN medication_name = 'Ceftazidime' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF11_7_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF11_14_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF11_30_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF11_90_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF11_180_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF11_all_time,
    MAX(CASE WHEN medication_name = 'Zyvox' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS ZYV_7_days,
    MAX(CASE WHEN medication_name = 'Zyvox' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS ZYV_14_days,
    MAX(CASE WHEN medication_name = 'Zyvox' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS ZYV_30_days,
    MAX(CASE WHEN medication_name = 'Zyvox' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS ZYV_90_days,
    MAX(CASE WHEN medication_name = 'Zyvox' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS ZYV_180_days,
    MAX(CASE WHEN medication_name = 'Zyvox' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS ZYV_all_time,
    MAX(CASE WHEN medication_name = 'Methenamine Mandelate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MET3_7_days,
    MAX(CASE WHEN medication_name = 'Methenamine Mandelate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MET3_14_days,
    MAX(CASE WHEN medication_name = 'Methenamine Mandelate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MET3_30_days,
    MAX(CASE WHEN medication_name = 'Methenamine Mandelate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MET3_90_days,
    MAX(CASE WHEN medication_name = 'Methenamine Mandelate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MET3_180_days,
    MAX(CASE WHEN medication_name = 'Methenamine Mandelate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MET3_all_time,
    MAX(CASE WHEN medication_name = 'Rifabutin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS RIF2_7_days,
    MAX(CASE WHEN medication_name = 'Rifabutin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS RIF2_14_days,
    MAX(CASE WHEN medication_name = 'Rifabutin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS RIF2_30_days,
    MAX(CASE WHEN medication_name = 'Rifabutin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS RIF2_90_days,
    MAX(CASE WHEN medication_name = 'Rifabutin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS RIF2_180_days,
    MAX(CASE WHEN medication_name = 'Rifabutin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS RIF2_all_time,
    MAX(CASE WHEN medication_name = 'Tedizolid' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS TED_7_days,
    MAX(CASE WHEN medication_name = 'Tedizolid' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS TED_14_days,
    MAX(CASE WHEN medication_name = 'Tedizolid' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS TED_30_days,
    MAX(CASE WHEN medication_name = 'Tedizolid' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS TED_90_days,
    MAX(CASE WHEN medication_name = 'Tedizolid' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS TED_180_days,
    MAX(CASE WHEN medication_name = 'Tedizolid' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS TED_all_time
FROM
    binary_indicators
GROUP BY
    anon_id,
    pat_enc_csn_id_coded,
    order_proc_id_coded,
    order_time_jittered_utc;


