--The goal is to create the microbiology_cultures_prior_med table, which includes binary indicators for specific medication exposure within various time frames.


######## Steps ##########

####################################################################################################################
--1. Creating the microbiology_cultures_prior_antibiotics_extracted Table.  To extract microbiology cultures and their 
    -- associated medications, along with the time frames of medication exposure.
####################################################################################################################
CREATE OR REPLACE TABLE `som-nero-phi-jonc101.antimicrobial_stewardship.microbiology_cultures_prior_antibiotics_extracted` AS
WITH microbiology_cultures AS (
    SELECT DISTINCT
        anon_id,
        pat_enc_csn_id_coded,
        order_proc_id_coded,
        order_time_jittered_utc
    FROM 
        `som-nero-phi-jonc101.antimicrobial_stewardship.microbiology_cultures_cohort`
),

cleaned_medications AS (
    SELECT 
        mc.anon_id,
        mc.pat_enc_csn_id_coded,
        mc.order_proc_id_coded,
        mc.order_time_jittered_utc,
        mo.ordering_date_jittered_utc,
        INITCAP(TRIM(
            REGEXP_REPLACE(
                REGEXP_REPLACE(
                    LOWER(mm.name),
                    'penicillin[^a-z].*$', 'penicillin'
                ),
                '^[^a-z]*|\\s+\\S*[^a-z\\s]+.*$|\\.+$', ''
            )
        )) AS medication_name
    FROM 
        microbiology_cultures mc
    LEFT JOIN 
        `som-nero-phi-jonc101.shc_core_2023.order_med` mo
    ON 
        mc.anon_id = mo.anon_id
    LEFT JOIN 
        `som-nero-phi-jonc101.shc_core_2023.mapped_meds` mm
    ON 
        mo.med_description = mm.name
),

prior_antibiotics_exposure AS (
    SELECT 
        cm.anon_id,
        cm.pat_enc_csn_id_coded,
        cm.order_proc_id_coded,
        cm.order_time_jittered_utc,
        cm.medication_name,
        CASE 
            WHEN TIMESTAMP_DIFF(cm.order_time_jittered_utc, cm.ordering_date_jittered_utc, DAY) <= 7 THEN '7'
            WHEN TIMESTAMP_DIFF(cm.order_time_jittered_utc, cm.ordering_date_jittered_utc, DAY) <= 14 THEN '14'
            WHEN TIMESTAMP_DIFF(cm.order_time_jittered_utc, cm.ordering_date_jittered_utc, DAY) <= 30 THEN '30'
            WHEN TIMESTAMP_DIFF(cm.order_time_jittered_utc, cm.ordering_date_jittered_utc, DAY) <= 90 THEN '90'
            WHEN TIMESTAMP_DIFF(cm.order_time_jittered_utc, cm.ordering_date_jittered_utc, DAY) <= 180 THEN '180'
            ELSE 'ALL'
        END AS time_frame
    FROM 
        cleaned_medications cm
)

SELECT  * FROM prior_antibiotics_exposure;

#######################################################################################################################################
-- 2. Cleaning the Extracted Data. Filters the extracted data and keeps only the rows from the list of antibiotics provided. List of 
-- the antibiotics have been saved in temp_antibiotics table. There are 89 abx that we want to extract. 
#######################################################################################################################################
-- Create a cleaned table by filtering the rows from microbiology_cultures_prior_antibiotics_extracted that are in temp_antibiotics
CREATE OR REPLACE TABLE `som-nero-phi-jonc101.antimicrobial_stewardship.microbiology_cultures_prior_antibiotics_cleaned` AS
WITH antibiotic_list AS (
    SELECT antibiotic_name
    FROM `som-nero-phi-jonc101.antimicrobial_stewardship.temp_antibiotics`
),

-- Identify rows with valid antibiotics
valid_antibiotics AS (
    SELECT 
        pae.anon_id,
        pae.pat_enc_csn_id_coded,
        pae.order_proc_id_coded,
        pae.order_time_jittered_utc,
        pae.medication_name,
        pae.time_frame
    FROM 
        `som-nero-phi-jonc101.antimicrobial_stewardship.microbiology_cultures_prior_antibiotics_extracted` pae
    INNER JOIN 
        antibiotic_list al
    ON 
        pae.medication_name = al.antibiotic_name
)

-- Select only the valid antibiotics data
SELECT * FROM valid_antibiotics;


#######################################################################################################################################
-- 3. Generating the Final SQL Query using Python To create the final table microbiology_cultures_prior_med with binary indicators for 
   -- each antibiotic and each time frame.
#######################################################################################################################################

-- Create the pivoted table with binary indicators
CREATE OR REPLACE TABLE `som-nero-phi-jonc101.antimicrobial_stewardship.microbiology_cultures_prior_med` AS
WITH
-- Select all necessary fields and create binary indicators for each antibiotic and time frame
binary_indicators AS (
    SELECT
        anon_id,
        pat_enc_csn_id_coded,
        order_proc_id_coded,
        order_time_jittered_utc,
        medication_name,
        time_frame,
        CASE WHEN time_frame = '7' THEN 1 ELSE 0 END AS medication_7_days,
        CASE WHEN time_frame = '14' THEN 1 ELSE 0 END AS medication_14_days,
        CASE WHEN time_frame = '30' THEN 1 ELSE 0 END AS medication_30_days,
        CASE WHEN time_frame = '90' THEN 1 ELSE 0 END AS medication_90_days,
        CASE WHEN time_frame = '180' THEN 1 ELSE 0 END AS medication_180_days,
        CASE WHEN time_frame = 'ALL' THEN 1 ELSE 0 END AS medication_all_time
    FROM
        `som-nero-phi-jonc101.antimicrobial_stewardship.microbiology_cultures_prior_antibiotics_cleaned`
)
-- Pivot the table to create separate columns for each antibiotic and time frame
SELECT
    anon_id,
    pat_enc_csn_id_coded,
    order_proc_id_coded,
    order_time_jittered_utc,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS NIT_7_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS NIT_14_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS NIT_30_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS NIT_90_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS NIT_180_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS NIT_all_time,
    MAX(CASE WHEN medication_name = 'Cephalexin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEP_7_days,
    MAX(CASE WHEN medication_name = 'Cephalexin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEP_14_days,
    MAX(CASE WHEN medication_name = 'Cephalexin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEP_30_days,
    MAX(CASE WHEN medication_name = 'Cephalexin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEP_90_days,
    MAX(CASE WHEN medication_name = 'Cephalexin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEP_180_days,
    MAX(CASE WHEN medication_name = 'Cephalexin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEP_all_time,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam-Dextrs' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS PIP_7_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam-Dextrs' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS PIP_14_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam-Dextrs' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS PIP_30_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam-Dextrs' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS PIP_90_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam-Dextrs' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS PIP_180_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam-Dextrs' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS PIP_all_time,
    MAX(CASE WHEN medication_name = 'Sulfamethoxazole-Trimethoprim' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS SUL_7_days,
    MAX(CASE WHEN medication_name = 'Sulfamethoxazole-Trimethoprim' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS SUL_14_days,
    MAX(CASE WHEN medication_name = 'Sulfamethoxazole-Trimethoprim' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS SUL_30_days,
    MAX(CASE WHEN medication_name = 'Sulfamethoxazole-Trimethoprim' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS SUL_90_days,
    MAX(CASE WHEN medication_name = 'Sulfamethoxazole-Trimethoprim' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS SUL_180_days,
    MAX(CASE WHEN medication_name = 'Sulfamethoxazole-Trimethoprim' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS SUL_all_time,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin Hcl' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CIP_7_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin Hcl' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CIP_14_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin Hcl' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CIP_30_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin Hcl' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CIP_90_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin Hcl' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CIP_180_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin Hcl' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CIP_all_time,
    MAX(CASE WHEN medication_name = 'Cefazolin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF_7_days,
    MAX(CASE WHEN medication_name = 'Cefazolin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF_14_days,
    MAX(CASE WHEN medication_name = 'Cefazolin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF_30_days,
    MAX(CASE WHEN medication_name = 'Cefazolin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF_90_days,
    MAX(CASE WHEN medication_name = 'Cefazolin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF_180_days,
    MAX(CASE WHEN medication_name = 'Cefazolin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF_all_time,
    MAX(CASE WHEN medication_name = 'Cefazolin In Dextrose' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF1_7_days,
    MAX(CASE WHEN medication_name = 'Cefazolin In Dextrose' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF1_14_days,
    MAX(CASE WHEN medication_name = 'Cefazolin In Dextrose' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF1_30_days,
    MAX(CASE WHEN medication_name = 'Cefazolin In Dextrose' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF1_90_days,
    MAX(CASE WHEN medication_name = 'Cefazolin In Dextrose' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF1_180_days,
    MAX(CASE WHEN medication_name = 'Cefazolin In Dextrose' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF1_all_time,
    MAX(CASE WHEN medication_name = 'Levofloxacin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS LEV_7_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS LEV_14_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS LEV_30_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS LEV_90_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS LEV_180_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS LEV_all_time,
    MAX(CASE WHEN medication_name = 'Azithromycin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AZI_7_days,
    MAX(CASE WHEN medication_name = 'Azithromycin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AZI_14_days,
    MAX(CASE WHEN medication_name = 'Azithromycin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AZI_30_days,
    MAX(CASE WHEN medication_name = 'Azithromycin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AZI_90_days,
    MAX(CASE WHEN medication_name = 'Azithromycin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AZI_180_days,
    MAX(CASE WHEN medication_name = 'Azithromycin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AZI_all_time,
    MAX(CASE WHEN medication_name = 'Amoxicillin-Pot Clavulanate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AMO_7_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin-Pot Clavulanate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AMO_14_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin-Pot Clavulanate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AMO_30_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin-Pot Clavulanate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AMO_90_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin-Pot Clavulanate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AMO_180_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin-Pot Clavulanate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AMO_all_time,
    MAX(CASE WHEN medication_name = 'Metronidazole In Nacl' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MET_7_days,
    MAX(CASE WHEN medication_name = 'Metronidazole In Nacl' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MET_14_days,
    MAX(CASE WHEN medication_name = 'Metronidazole In Nacl' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MET_30_days,
    MAX(CASE WHEN medication_name = 'Metronidazole In Nacl' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MET_90_days,
    MAX(CASE WHEN medication_name = 'Metronidazole In Nacl' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MET_180_days,
    MAX(CASE WHEN medication_name = 'Metronidazole In Nacl' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MET_all_time,
    MAX(CASE WHEN medication_name = 'Ceftriaxone' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF2_7_days,
    MAX(CASE WHEN medication_name = 'Ceftriaxone' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF2_14_days,
    MAX(CASE WHEN medication_name = 'Ceftriaxone' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF2_30_days,
    MAX(CASE WHEN medication_name = 'Ceftriaxone' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF2_90_days,
    MAX(CASE WHEN medication_name = 'Ceftriaxone' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF2_180_days,
    MAX(CASE WHEN medication_name = 'Ceftriaxone' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF2_all_time,
    MAX(CASE WHEN medication_name = 'Vancomycin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS VAN_7_days,
    MAX(CASE WHEN medication_name = 'Vancomycin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS VAN_14_days,
    MAX(CASE WHEN medication_name = 'Vancomycin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS VAN_30_days,
    MAX(CASE WHEN medication_name = 'Vancomycin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS VAN_90_days,
    MAX(CASE WHEN medication_name = 'Vancomycin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS VAN_180_days,
    MAX(CASE WHEN medication_name = 'Vancomycin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS VAN_all_time,
    MAX(CASE WHEN medication_name = 'Levofloxacin In' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS LEV1_7_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin In' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS LEV1_14_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin In' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS LEV1_30_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin In' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS LEV1_90_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin In' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS LEV1_180_days,
    MAX(CASE WHEN medication_name = 'Levofloxacin In' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS LEV1_all_time,
    MAX(CASE WHEN medication_name = 'Vancomycin In Dextrose' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS VAN1_7_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In Dextrose' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS VAN1_14_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In Dextrose' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS VAN1_30_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In Dextrose' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS VAN1_90_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In Dextrose' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS VAN1_180_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In Dextrose' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS VAN1_all_time,
    MAX(CASE WHEN medication_name = 'Metronidazole' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MET1_7_days,
    MAX(CASE WHEN medication_name = 'Metronidazole' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MET1_14_days,
    MAX(CASE WHEN medication_name = 'Metronidazole' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MET1_30_days,
    MAX(CASE WHEN medication_name = 'Metronidazole' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MET1_90_days,
    MAX(CASE WHEN medication_name = 'Metronidazole' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MET1_180_days,
    MAX(CASE WHEN medication_name = 'Metronidazole' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MET1_all_time,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin In' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CIP1_7_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin In' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CIP1_14_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin In' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CIP1_30_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin In' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CIP1_90_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin In' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CIP1_180_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin In' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CIP1_all_time,
    MAX(CASE WHEN medication_name = 'Doxycycline Hyclate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS DOX_7_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Hyclate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS DOX_14_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Hyclate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS DOX_30_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Hyclate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS DOX_90_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Hyclate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS DOX_180_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Hyclate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS DOX_all_time,
    MAX(CASE WHEN medication_name = 'Cefpodoxime' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF3_7_days,
    MAX(CASE WHEN medication_name = 'Cefpodoxime' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF3_14_days,
    MAX(CASE WHEN medication_name = 'Cefpodoxime' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF3_30_days,
    MAX(CASE WHEN medication_name = 'Cefpodoxime' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF3_90_days,
    MAX(CASE WHEN medication_name = 'Cefpodoxime' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF3_180_days,
    MAX(CASE WHEN medication_name = 'Cefpodoxime' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF3_all_time,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS PIP1_7_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS PIP1_14_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS PIP1_30_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS PIP1_90_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS PIP1_180_days,
    MAX(CASE WHEN medication_name = 'Piperacillin-Tazobactam' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS PIP1_all_time,
    MAX(CASE WHEN medication_name = 'Rifaximin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS RIF_7_days,
    MAX(CASE WHEN medication_name = 'Rifaximin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS RIF_14_days,
    MAX(CASE WHEN medication_name = 'Rifaximin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS RIF_30_days,
    MAX(CASE WHEN medication_name = 'Rifaximin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS RIF_90_days,
    MAX(CASE WHEN medication_name = 'Rifaximin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS RIF_180_days,
    MAX(CASE WHEN medication_name = 'Rifaximin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS RIF_all_time,
    MAX(CASE WHEN medication_name = 'Vancomycin-Diluent Combo' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS VAN2_7_days,
    MAX(CASE WHEN medication_name = 'Vancomycin-Diluent Combo' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS VAN2_14_days,
    MAX(CASE WHEN medication_name = 'Vancomycin-Diluent Combo' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS VAN2_30_days,
    MAX(CASE WHEN medication_name = 'Vancomycin-Diluent Combo' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS VAN2_90_days,
    MAX(CASE WHEN medication_name = 'Vancomycin-Diluent Combo' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS VAN2_180_days,
    MAX(CASE WHEN medication_name = 'Vancomycin-Diluent Combo' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS VAN2_all_time,
    MAX(CASE WHEN medication_name = 'Clindamycin In' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CLI_7_days,
    MAX(CASE WHEN medication_name = 'Clindamycin In' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CLI_14_days,
    MAX(CASE WHEN medication_name = 'Clindamycin In' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CLI_30_days,
    MAX(CASE WHEN medication_name = 'Clindamycin In' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CLI_90_days,
    MAX(CASE WHEN medication_name = 'Clindamycin In' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CLI_180_days,
    MAX(CASE WHEN medication_name = 'Clindamycin In' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CLI_all_time,
    MAX(CASE WHEN medication_name = 'Amoxicillin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AMO1_7_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AMO1_14_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AMO1_30_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AMO1_90_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AMO1_180_days,
    MAX(CASE WHEN medication_name = 'Amoxicillin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AMO1_all_time,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin Macrocrystal' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS NIT1_7_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin Macrocrystal' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS NIT1_14_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin Macrocrystal' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS NIT1_30_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin Macrocrystal' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS NIT1_90_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin Macrocrystal' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS NIT1_180_days,
    MAX(CASE WHEN medication_name = 'Nitrofurantoin Macrocrystal' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS NIT1_all_time,
    MAX(CASE WHEN medication_name = 'Macrobid' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MAC_7_days,
    MAX(CASE WHEN medication_name = 'Macrobid' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MAC_14_days,
    MAX(CASE WHEN medication_name = 'Macrobid' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MAC_30_days,
    MAX(CASE WHEN medication_name = 'Macrobid' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MAC_90_days,
    MAX(CASE WHEN medication_name = 'Macrobid' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MAC_180_days,
    MAX(CASE WHEN medication_name = 'Macrobid' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MAC_all_time,
    MAX(CASE WHEN medication_name = 'Gentamicin-Sodium Citrate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS GEN_7_days,
    MAX(CASE WHEN medication_name = 'Gentamicin-Sodium Citrate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS GEN_14_days,
    MAX(CASE WHEN medication_name = 'Gentamicin-Sodium Citrate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS GEN_30_days,
    MAX(CASE WHEN medication_name = 'Gentamicin-Sodium Citrate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS GEN_90_days,
    MAX(CASE WHEN medication_name = 'Gentamicin-Sodium Citrate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS GEN_180_days,
    MAX(CASE WHEN medication_name = 'Gentamicin-Sodium Citrate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS GEN_all_time,
    MAX(CASE WHEN medication_name = 'Cefdinir' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF4_7_days,
    MAX(CASE WHEN medication_name = 'Cefdinir' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF4_14_days,
    MAX(CASE WHEN medication_name = 'Cefdinir' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF4_30_days,
    MAX(CASE WHEN medication_name = 'Cefdinir' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF4_90_days,
    MAX(CASE WHEN medication_name = 'Cefdinir' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF4_180_days,
    MAX(CASE WHEN medication_name = 'Cefdinir' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF4_all_time,
    MAX(CASE WHEN medication_name = 'Clindamycin Phosphate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CLI1_7_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Phosphate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CLI1_14_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Phosphate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CLI1_30_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Phosphate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CLI1_90_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Phosphate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CLI1_180_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Phosphate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CLI1_all_time,
    MAX(CASE WHEN medication_name = 'Cefoxitin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF5_7_days,
    MAX(CASE WHEN medication_name = 'Cefoxitin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF5_14_days,
    MAX(CASE WHEN medication_name = 'Cefoxitin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF5_30_days,
    MAX(CASE WHEN medication_name = 'Cefoxitin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF5_90_days,
    MAX(CASE WHEN medication_name = 'Cefoxitin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF5_180_days,
    MAX(CASE WHEN medication_name = 'Cefoxitin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF5_all_time,
    MAX(CASE WHEN medication_name = 'Cipro' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CIP2_7_days,
    MAX(CASE WHEN medication_name = 'Cipro' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CIP2_14_days,
    MAX(CASE WHEN medication_name = 'Cipro' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CIP2_30_days,
    MAX(CASE WHEN medication_name = 'Cipro' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CIP2_90_days,
    MAX(CASE WHEN medication_name = 'Cipro' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CIP2_180_days,
    MAX(CASE WHEN medication_name = 'Cipro' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CIP2_all_time,
    MAX(CASE WHEN medication_name = 'Clindamycin Hcl' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CLI2_7_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Hcl' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CLI2_14_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Hcl' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CLI2_30_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Hcl' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CLI2_90_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Hcl' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CLI2_180_days,
    MAX(CASE WHEN medication_name = 'Clindamycin Hcl' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CLI2_all_time,
    MAX(CASE WHEN medication_name = 'Vancomycin In' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS VAN3_7_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS VAN3_14_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS VAN3_30_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS VAN3_90_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS VAN3_180_days,
    MAX(CASE WHEN medication_name = 'Vancomycin In' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS VAN3_all_time,
    MAX(CASE WHEN medication_name = 'Moxifloxacin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MOX_7_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MOX_14_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MOX_30_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MOX_90_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MOX_180_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MOX_all_time,
    MAX(CASE WHEN medication_name = 'Gentamicin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS GEN1_7_days,
    MAX(CASE WHEN medication_name = 'Gentamicin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS GEN1_14_days,
    MAX(CASE WHEN medication_name = 'Gentamicin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS GEN1_30_days,
    MAX(CASE WHEN medication_name = 'Gentamicin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS GEN1_90_days,
    MAX(CASE WHEN medication_name = 'Gentamicin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS GEN1_180_days,
    MAX(CASE WHEN medication_name = 'Gentamicin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS GEN1_all_time,
    MAX(CASE WHEN medication_name = 'Linezolid' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS LIN_7_days,
    MAX(CASE WHEN medication_name = 'Linezolid' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS LIN_14_days,
    MAX(CASE WHEN medication_name = 'Linezolid' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS LIN_30_days,
    MAX(CASE WHEN medication_name = 'Linezolid' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS LIN_90_days,
    MAX(CASE WHEN medication_name = 'Linezolid' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS LIN_180_days,
    MAX(CASE WHEN medication_name = 'Linezolid' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS LIN_all_time,
    MAX(CASE WHEN medication_name = 'Zithromax' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS ZIT_7_days,
    MAX(CASE WHEN medication_name = 'Zithromax' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS ZIT_14_days,
    MAX(CASE WHEN medication_name = 'Zithromax' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS ZIT_30_days,
    MAX(CASE WHEN medication_name = 'Zithromax' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS ZIT_90_days,
    MAX(CASE WHEN medication_name = 'Zithromax' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS ZIT_180_days,
    MAX(CASE WHEN medication_name = 'Zithromax' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS ZIT_all_time,
    MAX(CASE WHEN medication_name = 'Erythromycin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS ERY_7_days,
    MAX(CASE WHEN medication_name = 'Erythromycin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS ERY_14_days,
    MAX(CASE WHEN medication_name = 'Erythromycin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS ERY_30_days,
    MAX(CASE WHEN medication_name = 'Erythromycin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS ERY_90_days,
    MAX(CASE WHEN medication_name = 'Erythromycin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS ERY_180_days,
    MAX(CASE WHEN medication_name = 'Erythromycin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS ERY_all_time,
    MAX(CASE WHEN medication_name = 'Bactrim Ds' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS BAC_7_days,
    MAX(CASE WHEN medication_name = 'Bactrim Ds' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS BAC_14_days,
    MAX(CASE WHEN medication_name = 'Bactrim Ds' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS BAC_30_days,
    MAX(CASE WHEN medication_name = 'Bactrim Ds' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS BAC_90_days,
    MAX(CASE WHEN medication_name = 'Bactrim Ds' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS BAC_180_days,
    MAX(CASE WHEN medication_name = 'Bactrim Ds' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS BAC_all_time,
    MAX(CASE WHEN medication_name = 'Fosfomycin Tromethamine' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS FOS_7_days,
    MAX(CASE WHEN medication_name = 'Fosfomycin Tromethamine' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS FOS_14_days,
    MAX(CASE WHEN medication_name = 'Fosfomycin Tromethamine' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS FOS_30_days,
    MAX(CASE WHEN medication_name = 'Fosfomycin Tromethamine' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS FOS_90_days,
    MAX(CASE WHEN medication_name = 'Fosfomycin Tromethamine' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS FOS_180_days,
    MAX(CASE WHEN medication_name = 'Fosfomycin Tromethamine' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS FOS_all_time,
    MAX(CASE WHEN medication_name = 'Cefepime' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF6_7_days,
    MAX(CASE WHEN medication_name = 'Cefepime' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF6_14_days,
    MAX(CASE WHEN medication_name = 'Cefepime' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF6_30_days,
    MAX(CASE WHEN medication_name = 'Cefepime' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF6_90_days,
    MAX(CASE WHEN medication_name = 'Cefepime' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF6_180_days,
    MAX(CASE WHEN medication_name = 'Cefepime' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF6_all_time,
    MAX(CASE WHEN medication_name = 'Keflex' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS KEF_7_days,
    MAX(CASE WHEN medication_name = 'Keflex' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS KEF_14_days,
    MAX(CASE WHEN medication_name = 'Keflex' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS KEF_30_days,
    MAX(CASE WHEN medication_name = 'Keflex' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS KEF_90_days,
    MAX(CASE WHEN medication_name = 'Keflex' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS KEF_180_days,
    MAX(CASE WHEN medication_name = 'Keflex' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS KEF_all_time,
    MAX(CASE WHEN medication_name = 'Colistin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS COL_7_days,
    MAX(CASE WHEN medication_name = 'Colistin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS COL_14_days,
    MAX(CASE WHEN medication_name = 'Colistin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS COL_30_days,
    MAX(CASE WHEN medication_name = 'Colistin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS COL_90_days,
    MAX(CASE WHEN medication_name = 'Colistin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS COL_180_days,
    MAX(CASE WHEN medication_name = 'Colistin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS COL_all_time,
    MAX(CASE WHEN medication_name = 'Doxycycline Monohydrate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS DOX1_7_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Monohydrate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS DOX1_14_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Monohydrate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS DOX1_30_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Monohydrate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS DOX1_90_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Monohydrate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS DOX1_180_days,
    MAX(CASE WHEN medication_name = 'Doxycycline Monohydrate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS DOX1_all_time,
    MAX(CASE WHEN medication_name = 'Levaquin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS LEV2_7_days,
    MAX(CASE WHEN medication_name = 'Levaquin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS LEV2_14_days,
    MAX(CASE WHEN medication_name = 'Levaquin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS LEV2_30_days,
    MAX(CASE WHEN medication_name = 'Levaquin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS LEV2_90_days,
    MAX(CASE WHEN medication_name = 'Levaquin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS LEV2_180_days,
    MAX(CASE WHEN medication_name = 'Levaquin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS LEV2_all_time,
    MAX(CASE WHEN medication_name = 'Clarithromycin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CLA_7_days,
    MAX(CASE WHEN medication_name = 'Clarithromycin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CLA_14_days,
    MAX(CASE WHEN medication_name = 'Clarithromycin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CLA_30_days,
    MAX(CASE WHEN medication_name = 'Clarithromycin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CLA_90_days,
    MAX(CASE WHEN medication_name = 'Clarithromycin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CLA_180_days,
    MAX(CASE WHEN medication_name = 'Clarithromycin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CLA_all_time,
    MAX(CASE WHEN medication_name = 'Rifampin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS RIF1_7_days,
    MAX(CASE WHEN medication_name = 'Rifampin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS RIF1_14_days,
    MAX(CASE WHEN medication_name = 'Rifampin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS RIF1_30_days,
    MAX(CASE WHEN medication_name = 'Rifampin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS RIF1_90_days,
    MAX(CASE WHEN medication_name = 'Rifampin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS RIF1_180_days,
    MAX(CASE WHEN medication_name = 'Rifampin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS RIF1_all_time,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CIP3_7_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CIP3_14_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CIP3_30_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CIP3_90_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CIP3_180_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CIP3_all_time,
    MAX(CASE WHEN medication_name = 'Cefuroxime Axetil' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF7_7_days,
    MAX(CASE WHEN medication_name = 'Cefuroxime Axetil' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF7_14_days,
    MAX(CASE WHEN medication_name = 'Cefuroxime Axetil' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF7_30_days,
    MAX(CASE WHEN medication_name = 'Cefuroxime Axetil' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF7_90_days,
    MAX(CASE WHEN medication_name = 'Cefuroxime Axetil' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF7_180_days,
    MAX(CASE WHEN medication_name = 'Cefuroxime Axetil' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF7_all_time,
    MAX(CASE WHEN medication_name = 'Augmentin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AUG_7_days,
    MAX(CASE WHEN medication_name = 'Augmentin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AUG_14_days,
    MAX(CASE WHEN medication_name = 'Augmentin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AUG_30_days,
    MAX(CASE WHEN medication_name = 'Augmentin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AUG_90_days,
    MAX(CASE WHEN medication_name = 'Augmentin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AUG_180_days,
    MAX(CASE WHEN medication_name = 'Augmentin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AUG_all_time,
    MAX(CASE WHEN medication_name = 'Cefadroxil' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF8_7_days,
    MAX(CASE WHEN medication_name = 'Cefadroxil' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF8_14_days,
    MAX(CASE WHEN medication_name = 'Cefadroxil' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF8_30_days,
    MAX(CASE WHEN medication_name = 'Cefadroxil' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF8_90_days,
    MAX(CASE WHEN medication_name = 'Cefadroxil' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF8_180_days,
    MAX(CASE WHEN medication_name = 'Cefadroxil' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF8_all_time,
    MAX(CASE WHEN medication_name = 'Methenamine Hippurate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MET2_7_days,
    MAX(CASE WHEN medication_name = 'Methenamine Hippurate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MET2_14_days,
    MAX(CASE WHEN medication_name = 'Methenamine Hippurate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MET2_30_days,
    MAX(CASE WHEN medication_name = 'Methenamine Hippurate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MET2_90_days,
    MAX(CASE WHEN medication_name = 'Methenamine Hippurate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MET2_180_days,
    MAX(CASE WHEN medication_name = 'Methenamine Hippurate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MET2_all_time,
    MAX(CASE WHEN medication_name = 'Ertapenem' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS ERT_7_days,
    MAX(CASE WHEN medication_name = 'Ertapenem' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS ERT_14_days,
    MAX(CASE WHEN medication_name = 'Ertapenem' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS ERT_30_days,
    MAX(CASE WHEN medication_name = 'Ertapenem' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS ERT_90_days,
    MAX(CASE WHEN medication_name = 'Ertapenem' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS ERT_180_days,
    MAX(CASE WHEN medication_name = 'Ertapenem' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS ERT_all_time,
    MAX(CASE WHEN medication_name = 'Linezolid In Dextrose' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS LIN1_7_days,
    MAX(CASE WHEN medication_name = 'Linezolid In Dextrose' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS LIN1_14_days,
    MAX(CASE WHEN medication_name = 'Linezolid In Dextrose' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS LIN1_30_days,
    MAX(CASE WHEN medication_name = 'Linezolid In Dextrose' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS LIN1_90_days,
    MAX(CASE WHEN medication_name = 'Linezolid In Dextrose' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS LIN1_180_days,
    MAX(CASE WHEN medication_name = 'Linezolid In Dextrose' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS LIN1_all_time,
    MAX(CASE WHEN medication_name = 'Ofloxacin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS OFL_7_days,
    MAX(CASE WHEN medication_name = 'Ofloxacin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS OFL_14_days,
    MAX(CASE WHEN medication_name = 'Ofloxacin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS OFL_30_days,
    MAX(CASE WHEN medication_name = 'Ofloxacin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS OFL_90_days,
    MAX(CASE WHEN medication_name = 'Ofloxacin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS OFL_180_days,
    MAX(CASE WHEN medication_name = 'Ofloxacin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS OFL_all_time,
    MAX(CASE WHEN medication_name = 'Penicillin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS PEN_7_days,
    MAX(CASE WHEN medication_name = 'Penicillin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS PEN_14_days,
    MAX(CASE WHEN medication_name = 'Penicillin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS PEN_30_days,
    MAX(CASE WHEN medication_name = 'Penicillin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS PEN_90_days,
    MAX(CASE WHEN medication_name = 'Penicillin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS PEN_180_days,
    MAX(CASE WHEN medication_name = 'Penicillin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS PEN_all_time,
    MAX(CASE WHEN medication_name = 'Silver Sulfadiazine' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS SIL_7_days,
    MAX(CASE WHEN medication_name = 'Silver Sulfadiazine' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS SIL_14_days,
    MAX(CASE WHEN medication_name = 'Silver Sulfadiazine' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS SIL_30_days,
    MAX(CASE WHEN medication_name = 'Silver Sulfadiazine' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS SIL_90_days,
    MAX(CASE WHEN medication_name = 'Silver Sulfadiazine' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS SIL_180_days,
    MAX(CASE WHEN medication_name = 'Silver Sulfadiazine' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS SIL_all_time,
    MAX(CASE WHEN medication_name = 'Dapsone' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS DAP_7_days,
    MAX(CASE WHEN medication_name = 'Dapsone' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS DAP_14_days,
    MAX(CASE WHEN medication_name = 'Dapsone' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS DAP_30_days,
    MAX(CASE WHEN medication_name = 'Dapsone' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS DAP_90_days,
    MAX(CASE WHEN medication_name = 'Dapsone' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS DAP_180_days,
    MAX(CASE WHEN medication_name = 'Dapsone' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS DAP_all_time,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin-Dexamethasone' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CIP4_7_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin-Dexamethasone' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CIP4_14_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin-Dexamethasone' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CIP4_30_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin-Dexamethasone' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CIP4_90_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin-Dexamethasone' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CIP4_180_days,
    MAX(CASE WHEN medication_name = 'Ciprofloxacin-Dexamethasone' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CIP4_all_time,
    MAX(CASE WHEN medication_name = 'Ampicillin Sodium' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AMP_7_days,
    MAX(CASE WHEN medication_name = 'Ampicillin Sodium' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AMP_14_days,
    MAX(CASE WHEN medication_name = 'Ampicillin Sodium' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AMP_30_days,
    MAX(CASE WHEN medication_name = 'Ampicillin Sodium' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AMP_90_days,
    MAX(CASE WHEN medication_name = 'Ampicillin Sodium' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AMP_180_days,
    MAX(CASE WHEN medication_name = 'Ampicillin Sodium' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AMP_all_time,
    MAX(CASE WHEN medication_name = 'Isoniazid' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS ISO_7_days,
    MAX(CASE WHEN medication_name = 'Isoniazid' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS ISO_14_days,
    MAX(CASE WHEN medication_name = 'Isoniazid' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS ISO_30_days,
    MAX(CASE WHEN medication_name = 'Isoniazid' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS ISO_90_days,
    MAX(CASE WHEN medication_name = 'Isoniazid' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS ISO_180_days,
    MAX(CASE WHEN medication_name = 'Isoniazid' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS ISO_all_time,
    MAX(CASE WHEN medication_name = 'Bactrim' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS BAC1_7_days,
    MAX(CASE WHEN medication_name = 'Bactrim' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS BAC1_14_days,
    MAX(CASE WHEN medication_name = 'Bactrim' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS BAC1_30_days,
    MAX(CASE WHEN medication_name = 'Bactrim' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS BAC1_90_days,
    MAX(CASE WHEN medication_name = 'Bactrim' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS BAC1_180_days,
    MAX(CASE WHEN medication_name = 'Bactrim' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS BAC1_all_time,
    MAX(CASE WHEN medication_name = 'Fidaxomicin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS FID_7_days,
    MAX(CASE WHEN medication_name = 'Fidaxomicin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS FID_14_days,
    MAX(CASE WHEN medication_name = 'Fidaxomicin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS FID_30_days,
    MAX(CASE WHEN medication_name = 'Fidaxomicin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS FID_90_days,
    MAX(CASE WHEN medication_name = 'Fidaxomicin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS FID_180_days,
    MAX(CASE WHEN medication_name = 'Fidaxomicin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS FID_all_time,
    MAX(CASE WHEN medication_name = 'Aztreonam In' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AZT_7_days,
    MAX(CASE WHEN medication_name = 'Aztreonam In' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AZT_14_days,
    MAX(CASE WHEN medication_name = 'Aztreonam In' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AZT_30_days,
    MAX(CASE WHEN medication_name = 'Aztreonam In' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AZT_90_days,
    MAX(CASE WHEN medication_name = 'Aztreonam In' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AZT_180_days,
    MAX(CASE WHEN medication_name = 'Aztreonam In' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AZT_all_time,
    MAX(CASE WHEN medication_name = 'Ethambutol' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS ETH_7_days,
    MAX(CASE WHEN medication_name = 'Ethambutol' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS ETH_14_days,
    MAX(CASE WHEN medication_name = 'Ethambutol' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS ETH_30_days,
    MAX(CASE WHEN medication_name = 'Ethambutol' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS ETH_90_days,
    MAX(CASE WHEN medication_name = 'Ethambutol' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS ETH_180_days,
    MAX(CASE WHEN medication_name = 'Ethambutol' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS ETH_all_time,
    MAX(CASE WHEN medication_name = 'Tobramycin Sulfate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS TOB_7_days,
    MAX(CASE WHEN medication_name = 'Tobramycin Sulfate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS TOB_14_days,
    MAX(CASE WHEN medication_name = 'Tobramycin Sulfate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS TOB_30_days,
    MAX(CASE WHEN medication_name = 'Tobramycin Sulfate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS TOB_90_days,
    MAX(CASE WHEN medication_name = 'Tobramycin Sulfate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS TOB_180_days,
    MAX(CASE WHEN medication_name = 'Tobramycin Sulfate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS TOB_all_time,
    MAX(CASE WHEN medication_name = 'Cefepime In' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF9_7_days,
    MAX(CASE WHEN medication_name = 'Cefepime In' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF9_14_days,
    MAX(CASE WHEN medication_name = 'Cefepime In' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF9_30_days,
    MAX(CASE WHEN medication_name = 'Cefepime In' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF9_90_days,
    MAX(CASE WHEN medication_name = 'Cefepime In' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF9_180_days,
    MAX(CASE WHEN medication_name = 'Cefepime In' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF9_all_time,
    MAX(CASE WHEN medication_name = 'Ampicillin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AMP1_7_days,
    MAX(CASE WHEN medication_name = 'Ampicillin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AMP1_14_days,
    MAX(CASE WHEN medication_name = 'Ampicillin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AMP1_30_days,
    MAX(CASE WHEN medication_name = 'Ampicillin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AMP1_90_days,
    MAX(CASE WHEN medication_name = 'Ampicillin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AMP1_180_days,
    MAX(CASE WHEN medication_name = 'Ampicillin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AMP1_all_time,
    MAX(CASE WHEN medication_name = 'Minocycline' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MIN_7_days,
    MAX(CASE WHEN medication_name = 'Minocycline' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MIN_14_days,
    MAX(CASE WHEN medication_name = 'Minocycline' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MIN_30_days,
    MAX(CASE WHEN medication_name = 'Minocycline' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MIN_90_days,
    MAX(CASE WHEN medication_name = 'Minocycline' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MIN_180_days,
    MAX(CASE WHEN medication_name = 'Minocycline' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MIN_all_time,
    MAX(CASE WHEN medication_name = 'Ceftazidime-Dextrose' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF10_7_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime-Dextrose' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF10_14_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime-Dextrose' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF10_30_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime-Dextrose' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF10_90_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime-Dextrose' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF10_180_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime-Dextrose' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF10_all_time,
    MAX(CASE WHEN medication_name = 'Aztreonam' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AZT1_7_days,
    MAX(CASE WHEN medication_name = 'Aztreonam' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AZT1_14_days,
    MAX(CASE WHEN medication_name = 'Aztreonam' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AZT1_30_days,
    MAX(CASE WHEN medication_name = 'Aztreonam' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AZT1_90_days,
    MAX(CASE WHEN medication_name = 'Aztreonam' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AZT1_180_days,
    MAX(CASE WHEN medication_name = 'Aztreonam' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AZT1_all_time,
    MAX(CASE WHEN medication_name = 'Xifaxan' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS XIF_7_days,
    MAX(CASE WHEN medication_name = 'Xifaxan' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS XIF_14_days,
    MAX(CASE WHEN medication_name = 'Xifaxan' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS XIF_30_days,
    MAX(CASE WHEN medication_name = 'Xifaxan' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS XIF_90_days,
    MAX(CASE WHEN medication_name = 'Xifaxan' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS XIF_180_days,
    MAX(CASE WHEN medication_name = 'Xifaxan' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS XIF_all_time,
    MAX(CASE WHEN medication_name = 'Erythromycin Ethylsuccinate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS ERY1_7_days,
    MAX(CASE WHEN medication_name = 'Erythromycin Ethylsuccinate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS ERY1_14_days,
    MAX(CASE WHEN medication_name = 'Erythromycin Ethylsuccinate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS ERY1_30_days,
    MAX(CASE WHEN medication_name = 'Erythromycin Ethylsuccinate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS ERY1_90_days,
    MAX(CASE WHEN medication_name = 'Erythromycin Ethylsuccinate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS ERY1_180_days,
    MAX(CASE WHEN medication_name = 'Erythromycin Ethylsuccinate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS ERY1_all_time,
    MAX(CASE WHEN medication_name = 'Gentamicin In Nacl' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS GEN2_7_days,
    MAX(CASE WHEN medication_name = 'Gentamicin In Nacl' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS GEN2_14_days,
    MAX(CASE WHEN medication_name = 'Gentamicin In Nacl' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS GEN2_30_days,
    MAX(CASE WHEN medication_name = 'Gentamicin In Nacl' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS GEN2_90_days,
    MAX(CASE WHEN medication_name = 'Gentamicin In Nacl' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS GEN2_180_days,
    MAX(CASE WHEN medication_name = 'Gentamicin In Nacl' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS GEN2_all_time,
    MAX(CASE WHEN medication_name = 'Meropenem' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MER_7_days,
    MAX(CASE WHEN medication_name = 'Meropenem' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MER_14_days,
    MAX(CASE WHEN medication_name = 'Meropenem' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MER_30_days,
    MAX(CASE WHEN medication_name = 'Meropenem' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MER_90_days,
    MAX(CASE WHEN medication_name = 'Meropenem' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MER_180_days,
    MAX(CASE WHEN medication_name = 'Meropenem' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MER_all_time,
    MAX(CASE WHEN medication_name = 'Gatifloxacin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS GAT_7_days,
    MAX(CASE WHEN medication_name = 'Gatifloxacin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS GAT_14_days,
    MAX(CASE WHEN medication_name = 'Gatifloxacin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS GAT_30_days,
    MAX(CASE WHEN medication_name = 'Gatifloxacin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS GAT_90_days,
    MAX(CASE WHEN medication_name = 'Gatifloxacin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS GAT_180_days,
    MAX(CASE WHEN medication_name = 'Gatifloxacin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS GAT_all_time,
    MAX(CASE WHEN medication_name = 'Flagyl' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS FLA_7_days,
    MAX(CASE WHEN medication_name = 'Flagyl' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS FLA_14_days,
    MAX(CASE WHEN medication_name = 'Flagyl' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS FLA_30_days,
    MAX(CASE WHEN medication_name = 'Flagyl' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS FLA_90_days,
    MAX(CASE WHEN medication_name = 'Flagyl' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS FLA_180_days,
    MAX(CASE WHEN medication_name = 'Flagyl' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS FLA_all_time,
    MAX(CASE WHEN medication_name = 'Macrodantin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MAC1_7_days,
    MAX(CASE WHEN medication_name = 'Macrodantin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MAC1_14_days,
    MAX(CASE WHEN medication_name = 'Macrodantin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MAC1_30_days,
    MAX(CASE WHEN medication_name = 'Macrodantin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MAC1_90_days,
    MAX(CASE WHEN medication_name = 'Macrodantin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MAC1_180_days,
    MAX(CASE WHEN medication_name = 'Macrodantin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MAC1_all_time,
    MAX(CASE WHEN medication_name = 'Amikacin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS AMI_7_days,
    MAX(CASE WHEN medication_name = 'Amikacin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS AMI_14_days,
    MAX(CASE WHEN medication_name = 'Amikacin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS AMI_30_days,
    MAX(CASE WHEN medication_name = 'Amikacin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS AMI_90_days,
    MAX(CASE WHEN medication_name = 'Amikacin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS AMI_180_days,
    MAX(CASE WHEN medication_name = 'Amikacin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS AMI_all_time,
    MAX(CASE WHEN medication_name = 'Trimethoprim' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS TRI_7_days,
    MAX(CASE WHEN medication_name = 'Trimethoprim' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS TRI_14_days,
    MAX(CASE WHEN medication_name = 'Trimethoprim' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS TRI_30_days,
    MAX(CASE WHEN medication_name = 'Trimethoprim' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS TRI_90_days,
    MAX(CASE WHEN medication_name = 'Trimethoprim' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS TRI_180_days,
    MAX(CASE WHEN medication_name = 'Trimethoprim' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS TRI_all_time,
    MAX(CASE WHEN medication_name = 'Tobramycin-Dexamethasone' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS TOB1_7_days,
    MAX(CASE WHEN medication_name = 'Tobramycin-Dexamethasone' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS TOB1_14_days,
    MAX(CASE WHEN medication_name = 'Tobramycin-Dexamethasone' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS TOB1_30_days,
    MAX(CASE WHEN medication_name = 'Tobramycin-Dexamethasone' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS TOB1_90_days,
    MAX(CASE WHEN medication_name = 'Tobramycin-Dexamethasone' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS TOB1_180_days,
    MAX(CASE WHEN medication_name = 'Tobramycin-Dexamethasone' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS TOB1_all_time,
    MAX(CASE WHEN medication_name = 'Dicloxacillin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS DIC_7_days,
    MAX(CASE WHEN medication_name = 'Dicloxacillin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS DIC_14_days,
    MAX(CASE WHEN medication_name = 'Dicloxacillin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS DIC_30_days,
    MAX(CASE WHEN medication_name = 'Dicloxacillin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS DIC_90_days,
    MAX(CASE WHEN medication_name = 'Dicloxacillin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS DIC_180_days,
    MAX(CASE WHEN medication_name = 'Dicloxacillin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS DIC_all_time,
    MAX(CASE WHEN medication_name = 'Moxifloxacin-Sod.Chloride(Iso)' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MOX1_7_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin-Sod.Chloride(Iso)' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MOX1_14_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin-Sod.Chloride(Iso)' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MOX1_30_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin-Sod.Chloride(Iso)' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MOX1_90_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin-Sod.Chloride(Iso)' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MOX1_180_days,
    MAX(CASE WHEN medication_name = 'Moxifloxacin-Sod.Chloride(Iso)' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MOX1_all_time,
    MAX(CASE WHEN medication_name = 'Hiprex' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS HIP_7_days,
    MAX(CASE WHEN medication_name = 'Hiprex' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS HIP_14_days,
    MAX(CASE WHEN medication_name = 'Hiprex' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS HIP_30_days,
    MAX(CASE WHEN medication_name = 'Hiprex' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS HIP_90_days,
    MAX(CASE WHEN medication_name = 'Hiprex' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS HIP_180_days,
    MAX(CASE WHEN medication_name = 'Hiprex' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS HIP_all_time,
    MAX(CASE WHEN medication_name = 'Ceftazidime' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS CEF11_7_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS CEF11_14_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS CEF11_30_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS CEF11_90_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS CEF11_180_days,
    MAX(CASE WHEN medication_name = 'Ceftazidime' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS CEF11_all_time,
    MAX(CASE WHEN medication_name = 'Zyvox' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS ZYV_7_days,
    MAX(CASE WHEN medication_name = 'Zyvox' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS ZYV_14_days,
    MAX(CASE WHEN medication_name = 'Zyvox' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS ZYV_30_days,
    MAX(CASE WHEN medication_name = 'Zyvox' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS ZYV_90_days,
    MAX(CASE WHEN medication_name = 'Zyvox' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS ZYV_180_days,
    MAX(CASE WHEN medication_name = 'Zyvox' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS ZYV_all_time,
    MAX(CASE WHEN medication_name = 'Methenamine Mandelate' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS MET3_7_days,
    MAX(CASE WHEN medication_name = 'Methenamine Mandelate' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS MET3_14_days,
    MAX(CASE WHEN medication_name = 'Methenamine Mandelate' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS MET3_30_days,
    MAX(CASE WHEN medication_name = 'Methenamine Mandelate' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS MET3_90_days,
    MAX(CASE WHEN medication_name = 'Methenamine Mandelate' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS MET3_180_days,
    MAX(CASE WHEN medication_name = 'Methenamine Mandelate' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS MET3_all_time,
    MAX(CASE WHEN medication_name = 'Rifabutin' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS RIF2_7_days,
    MAX(CASE WHEN medication_name = 'Rifabutin' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS RIF2_14_days,
    MAX(CASE WHEN medication_name = 'Rifabutin' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS RIF2_30_days,
    MAX(CASE WHEN medication_name = 'Rifabutin' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS RIF2_90_days,
    MAX(CASE WHEN medication_name = 'Rifabutin' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS RIF2_180_days,
    MAX(CASE WHEN medication_name = 'Rifabutin' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS RIF2_all_time,
    MAX(CASE WHEN medication_name = 'Tedizolid' AND medication_7_days = 1 THEN 1 ELSE 0 END) AS TED_7_days,
    MAX(CASE WHEN medication_name = 'Tedizolid' AND medication_14_days = 1 THEN 1 ELSE 0 END) AS TED_14_days,
    MAX(CASE WHEN medication_name = 'Tedizolid' AND medication_30_days = 1 THEN 1 ELSE 0 END) AS TED_30_days,
    MAX(CASE WHEN medication_name = 'Tedizolid' AND medication_90_days = 1 THEN 1 ELSE 0 END) AS TED_90_days,
    MAX(CASE WHEN medication_name = 'Tedizolid' AND medication_180_days = 1 THEN 1 ELSE 0 END) AS TED_180_days,
    MAX(CASE WHEN medication_name = 'Tedizolid' AND medication_all_time = 1 THEN 1 ELSE 0 END) AS TED_all_time
FROM
    binary_indicators
GROUP BY
    anon_id,
    pat_enc_csn_id_coded,
    order_proc_id_coded,
    order_time_jittered_utc;

#######################################################################################################################################
-- 4. Identify rows from microbiology_cultures_cohort that are not in microbiology_cultures_prior_med
#######################################################################################################################################

CREATE OR REPLACE TABLE `som-nero-phi-jonc101.antimicrobial_stewardship.temp_missing_rows` AS
WITH missing_rows AS (
    SELECT DISTINCT
        mcc.anon_id,
        mcc.pat_enc_csn_id_coded,
        mcc.order_proc_id_coded,
        mcc.order_time_jittered_utc
    FROM 
        `som-nero-phi-jonc101.antimicrobial_stewardship.microbiology_cultures_cohort` mcc
    LEFT JOIN 
        `som-nero-phi-jonc101.antimicrobial_stewardship.microbiology_cultures_prior_med` mcpm
    ON 
        mcc.anon_id = mcpm.anon_id 
        AND mcc.pat_enc_csn_id_coded = mcpm.pat_enc_csn_id_coded 
        AND mcc.order_proc_id_coded = mcpm.order_proc_id_coded
        AND mcc.order_time_jittered_utc = mcpm.order_time_jittered_utc
    WHERE 
        mcpm.anon_id IS NULL
)

SELECT
    anon_id,
    pat_enc_csn_id_coded,
    order_proc_id_coded,
    order_time_jittered_utc,
        0 AS NIT_7_days,
        0 AS NIT_14_days,
        0 AS NIT_30_days,
        0 AS NIT_90_days,
        0 AS NIT_180_days,
        0 AS NIT_all_time,
        0 AS CEP_7_days,
        0 AS CEP_14_days,
        0 AS CEP_30_days,
        0 AS CEP_90_days,
        0 AS CEP_180_days,
        0 AS CEP_all_time,
        0 AS PIP_7_days,
        0 AS PIP_14_days,
        0 AS PIP_30_days,
        0 AS PIP_90_days,
        0 AS PIP_180_days,
        0 AS PIP_all_time,
        0 AS SUL_7_days,
        0 AS SUL_14_days,
        0 AS SUL_30_days,
        0 AS SUL_90_days,
        0 AS SUL_180_days,
        0 AS SUL_all_time,
        0 AS CIP_7_days,
        0 AS CIP_14_days,
        0 AS CIP_30_days,
        0 AS CIP_90_days,
        0 AS CIP_180_days,
        0 AS CIP_all_time,
        0 AS CEF_7_days,
        0 AS CEF_14_days,
        0 AS CEF_30_days,
        0 AS CEF_90_days,
        0 AS CEF_180_days,
        0 AS CEF_all_time,
        0 AS CEF1_7_days,
        0 AS CEF1_14_days,
        0 AS CEF1_30_days,
        0 AS CEF1_90_days,
        0 AS CEF1_180_days,
        0 AS CEF1_all_time,
        0 AS LEV_7_days,
        0 AS LEV_14_days,
        0 AS LEV_30_days,
        0 AS LEV_90_days,
        0 AS LEV_180_days,
        0 AS LEV_all_time,
        0 AS AZI_7_days,
        0 AS AZI_14_days,
        0 AS AZI_30_days,
        0 AS AZI_90_days,
        0 AS AZI_180_days,
        0 AS AZI_all_time,
        0 AS AMO_7_days,
        0 AS AMO_14_days,
        0 AS AMO_30_days,
        0 AS AMO_90_days,
        0 AS AMO_180_days,
        0 AS AMO_all_time,
        0 AS MET_7_days,
        0 AS MET_14_days,
        0 AS MET_30_days,
        0 AS MET_90_days,
        0 AS MET_180_days,
        0 AS MET_all_time,
        0 AS CEF2_7_days,
        0 AS CEF2_14_days,
        0 AS CEF2_30_days,
        0 AS CEF2_90_days,
        0 AS CEF2_180_days,
        0 AS CEF2_all_time,
        0 AS VAN_7_days,
        0 AS VAN_14_days,
        0 AS VAN_30_days,
        0 AS VAN_90_days,
        0 AS VAN_180_days,
        0 AS VAN_all_time,
        0 AS LEV1_7_days,
        0 AS LEV1_14_days,
        0 AS LEV1_30_days,
        0 AS LEV1_90_days,
        0 AS LEV1_180_days,
        0 AS LEV1_all_time,
        0 AS VAN1_7_days,
        0 AS VAN1_14_days,
        0 AS VAN1_30_days,
        0 AS VAN1_90_days,
        0 AS VAN1_180_days,
        0 AS VAN1_all_time,
        0 AS MET1_7_days,
        0 AS MET1_14_days,
        0 AS MET1_30_days,
        0 AS MET1_90_days,
        0 AS MET1_180_days,
        0 AS MET1_all_time,
        0 AS CIP1_7_days,
        0 AS CIP1_14_days,
        0 AS CIP1_30_days,
        0 AS CIP1_90_days,
        0 AS CIP1_180_days,
        0 AS CIP1_all_time,
        0 AS DOX_7_days,
        0 AS DOX_14_days,
        0 AS DOX_30_days,
        0 AS DOX_90_days,
        0 AS DOX_180_days,
        0 AS DOX_all_time,
        0 AS CEF3_7_days,
        0 AS CEF3_14_days,
        0 AS CEF3_30_days,
        0 AS CEF3_90_days,
        0 AS CEF3_180_days,
        0 AS CEF3_all_time,
        0 AS PIP1_7_days,
        0 AS PIP1_14_days,
        0 AS PIP1_30_days,
        0 AS PIP1_90_days,
        0 AS PIP1_180_days,
        0 AS PIP1_all_time,
        0 AS RIF_7_days,
        0 AS RIF_14_days,
        0 AS RIF_30_days,
        0 AS RIF_90_days,
        0 AS RIF_180_days,
        0 AS RIF_all_time,
        0 AS VAN2_7_days,
        0 AS VAN2_14_days,
        0 AS VAN2_30_days,
        0 AS VAN2_90_days,
        0 AS VAN2_180_days,
        0 AS VAN2_all_time,
        0 AS CLI_7_days,
        0 AS CLI_14_days,
        0 AS CLI_30_days,
        0 AS CLI_90_days,
        0 AS CLI_180_days,
        0 AS CLI_all_time,
        0 AS AMO1_7_days,
        0 AS AMO1_14_days,
        0 AS AMO1_30_days,
        0 AS AMO1_90_days,
        0 AS AMO1_180_days,
        0 AS AMO1_all_time,
        0 AS NIT1_7_days,
        0 AS NIT1_14_days,
        0 AS NIT1_30_days,
        0 AS NIT1_90_days,
        0 AS NIT1_180_days,
        0 AS NIT1_all_time,
        0 AS MAC_7_days,
        0 AS MAC_14_days,
        0 AS MAC_30_days,
        0 AS MAC_90_days,
        0 AS MAC_180_days,
        0 AS MAC_all_time,
        0 AS GEN_7_days,
        0 AS GEN_14_days,
        0 AS GEN_30_days,
        0 AS GEN_90_days,
        0 AS GEN_180_days,
        0 AS GEN_all_time,
        0 AS CEF4_7_days,
        0 AS CEF4_14_days,
        0 AS CEF4_30_days,
        0 AS CEF4_90_days,
        0 AS CEF4_180_days,
        0 AS CEF4_all_time,
        0 AS CLI1_7_days,
        0 AS CLI1_14_days,
        0 AS CLI1_30_days,
        0 AS CLI1_90_days,
        0 AS CLI1_180_days,
        0 AS CLI1_all_time,
        0 AS CEF5_7_days,
        0 AS CEF5_14_days,
        0 AS CEF5_30_days,
        0 AS CEF5_90_days,
        0 AS CEF5_180_days,
        0 AS CEF5_all_time,
        0 AS CIP2_7_days,
        0 AS CIP2_14_days,
        0 AS CIP2_30_days,
        0 AS CIP2_90_days,
        0 AS CIP2_180_days,
        0 AS CIP2_all_time,
        0 AS CLI2_7_days,
        0 AS CLI2_14_days,
        0 AS CLI2_30_days,
        0 AS CLI2_90_days,
        0 AS CLI2_180_days,
        0 AS CLI2_all_time,
        0 AS VAN3_7_days,
0 AS VAN3_14_days,
0 AS VAN3_30_days,
0 AS VAN3_90_days,
0 AS VAN3_180_days,
0 AS VAN3_all_time,
0 AS MOX_7_days,
0 AS MOX_14_days,
0 AS MOX_30_days,
0 AS MOX_90_days,
0 AS MOX_180_days,
0 AS MOX_all_time,
0 AS GEN1_7_days,
0 AS GEN1_14_days,
0 AS GEN1_30_days,
0 AS GEN1_90_days,
0 AS GEN1_180_days,
0 AS GEN1_all_time,
0 AS LIN_7_days,
0 AS LIN_14_days,
0 AS LIN_30_days,
0 AS LIN_90_days,
0 AS LIN_180_days,
0 AS LIN_all_time,
0 AS ZIT_7_days,
0 AS ZIT_14_days,
0 AS ZIT_30_days,
0 AS ZIT_90_days,
0 AS ZIT_180_days,
0 AS ZIT_all_time,
0 AS ERY_7_days,
0 AS ERY_14_days,
0 AS ERY_30_days,
0 AS ERY_90_days,
0 AS ERY_180_days,
0 AS ERY_all_time,
0 AS BAC_7_days,
0 AS BAC_14_days,
0 AS BAC_30_days,
0 AS BAC_90_days,
0 AS BAC_180_days,
0 AS BAC_all_time,
0 AS FOS_7_days,
0 AS FOS_14_days,
0 AS FOS_30_days,
0 AS FOS_90_days,
0 AS FOS_180_days,
0 AS FOS_all_time,
0 AS CEF6_7_days,
0 AS CEF6_14_days,
0 AS CEF6_30_days,
0 AS CEF6_90_days,
0 AS CEF6_180_days,
0 AS CEF6_all_time,
0 AS KEF_7_days,
0 AS KEF_14_days,
0 AS KEF_30_days,
0 AS KEF_90_days,
0 AS KEF_180_days,
0 AS KEF_all_time,
0 AS COL_7_days,
0 AS COL_14_days,
0 AS COL_30_days,
0 AS COL_90_days,
0 AS COL_180_days,
0 AS COL_all_time,
0 AS DOX1_7_days,
0 AS DOX1_14_days,
0 AS DOX1_30_days,
0 AS DOX1_90_days,
0 AS DOX1_180_days,
0 AS DOX1_all_time,
0 AS LEV2_7_days,
0 AS LEV2_14_days,
0 AS LEV2_30_days,
0 AS LEV2_90_days,
0 AS LEV2_180_days,
0 AS LEV2_all_time,
0 AS CLA_7_days,
0 AS CLA_14_days,
0 AS CLA_30_days,
0 AS CLA_90_days,
0 AS CLA_180_days,
0 AS CLA_all_time,
0 AS RIF1_7_days,
0 AS RIF1_14_days,
0 AS RIF1_30_days,
0 AS RIF1_90_days,
0 AS RIF1_180_days,
0 AS RIF1_all_time,
0 AS CIP3_7_days,
0 AS CIP3_14_days,
0 AS CIP3_30_days,
0 AS CIP3_90_days,
0 AS CIP3_180_days,
0 AS CIP3_all_time,
0 AS CEF7_7_days,
0 AS CEF7_14_days,
0 AS CEF7_30_days,
0 AS CEF7_90_days,
0 AS CEF7_180_days,
0 AS CEF7_all_time,
0 AS AUG_7_days,
0 AS AUG_14_days,
0 AS AUG_30_days,
0 AS AUG_90_days,
0 AS AUG_180_days,
0 AS AUG_all_time,
0 AS CEF8_7_days,
0 AS CEF8_14_days,
0 AS CEF8_30_days,
0 AS CEF8_90_days,
0 AS CEF8_180_days,
0 AS CEF8_all_time,
0 AS MET2_7_days,
0 AS MET2_14_days,
0 AS MET2_30_days,
0 AS MET2_90_days,
0 AS MET2_180_days,
0 AS MET2_all_time,
0 AS ERT_7_days,
0 AS ERT_14_days,
0 AS ERT_30_days,
0 AS ERT_90_days,
0 AS ERT_180_days,
0 AS ERT_all_time,
0 AS LIN1_7_days,
0 AS LIN1_14_days,
0 AS LIN1_30_days,
0 AS LIN1_90_days,
0 AS LIN1_180_days,
0 AS LIN1_all_time,
0 AS OFL_7_days,
0 AS OFL_14_days,
0 AS OFL_30_days,
0 AS OFL_90_days,
0 AS OFL_180_days,
0 AS OFL_all_time,
0 AS PEN_7_days,
0 AS PEN_14_days,
0 AS PEN_30_days,
0 AS PEN_90_days,
0 AS PEN_180_days,
0 AS PEN_all_time,
0 AS SIL_7_days,
0 AS SIL_14_days,
0 AS SIL_30_days,
0 AS SIL_90_days,
0 AS SIL_180_days,
0 AS SIL_all_time,
0 AS DAP_7_days,
0 AS DAP_14_days,
0 AS DAP_30_days,
0 AS DAP_90_days,
0 AS DAP_180_days,
0 AS DAP_all_time,
0 AS CIP4_7_days,
0 AS CIP4_14_days,
0 AS CIP4_30_days,
0 AS CIP4_90_days,
0 AS CIP4_180_days,
0 AS CIP4_all_time,
0 AS AMP_7_days,
0 AS AMP_14_days,
0 AS AMP_30_days,
0 AS AMP_90_days,
0 AS AMP_180_days,
0 AS AMP_all_time,
0 AS ISO_7_days,
0 AS ISO_14_days,
0 AS ISO_30_days,
0 AS ISO_90_days,
0 AS ISO_180_days,
0 AS ISO_all_time,
0 AS BAC1_7_days,
0 AS BAC1_14_days,
0 AS BAC1_30_days,
0 AS BAC1_90_days,
0 AS BAC1_180_days,
0 AS BAC1_all_time,
0 AS FID_7_days,
0 AS FID_14_days,
0 AS FID_30_days,
0 AS FID_90_days,
0 AS FID_180_days,
0 AS FID_all_time,
0 AS AZT_7_days,
0 AS AZT_14_days,
0 AS AZT_30_days,
0 AS AZT_90_days,
0 AS AZT_180_days,
0 AS AZT_all_time,
0 AS ETH_7_days,
0 AS ETH_14_days,
0 AS ETH_30_days,
0 AS ETH_90_days,
0 AS ETH_180_days,
0 AS ETH_all_time,
0 AS TOB_7_days,
0 AS TOB_14_days,
0 AS TOB_30_days,
0 AS TOB_90_days,
0 AS TOB_180_days,
0 AS TOB_all_time,
0 AS CEF9_7_days,
0 AS CEF9_14_days,
0 AS CEF9_30_days,
0 AS CEF9_90_days,
0 AS CEF9_180_days,
0 AS CEF9_all_time,
0 AS AMP1_7_days,
0 AS AMP1_14_days,
0 AS AMP1_30_days,
0 AS AMP1_90_days,
0 AS AMP1_180_days,
0 AS AMP1_all_time,
0 AS MIN_7_days,
0 AS MIN_14_days,
0 AS MIN_30_days,
0 AS MIN_90_days,
0 AS MIN_180_days,
0 AS MIN_all_time,
0 AS CEF10_7_days,
0 AS CEF10_14_days,
0 AS CEF10_30_days,
0 AS CEF10_90_days,
0 AS CEF10_180_days,
0 AS CEF10_all_time,
0 AS AZT1_7_days,
0 AS AZT1_14_days,
0 AS AZT1_30_days,
0 AS AZT1_90_days,
0 AS AZT1_180_days,
0 AS AZT1_all_time,
0 AS XIF_7_days,
0 AS XIF_14_days,
0 AS XIF_30_days,
0 AS XIF_90_days,
0 AS XIF_180_days,
0 AS XIF_all_time,
0 AS ERY1_7_days,
0 AS ERY1_14_days,
0 AS ERY1_30_days,
0 AS ERY1_90_days,
0 AS ERY1_180_days,
0 AS ERY1_all_time,
0 AS GEN2_7_days,
0 AS GEN2_14_days,
0 AS GEN2_30_days,
0 AS GEN2_90_days,
0 AS GEN2_180_days,
0 AS GEN2_all_time,
0 AS MER_7_days,
0 AS MER_14_days,
0 AS MER_30_days,
0 AS MER_90_days,
0 AS MER_180_days,
0 AS MER_all_time,
0 AS GAT_7_days,
0 AS GAT_14_days,
0 AS GAT_30_days,
0 AS GAT_90_days,
0 AS GAT_180_days,
0 AS GAT_all_time,
0 AS FLA_7_days,
0 AS FLA_14_days,
0 AS FLA_30_days,
0 AS FLA_90_days,
0 AS FLA_180_days,
0 AS FLA_all_time,
0 AS MAC1_7_days,
0 AS MAC1_14_days,
0 AS MAC1_30_days,
0 AS MAC1_90_days,
0 AS MAC1_180_days,
0 AS MAC1_all_time,
0 AS AMI_7_days,
0 AS AMI_14_days,
0 AS AMI_30_days,
0 AS AMI_90_days,
0 AS AMI_180_days,
0 AS AMI_all_time,
0 AS TRI_7_days,
0 AS TRI_14_days,
0 AS TRI_30_days,
0 AS TRI_90_days,
0 AS TRI_180_days,
0 AS TRI_all_time,
0 AS TOB1_7_days,
0 AS TOB1_14_days,
0 AS TOB1_30_days,
0 AS TOB1_90_days,
0 AS TOB1_180_days,
0 AS TOB1_all_time,
0 AS DIC_7_days,
0 AS DIC_14_days,
0 AS DIC_30_days,
0 AS DIC_90_days,
0 AS DIC_180_days,
0 AS DIC_all_time,
0 AS MOX1_7_days,
0 AS MOX1_14_days,
0 AS MOX1_30_days,
0 AS MOX1_90_days,
0 AS MOX1_180_days,
0 AS MOX1_all_time,
0 AS HIP_7_days,
0 AS HIP_14_days,
0 AS HIP_30_days,
0 AS HIP_90_days,
0 AS HIP_180_days,
0 AS HIP_all_time,
0 AS CEF11_7_days,
0 AS CEF11_14_days,
0 AS CEF11_30_days,
0 AS CEF11_90_days,
0 AS CEF11_180_days,
0 AS CEF11_all_time,
0 AS ZYV_7_days,
0 AS ZYV_14_days,
0 AS ZYV_30_days,
0 AS ZYV_90_days,
0 AS ZYV_180_days,
0 AS ZYV_all_time,
0 AS MET3_7_days,
0 AS MET3_14_days,
0 AS MET3_30_days,
0 AS MET3_90_days,
0 AS MET3_180_days,
0 AS MET3_all_time,
0 AS RIF2_7_days,
0 AS RIF2_14_days,
0 AS RIF2_30_days,
0 AS RIF2_90_days,
0 AS RIF2_180_days,
0 AS RIF2_all_time,
0 AS TED_7_days,
0 AS TED_14_days,
0 AS TED_30_days,
0 AS TED_90_days,
0 AS TED_180_days,
0 AS TED_all_time
FROM missing_rows;



MERGE INTO `som-nero-phi-jonc101.antimicrobial_stewardship.microbiology_cultures_prior_med` AS target
USING `som-nero-phi-jonc101.antimicrobial_stewardship.temp_missing_rows` AS source
ON target.anon_id = source.anon_id 
   AND target.pat_enc_csn_id_coded = source.pat_enc_csn_id_coded 
   AND target.order_proc_id_coded = source.order_proc_id_coded
   AND target.order_time_jittered_utc = source.order_time_jittered_utc
WHEN NOT MATCHED THEN
INSERT (
    anon_id,
    pat_enc_csn_id_coded,
    order_proc_id_coded,
    order_time_jittered_utc,
    NIT_7_days,
    NIT_14_days,
NIT_30_days,
NIT_90_days,
NIT_180_days,
NIT_all_time,
CEP_7_days,
CEP_14_days,
CEP_30_days,
CEP_90_days,
CEP_180_days,
CEP_all_time,
PIP_7_days,
PIP_14_days,
PIP_30_days,
PIP_90_days,
PIP_180_days,
PIP_all_time,
SUL_7_days,
SUL_14_days,
SUL_30_days,
SUL_90_days,
SUL_180_days,
SUL_all_time,
CIP_7_days,
CIP_14_days,
CIP_30_days,
CIP_90_days,
CIP_180_days,
CIP_all_time,
CEF_7_days,
CEF_14_days,
CEF_30_days,
CEF_90_days,
CEF_180_days,
CEF_all_time,
CEF1_7_days,
CEF1_14_days,
CEF1_30_days,
CEF1_90_days,
CEF1_180_days,
CEF1_all_time,
LEV_7_days,
LEV_14_days,
LEV_30_days,
LEV_90_days,
LEV_180_days,
LEV_all_time,
AZI_7_days,
AZI_14_days,
AZI_30_days,
AZI_90_days,
AZI_180_days,
AZI_all_time,
AMO_7_days,
AMO_14_days,
AMO_30_days,
AMO_90_days,
AMO_180_days,
AMO_all_time,
MET_7_days,
MET_14_days,
MET_30_days,
MET_90_days,
MET_180_days,
MET_all_time,
CEF2_7_days,
CEF2_14_days,
CEF2_30_days,
CEF2_90_days,
CEF2_180_days,
CEF2_all_time,
VAN_7_days,
VAN_14_days,
VAN_30_days,
VAN_90_days,
VAN_180_days,
VAN_all_time,
LEV1_7_days,
LEV1_14_days,
LEV1_30_days,
LEV1_90_days,
LEV1_180_days,
LEV1_all_time,
VAN1_7_days,
VAN1_14_days,
VAN1_30_days,
VAN1_90_days,
VAN1_180_days,
VAN1_all_time,
MET1_7_days,
MET1_14_days,
MET1_30_days,
MET1_90_days,
MET1_180_days,
MET1_all_time,
CIP1_7_days,
CIP1_14_days,
CIP1_30_days,
CIP1_90_days,
CIP1_180_days,
CIP1_all_time,
DOX_7_days,
DOX_14_days,
DOX_30_days,
DOX_90_days,
DOX_180_days,
DOX_all_time,
CEF3_7_days,
CEF3_14_days,
CEF3_30_days,
CEF3_90_days,
CEF3_180_days,
CEF3_all_time,
PIP1_7_days,
PIP1_14_days,
PIP1_30_days,
PIP1_90_days,
PIP1_180_days,
PIP1_all_time,
RIF_7_days,
RIF_14_days,
RIF_30_days,
RIF_90_days,
RIF_180_days,
RIF_all_time,
VAN2_7_days,
VAN2_14_days,
VAN2_30_days,
VAN2_90_days,
VAN2_180_days,
VAN2_all_time,
CLI_7_days,
CLI_14_days,
CLI_30_days,
CLI_90_days,
CLI_180_days,
CLI_all_time,
AMO1_7_days,
AMO1_14_days,
AMO1_30_days,
AMO1_90_days,
AMO1_180_days,
AMO1_all_time,
NIT1_7_days,
NIT1_14_days,
NIT1_30_days,
NIT1_90_days,
NIT1_180_days,
NIT1_all_time,
MAC_7_days,
MAC_14_days,
MAC_30_days,
MAC_90_days,
MAC_180_days,
MAC_all_time,
GEN_7_days,
GEN_14_days,
GEN_30_days,
GEN_90_days,
GEN_180_days,
GEN_all_time,
CEF4_7_days,
CEF4_14_days,
CEF4_30_days,
CEF4_90_days,
CEF4_180_days,
CEF4_all_time,
CLI1_7_days,
CLI1_14_days,
CLI1_30_days,
CLI1_90_days,
CLI1_180_days,
CLI1_all_time,
CEF5_7_days,
CEF5_14_days,
CEF5_30_days,
CEF5_90_days,
CEF5_180_days,
CEF5_all_time,
CIP2_7_days,
CIP2_14_days,
CIP2_30_days,
CIP2_90_days,
CIP2_180_days,
CIP2_all_time,
CLI2_7_days,
CLI2_14_days,
CLI2_30_days,
CLI2_90_days,
CLI2_180_days,
CLI2_all_time,
VAN3_7_days,
VAN3_14_days,
VAN3_30_days,
VAN3_90_days,
VAN3_180_days,
VAN3_all_time,
MOX_7_days,
MOX_14_days,
MOX_30_days,
MOX_90_days,
MOX_180_days,
MOX_all_time,
GEN1_7_days,
GEN1_14_days,
GEN1_30_days,
GEN1_90_days,
GEN1_180_days,
GEN1_all_time,
LIN_7_days,
LIN_14_days,
LIN_30_days,
LIN_90_days,
LIN_180_days,
LIN_all_time,
ZIT_7_days,
ZIT_14_days,
ZIT_30_days,
ZIT_90_days,
ZIT_180_days,
ZIT_all_time,
ERY_7_days,
ERY_14_days,
ERY_30_days,
ERY_90_days,
ERY_180_days,
ERY_all_time,
BAC_7_days,
BAC_14_days,
BAC_30_days,
BAC_90_days,
BAC_180_days,
BAC_all_time,
FOS_7_days,
FOS_14_days,
FOS_30_days,
FOS_90_days,
FOS_180_days,
FOS_all_time,
CEF6_7_days,
CEF6_14_days,
CEF6_30_days,
CEF6_90_days,
CEF6_180_days,
CEF6_all_time,
KEF_7_days,
KEF_14_days,
KEF_30_days,
KEF_90_days,
KEF_180_days,
KEF_all_time,
COL_7_days,
COL_14_days,
COL_30_days,
COL_90_days,
COL_180_days,
COL_all_time,
DOX1_7_days,
DOX1_14_days,
DOX1_30_days,
DOX1_90_days,
DOX1_180_days,
DOX1_all_time,
LEV2_7_days,
LEV2_14_days,
LEV2_30_days,
LEV2_90_days,
LEV2_180_days,
LEV2_all_time,
CLA_7_days,
CLA_14_days,
CLA_30_days,
CLA_90_days,
CLA_180_days,
CLA_all_time,
RIF1_7_days,
RIF1_14_days,
RIF1_30_days,
RIF1_90_days,
RIF1_180_days,
RIF1_all_time,
CIP3_7_days,
CIP3_14_days,
CIP3_30_days,
CIP3_90_days,
CIP3_180_days,
CIP3_all_time,
CEF7_7_days,
CEF7_14_days,
CEF7_30_days,
CEF7_90_days,
CEF7_180_days,
CEF7_all_time,
AUG_7_days,
AUG_14_days,
AUG_30_days,
AUG_90_days,
AUG_180_days,
AUG_all_time,
CEF8_7_days,
CEF8_14_days,
CEF8_30_days,
CEF8_90_days,
CEF8_180_days,
CEF8_all_time,
MET2_7_days,
MET2_14_days,
MET2_30_days,
MET2_90_days,
MET2_180_days,
MET2_all_time,
ERT_7_days,
ERT_14_days,
ERT_30_days,
ERT_90_days,
ERT_180_days,
ERT_all_time,
LIN1_7_days,
LIN1_14_days,
LIN1_30_days,
LIN1_90_days,
LIN1_180_days,
LIN1_all_time,
OFL_7_days,
OFL_14_days,
OFL_30_days,
OFL_90_days,
OFL_180_days,
OFL_all_time,
PEN_7_days,
PEN_14_days,
PEN_30_days,
PEN_90_days,
PEN_180_days,
PEN_all_time,
SIL_7_days,
SIL_14_days,
SIL_30_days,
SIL_90_days,
SIL_180_days,
SIL_all_time,
DAP_7_days,
DAP_14_days,
DAP_30_days,
DAP_90_days,
DAP_180_days,
DAP_all_time,
CIP4_7_days,
CIP4_14_days,
CIP4_30_days,
CIP4_90_days,
CIP4_180_days,
CIP4_all_time,
AMP_7_days,
AMP_14_days,
AMP_30_days,
AMP_90_days,
AMP_180_days,
AMP_all_time,
ISO_7_days,
ISO_14_days,
ISO_30_days,
ISO_90_days,
ISO_180_days,
ISO_all_time,
BAC1_7_days,
BAC1_14_days,
BAC1_30_days,
BAC1_90_days,
BAC1_180_days,
BAC1_all_time,
FID_7_days,
FID_14_days,
FID_30_days,
FID_90_days,
FID_180_days,
FID_all_time,
AZT_7_days,
AZT_14_days,
AZT_30_days,
AZT_90_days,
AZT_180_days,
AZT_all_time,
ETH_7_days,
ETH_14_days,
ETH_30_days,
ETH_90_days,
ETH_180_days,
ETH_all_time,
TOB_7_days,
TOB_14_days,
TOB_30_days,
TOB_90_days,
TOB_180_days,
TOB_all_time,
CEF9_7_days,
CEF9_14_days,
CEF9_30_days,
CEF9_90_days,
CEF9_180_days,
CEF9_all_time,
AMP1_7_days,
AMP1_14_days,
AMP1_30_days,
AMP1_90_days,
AMP1_180_days,
AMP1_all_time,
MIN_7_days,
MIN_14_days,
MIN_30_days,
MIN_90_days,
MIN_180_days,
MIN_all_time,
CEF10_7_days,
CEF10_14_days,
CEF10_30_days,
CEF10_90_days,
CEF10_180_days,
CEF10_all_time,
AZT1_7_days,
AZT1_14_days,
AZT1_30_days,
AZT1_90_days,
AZT1_180_days,
AZT1_all_time,
XIF_7_days,
XIF_14_days,
XIF_30_days,
XIF_90_days,
XIF_180_days,
XIF_all_time,
ERY1_7_days,
ERY1_14_days,
ERY1_30_days,
ERY1_90_days,
ERY1_180_days,
ERY1_all_time,
GEN2_7_days,
GEN2_14_days,
GEN2_30_days,
GEN2_90_days,
GEN2_180_days,
GEN2_all_time,
MER_7_days,
MER_14_days,
MER_30_days,
MER_90_days,
MER_180_days,
MER_all_time,
GAT_7_days,
GAT_14_days,
GAT_30_days,
GAT_90_days,
GAT_180_days,
GAT_all_time,
FLA_7_days,
FLA_14_days,
FLA_30_days,
FLA_90_days,
FLA_180_days,
FLA_all_time,
MAC1_7_days,
MAC1_14_days,
MAC1_30_days,
MAC1_90_days,
MAC1_180_days,
MAC1_all_time,
AMI_7_days,
AMI_14_days,
AMI_30_days,
AMI_90_days,
AMI_180_days,
AMI_all_time,
TRI_7_days,
TRI_14_days,
TRI_30_days,
TRI_90_days,
TRI_180_days,
TRI_all_time,
TOB1_7_days,
TOB1_14_days,
TOB1_30_days,
TOB1_90_days,
TOB1_180_days,
TOB1_all_time,
DIC_7_days,
DIC_14_days,
DIC_30_days,
DIC_90_days,
DIC_180_days,
DIC_all_time,
MOX1_7_days,
MOX1_14_days,
MOX1_30_days,
MOX1_90_days,
MOX1_180_days,
MOX1_all_time,
HIP_7_days,
HIP_14_days,
HIP_30_days,
HIP_90_days,
HIP_180_days,
HIP_all_time,
CEF11_7_days,
CEF11_14_days,
CEF11_30_days,
CEF11_90_days,
CEF11_180_days,
CEF11_all_time,
ZYV_7_days,
ZYV_14_days,
ZYV_30_days,
ZYV_90_days,
ZYV_180_days,
ZYV_all_time,
MET3_7_days,
MET3_14_days,
MET3_30_days,
MET3_90_days,
MET3_180_days,
MET3_all_time,
RIF2_7_days,
RIF2_14_days,
RIF2_30_days,
RIF2_90_days,
RIF2_180_days,
RIF2_all_time,
TED_7_days,
TED_14_days,
TED_30_days,
TED_90_days,
TED_180_days,
TED_all_time
)
VALUES (
        source.anon_id,
    source.pat_enc_csn_id_coded,
    source.order_proc_id_coded,
    source.order_time_jittered_utc,
    source.NIT_7_days,
source.NIT_14_days,
source.NIT_30_days,
source.NIT_90_days,
source.NIT_180_days,
source.NIT_all_time,
source.CEP_7_days,
source.CEP_14_days,
source.CEP_30_days,
source.CEP_90_days,
source.CEP_180_days,
source.CEP_all_time,
source.PIP_7_days,
source.PIP_14_days,
source.PIP_30_days,
source.PIP_90_days,
source.PIP_180_days,
source.PIP_all_time,
source.SUL_7_days,
source.SUL_14_days,
source.SUL_30_days,
source.SUL_90_days,
source.SUL_180_days,
source.SUL_all_time,
source.CIP_7_days,
source.CIP_14_days,
source.CIP_30_days,
source.CIP_90_days,
source.CIP_180_days,
source.CIP_all_time,
source.CEF_7_days,
source.CEF_14_days,
source.CEF_30_days,
source.CEF_90_days,
source.CEF_180_days,
source.CEF_all_time,
source.CEF1_7_days,
source.CEF1_14_days,
source.CEF1_30_days,
source.CEF1_90_days,
source.CEF1_180_days,
source.CEF1_all_time,
source.LEV_7_days,
source.LEV_14_days,
source.LEV_30_days,
source.LEV_90_days,
source.LEV_180_days,
source.LEV_all_time,
source.AZI_7_days,
source.AZI_14_days,
source.AZI_30_days,
source.AZI_90_days,
source.AZI_180_days,
source.AZI_all_time,
source.AMO_7_days,
source.AMO_14_days,
source.AMO_30_days,
source.AMO_90_days,
source.AMO_180_days,
source.AMO_all_time,
source.MET_7_days,
source.MET_14_days,
source.MET_30_days,
source.MET_90_days,
source.MET_180_days,
source.MET_all_time,
source.CEF2_7_days,
source.CEF2_14_days,
source.CEF2_30_days,
source.CEF2_90_days,
source.CEF2_180_days,
source.CEF2_all_time,
source.VAN_7_days,
source.VAN_14_days,
source.VAN_30_days,
source.VAN_90_days,
source.VAN_180_days,
source.VAN_all_time,
source.LEV1_7_days,
source.LEV1_14_days,
source.LEV1_30_days,
source.LEV1_90_days,
source.LEV1_180_days,
source.LEV1_all_time,
source.VAN1_7_days,
source.VAN1_14_days,
source.VAN1_30_days,
source.VAN1_90_days,
source.VAN1_180_days,
source.VAN1_all_time,
source.MET1_7_days,
source.MET1_14_days,
source.MET1_30_days,
source.MET1_90_days,
source.MET1_180_days,
source.MET1_all_time,
source.CIP1_7_days,
source.CIP1_14_days,
source.CIP1_30_days,
source.CIP1_90_days,
source.CIP1_180_days,
source.CIP1_all_time,
source.DOX_7_days,
source.DOX_14_days,
source.DOX_30_days,
source.DOX_90_days,
source.DOX_180_days,
source.DOX_all_time,
source.CEF3_7_days,
source.CEF3_14_days,
source.CEF3_30_days,
source.CEF3_90_days,
source.CEF3_180_days,
source.CEF3_all_time,
source.PIP1_7_days,
source.PIP1_14_days,
source.PIP1_30_days,
source.PIP1_90_days,
source.PIP1_180_days,
source.PIP1_all_time,
source.RIF_7_days,
source.RIF_14_days,
source.RIF_30_days,
source.RIF_90_days,
source.RIF_180_days,
source.RIF_all_time,
source.VAN2_7_days,
source.VAN2_14_days,
source.VAN2_30_days,
source.VAN2_90_days,
source.VAN2_180_days,
source.VAN2_all_time,
source.CLI_7_days,
source.CLI_14_days,
source.CLI_30_days,
source.CLI_90_days,
source.CLI_180_days,
source.CLI_all_time,
source.AMO1_7_days,
source.AMO1_14_days,
source.AMO1_30_days,
source.AMO1_90_days,
source.AMO1_180_days,
source.AMO1_all_time,
source.NIT1_7_days,
source.NIT1_14_days,
source.NIT1_30_days,
source.NIT1_90_days,
source.NIT1_180_days,
source.NIT1_all_time,
source.MAC_7_days,
source.MAC_14_days,
source.MAC_30_days,
source.MAC_90_days,
source.MAC_180_days,
source.MAC_all_time,
source.GEN_7_days,
source.GEN_14_days,
source.GEN_30_days,
source.GEN_90_days,
source.GEN_180_days,
source.GEN_all_time,
source.CEF4_7_days,
source.CEF4_14_days,
source.CEF4_30_days,
source.CEF4_90_days,
source.CEF4_180_days,
source.CEF4_all_time,
source.CLI1_7_days,
source.CLI1_14_days,
source.CLI1_30_days,
source.CLI1_90_days,
source.CLI1_180_days,
source.CLI1_all_time,
source.CEF5_7_days,
source.CEF5_14_days,
source.CEF5_30_days,
source.CEF5_90_days,
source.CEF5_180_days,
source.CEF5_all_time,
source.CIP2_7_days,
source.CIP2_14_days,
source.CIP2_30_days,
source.CIP2_90_days,
source.CIP2_180_days,
source.CIP2_all_time,
source.CLI2_7_days,
source.CLI2_14_days,
source.CLI2_30_days,
source.CLI2_90_days,
source.CLI2_180_days,
source.CLI2_all_time,
source.VAN3_7_days,
source.VAN3_14_days,
source.VAN3_30_days,
source.VAN3_90_days,
source.VAN3_180_days,
source.VAN3_all_time,
source.MOX_7_days,
source.MOX_14_days,
source.MOX_30_days,
source.MOX_90_days,
source.MOX_180_days,
source.MOX_all_time,
source.GEN1_7_days,
source.GEN1_14_days,
source.GEN1_30_days,
source.GEN1_90_days,
source.GEN1_180_days,
source.GEN1_all_time,
source.LIN_7_days,
source.LIN_14_days,
source.LIN_30_days,
source.LIN_90_days,
source.LIN_180_days,
source.LIN_all_time,
source.ZIT_7_days,
source.ZIT_14_days,
source.ZIT_30_days,
source.ZIT_90_days,
source.ZIT_180_days,
source.ZIT_all_time,
source.ERY_7_days,
source.ERY_14_days,
source.ERY_30_days,
source.ERY_90_days,
source.ERY_180_days,
source.ERY_all_time,
source.BAC_7_days,
source.BAC_14_days,
source.BAC_30_days,
source.BAC_90_days,
source.BAC_180_days,
source.BAC_all_time,
source.FOS_7_days,
source.FOS_14_days,
source.FOS_30_days,
source.FOS_90_days,
source.FOS_180_days,
source.FOS_all_time,
source.CEF6_7_days,
source.CEF6_14_days,
source.CEF6_30_days,
source.CEF6_90_days,
source.CEF6_180_days,
source.CEF6_all_time,
source.KEF_7_days,
source.KEF_14_days,
source.KEF_30_days,
source.KEF_90_days,
source.KEF_180_days,
source.KEF_all_time,
source.COL_7_days,
source.COL_14_days,
source.COL_30_days,
source.COL_90_days,
source.COL_180_days,
source.COL_all_time,
source.DOX1_7_days,
source.DOX1_14_days,
source.DOX1_30_days,
source.DOX1_90_days,
source.DOX1_180_days,
source.DOX1_all_time,
source.LEV2_7_days,
source.LEV2_14_days,
source.LEV2_30_days,
source.LEV2_90_days,
source.LEV2_180_days,
source.LEV2_all_time,
source.CLA_7_days,
source.CLA_14_days,
source.CLA_30_days,
source.CLA_90_days,
source.CLA_180_days,
source.CLA_all_time,
source.RIF1_7_days,
source.RIF1_14_days,
source.RIF1_30_days,
source.RIF1_90_days,
source.RIF1_180_days,
source.RIF1_all_time,
source.CIP3_7_days,
source.CIP3_14_days,
source.CIP3_30_days,
source.CIP3_90_days,
source.CIP3_180_days,
source.CIP3_all_time,
source.CEF7_7_days,
source.CEF7_14_days,
source.CEF7_30_days,
source.CEF7_90_days,
source.CEF7_180_days,
source.CEF7_all_time,
source.AUG_7_days,
source.AUG_14_days,
source.AUG_30_days,
source.AUG_90_days,
source.AUG_180_days,
source.AUG_all_time,
source.CEF8_7_days,
source.CEF8_14_days,
source.CEF8_30_days,
source.CEF8_90_days,
source.CEF8_180_days,
source.CEF8_all_time,
source.MET2_7_days,
source.MET2_14_days,
source.MET2_30_days,
source.MET2_90_days,
source.MET2_180_days,
source.MET2_all_time,
source.ERT_7_days,
source.ERT_14_days,
source.ERT_30_days,
source.ERT_90_days,
source.ERT_180_days,
source.ERT_all_time,
source.LIN1_7_days,
source.LIN1_14_days,
source.LIN1_30_days,
source.LIN1_90_days,
source.LIN1_180_days,
source.LIN1_all_time,
source.OFL_7_days,
source.OFL_14_days,
source.OFL_30_days,
source.OFL_90_days,
source.OFL_180_days,
source.OFL_all_time,
source.PEN_7_days,
source.PEN_14_days,
source.PEN_30_days,
source.PEN_90_days,
source.PEN_180_days,
source.PEN_all_time,
source.SIL_7_days,
source.SIL_14_days,
source.SIL_30_days,
source.SIL_90_days,
source.SIL_180_days,
source.SIL_all_time,
source.DAP_7_days,
source.DAP_14_days,
source.DAP_30_days,
source.DAP_90_days,
source.DAP_180_days,
source.DAP_all_time,
source.CIP4_7_days,
source.CIP4_14_days,
source.CIP4_30_days,
source.CIP4_90_days,
source.CIP4_180_days,
source.CIP4_all_time,
source.AMP_7_days,
source.AMP_14_days,
source.AMP_30_days,
source.AMP_90_days,
source.AMP_180_days,
source.AMP_all_time,
source.ISO_7_days,
source.ISO_14_days,
source.ISO_30_days,
source.ISO_90_days,
source.ISO_180_days,
source.ISO_all_time,
source.BAC1_7_days,
source.BAC1_14_days,
source.BAC1_30_days,
source.BAC1_90_days,
source.BAC1_180_days,
source.BAC1_all_time,
source.FID_7_days,
source.FID_14_days,
source.FID_30_days,
source.FID_90_days,
source.FID_180_days,
source.FID_all_time,
source.AZT_7_days,
source.AZT_14_days,
source.AZT_30_days,
source.AZT_90_days,
source.AZT_180_days,
source.AZT_all_time,
source.ETH_7_days,
source.ETH_14_days,
source.ETH_30_days,
source.ETH_90_days,
source.ETH_180_days,
source.ETH_all_time,
source.TOB_7_days,
source.TOB_14_days,
source.TOB_30_days,
source.TOB_90_days,
source.TOB_180_days,
source.TOB_all_time,
source.CEF9_7_days,
source.CEF9_14_days,
source.CEF9_30_days,
source.CEF9_90_days,
source.CEF9_180_days,
source.CEF9_all_time,
source.AMP1_7_days,
source.AMP1_14_days,
source.AMP1_30_days,
source.AMP1_90_days,
source.AMP1_180_days,
source.AMP1_all_time,
source.MIN_7_days,
source.MIN_14_days,
source.MIN_30_days,
source.MIN_90_days,
source.MIN_180_days,
source.MIN_all_time,
source.CEF10_7_days,
source.CEF10_14_days,
source.CEF10_30_days,
source.CEF10_90_days,
source.CEF10_180_days,
source.CEF10_all_time,
source.AZT1_7_days,
source.AZT1_14_days,
source.AZT1_30_days,
source.AZT1_90_days,
source.AZT1_180_days,
source.AZT1_all_time,
source.XIF_7_days,
source.XIF_14_days,
source.XIF_30_days,
source.XIF_90_days,
source.XIF_180_days,
source.XIF_all_time,
source.ERY1_7_days,
source.ERY1_14_days,
source.ERY1_30_days,
source.ERY1_90_days,
source.ERY1_180_days,
source.ERY1_all_time,
source.GEN2_7_days,
source.GEN2_14_days,
source.GEN2_30_days,
source.GEN2_90_days,
source.GEN2_180_days,
source.GEN2_all_time,
source.MER_7_days,
source.MER_14_days,
source.MER_30_days,
source.MER_90_days,
source.MER_180_days,
source.MER_all_time,
source.GAT_7_days,
source.GAT_14_days,
source.GAT_30_days,
source.GAT_90_days,
source.GAT_180_days,
source.GAT_all_time,
source.FLA_7_days,
source.FLA_14_days,
source.FLA_30_days,
source.FLA_90_days,
source.FLA_180_days,
source.FLA_all_time,
source.MAC1_7_days,
source.MAC1_14_days,
source.MAC1_30_days,
source.MAC1_90_days,
source.MAC1_180_days,
source.MAC1_all_time,
source.AMI_7_days,
source.AMI_14_days,
source.AMI_30_days,
source.AMI_90_days,
source.AMI_180_days,
source.AMI_all_time,
source.TRI_7_days,
source.TRI_14_days,
source.TRI_30_days,
source.TRI_90_days,
source.TRI_180_days,
source.TRI_all_time,
source.TOB1_7_days,
source.TOB1_14_days,
source.TOB1_30_days,
source.TOB1_90_days,
source.TOB1_180_days,
source.TOB1_all_time,
source.DIC_7_days,
source.DIC_14_days,
source.DIC_30_days,
source.DIC_90_days,
source.DIC_180_days,
source.DIC_all_time,
source.MOX1_7_days,
source.MOX1_14_days,
source.MOX1_30_days,
source.MOX1_90_days,
source.MOX1_180_days,
source.MOX1_all_time,
source.HIP_7_days,
source.HIP_14_days,
source.HIP_30_days,
source.HIP_90_days,
source.HIP_180_days,
source.HIP_all_time,
source.CEF11_7_days,
source.CEF11_14_days,
source.CEF11_30_days,
source.CEF11_90_days,
source.CEF11_180_days,
source.CEF11_all_time,
source.ZYV_7_days,
source.ZYV_14_days,
source.ZYV_30_days,
source.ZYV_90_days,
source.ZYV_180_days,
source.ZYV_all_time,
source.MET3_7_days,
source.MET3_14_days,
source.MET3_30_days,
source.MET3_90_days,
source.MET3_180_days,
source.MET3_all_time,
source.RIF2_7_days,
source.RIF2_14_days,
source.RIF2_30_days,
source.RIF2_90_days,
source.RIF2_180_days,
source.RIF2_all_time,
source.TED_7_days,
source.TED_14_days,
source.TED_30_days,
source.TED_90_days,
source.TED_180_days,
source.TED_all_time);





