-- This query creates a table named class_subtype_lookup in BigQuery that contains antibiotics, their classes, and specific subtypes.
-- It then inserts records into this table with the provided antibiotic names, their corresponding classes, and subtypes. 
-- Finally, it selects and displays all the records from the class_subtype_lookup table.


CREATE OR REPLACE TABLE `som-nero-phi-jonc101.fateme_db.class_subtype_lookup` (
    antibiotic STRING,
    antibiotic_class STRING,
    antibiotic_subtype STRING
);

INSERT INTO `som-nero-phi-jonc101.fateme_db.class_subtype_lookup` (antibiotic, antibiotic_class, antibiotic_subtype)
VALUES
    ('Nitrofurantoin', 'Nitrofuran', 'Nitrofuran'),
    ('Cephalexin', 'Beta Lactam', 'Cephalosporin Gen1'),
    ('Piperacillin-Tazobactam-Dextrs', 'Beta Lactam', 'Beta Lactam Combo'),
    ('Sulfamethoxazole-Trimethoprim', 'Combination Antibiotic', 'Sulfonamide Combo'),
    ('Ciprofloxacin Hcl', 'Fluoroquinolone', 'Fluoroquinolone'),
    ('Cefazolin', 'Beta Lactam', 'Cephalosporin Gen1'),
    ('Cefazolin In Dextrose', 'Beta Lactam', 'Cephalosporin Gen1'),
    ('Levofloxacin', 'Fluoroquinolone', 'Fluoroquinolone'),
    ('Azithromycin', 'Macrolide Lincosamide', 'Macrolide'),
    ('Amoxicillin-Pot Clavulanate', 'Beta Lactam', 'Beta Lactam Combo'),
    ('Metronidazole In Nacl', 'Nitroimidazole', 'Nitroimidazole'),
    ('Ceftriaxone', 'Beta Lactam', 'Cephalosporin Gen3'),
    ('Vancomycin', 'Glycopeptide', 'Glycopeptide'),
    ('Levofloxacin In', 'Fluoroquinolone', 'Fluoroquinolone'),
    ('Vancomycin In Dextrose', 'Glycopeptide', 'Glycopeptide'),
    ('Metronidazole', 'Nitroimidazole', 'Nitroimidazole'),
    ('Ciprofloxacin In', 'Fluoroquinolone', 'Fluoroquinolone'),
    ('Doxycycline Hyclate', 'Tetracycline', 'Tetracycline'),
    ('Cefpodoxime', 'Beta Lactam', 'Cephalosporin Gen3'),
    ('Piperacillin-Tazobactam', 'Beta Lactam', 'Beta Lactam Combo'),
    ('Rifaximin', 'Ansamycin', 'Ansamycin'),
    ('Vancomycin-Diluent Combo', 'Glycopeptide', 'Glycopeptide'),
    ('Clindamycin In', 'Macrolide Lincosamide', 'Lincosamide'),
    ('Amoxicillin', 'Beta Lactam', 'Penicillin'),
    ('Nitrofurantoin Macrocrystal', 'Nitrofuran', 'Nitrofuran'),
    ('Macrobid', 'Nitrofuran', 'Nitrofuran'),
    ('Cefdinir', 'Beta Lactam', 'Cephalosporin Gen3'),
    ('Gentamicin-Sodium Citrate', 'Aminoglycoside', 'Aminoglycoside'),
    ('Clindamycin Phosphate', 'Macrolide Lincosamide', 'Lincosamide'),
    ('Cefoxitin', 'Beta Lactam', 'Cephalosporin Gen2'),
    ('Cipro', 'Fluoroquinolone', 'Fluoroquinolone'),
    ('Clindamycin Hcl', 'Macrolide Lincosamide', 'Lincosamide'),
    ('Vancomycin In', 'Glycopeptide', 'Glycopeptide'),
    ('Moxifloxacin', 'Fluoroquinolone', 'Fluoroquinolone'),
    ('Gentamicin', 'Aminoglycoside', 'Aminoglycoside'),
    ('Linezolid', 'Oxazolidinone', 'Oxazolidinone'),
    ('Zithromax', 'Macrolide Lincosamide', 'Macrolide'),
    ('Erythromycin', 'Macrolide Lincosamide', 'Macrolide'),
    ('Bactrim Ds', 'Combination Antibiotic', 'Sulfonamide Combo'),
    ('Fosfomycin Tromethamine', 'Fosfomycin', 'Fosfomycin'),
    ('Cefepime', 'Beta Lactam', 'Cephalosporin Gen4'),
    ('Keflex', 'Beta Lactam', 'Cephalosporin Gen1'),
    ('Doxycycline Monohydrate', 'Tetracycline', 'Tetracycline'),
    ('Colistin', 'Polymyxin, Lipopeptide', 'Polymyxin'),
    ('Clarithromycin', 'Macrolide Lincosamide', 'Macrolide'),
    ('Levaquin', 'Fluoroquinolone', 'Fluoroquinolone'),
    ('Rifampin', 'Ansamycin', 'Ansamycin'),
    ('Ciprofloxacin', 'Fluoroquinolone', 'Fluoroquinolone'),
    ('Cefuroxime Axetil', 'Beta Lactam', 'Cephalosporin Gen2'),
    ('Augmentin', 'Beta Lactam', 'Beta Lactam Combo'),
    ('Cefadroxil', 'Beta Lactam', 'Cephalosporin Gen1'),
    ('Methenamine Hippurate', 'Urinary Antiseptic', 'Urinary Antiseptic'),
    ('Ertapenem', 'Beta Lactam', 'Carbapenem'),
    ('Ofloxacin', 'Fluoroquinolone', 'Fluoroquinolone'),
    ('Linezolid In Dextrose', 'Oxazolidinone', 'Oxazolidinone'),
    ('Penicillin', 'Beta Lactam', 'Penicillin'),
    ('Silver Sulfadiazine', 'Sulfonamide', 'Sulfonamide'),
    ('Dapsone', 'Sulfonamide', 'Sulfonamide'),
    ('Ciprofloxacin-Dexamethasone', 'Fluoroquinolone', 'Fluoroquinolone'),
    ('Ampicillin Sodium', 'Beta Lactam', 'Penicillin'),
    ('Isoniazid', 'Antitubercular', 'Antitubercular'),
    ('Bactrim', 'Combination Antibiotic', 'Sulfonamide Combo'),
    ('Fidaxomicin', 'Macrolide Lincosamide', 'Macrolide'),
    ('Aztreonam In', 'Monobactam', 'Monobactam'),
    ('Ethambutol', 'Antitubercular', 'Antitubercular'),
    ('Tobramycin Sulfate', 'Aminoglycoside', 'Aminoglycoside'),
    ('Cefepime In', 'Beta Lactam', 'Cephalosporin Gen4'),
    ('Ampicillin', 'Beta Lactam', 'Penicillin'),
    ('Minocycline', 'Tetracycline', 'Tetracycline'),
    ('Ceftazidime-Dextrose', 'Beta Lactam', 'Cephalosporin Gen3'),
    ('Aztreonam', 'Monobactam', 'Monobactam'),
    ('Xifaxan', 'Ansamycin', 'Ansamycin'),
    ('Erythromycin Ethylsuccinate', 'Macrolide Lincosamide', 'Macrolide'),
    ('Gentamicin In Nacl', 'Aminoglycoside', 'Aminoglycoside'),
    ('Meropenem', 'Beta Lactam', 'Carbapenem'),
    ('Gatifloxacin', 'Fluoroquinolone', 'Fluoroquinolone'),
    ('Flagyl', 'Nitroimidazole', 'Nitroimidazole'),
    ('Macrodantin', 'Nitrofuran', 'Nitrofuran'),
    ('Amikacin', 'Aminoglycoside', 'Aminoglycoside'),
    ('Trimethoprim', 'Folate Synthesis Inhibitor', 'Folate Synthesis Inhibitor'),
    ('Tobramycin-Dexamethasone', 'Aminoglycoside', 'Aminoglycoside'),
    ('Dicloxacillin', 'Beta Lactam', 'Penicillin'),
    ('Moxifloxacin-Sod.Chloride(Iso)', 'Fluoroquinolone', 'Fluoroquinolone'),
    ('Hiprex', 'Urinary Antiseptic', 'Urinary Antiseptic'),
    ('Ceftazidime', 'Beta Lactam', 'Cephalosporin Gen3'),
    ('Zyvox', 'Oxazolidinone', 'Oxazolidinone'),
    ('Methenamine Mandelate', 'Urinary Antiseptic', 'Urinary Antiseptic'),
    ('Rifabutin', 'Ansamycin', 'Ansamycin'),
    ('Tedizolid', 'Oxazolidinone', 'Oxazolidinone');

SELECT * FROM `som-nero-phi-jonc101.fateme_db.class_subtype_lookup`;
