nohup python3 ExampleQueryApp.py -p 1 -r Oral -d A results/queryResults.A.Oral.tab &> log/exampleQuery.000.-r_Oral_-d_A_results..queryResults.A.Oral.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Oral -d B results/queryResults.B.Oral.tab &> log/exampleQuery.001.-r_Oral_-d_B_results..queryResults.B.Oral.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Oral -d C results/queryResults.C.Oral.tab &> log/exampleQuery.002.-r_Oral_-d_C_results..queryResults.C.Oral.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Oral -d D results/queryResults.D.Oral.tab &> log/exampleQuery.003.-r_Oral_-d_D_results..queryResults.D.Oral.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Oral -d E results/queryResults.E.Oral.tab &> log/exampleQuery.004.-r_Oral_-d_E_results..queryResults.E.Oral.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Oral -d F results/queryResults.F.Oral.tab &> log/exampleQuery.005.-r_Oral_-d_F_results..queryResults.F.Oral.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Oral -d G results/queryResults.G.Oral.tab &> log/exampleQuery.006.-r_Oral_-d_G_results..queryResults.G.Oral.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Oral -d H results/queryResults.H.Oral.tab &> log/exampleQuery.007.-r_Oral_-d_H_results..queryResults.H.Oral.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Oral -d I results/queryResults.I.Oral.tab &> log/exampleQuery.008.-r_Oral_-d_I_results..queryResults.I.Oral.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intravenous -d A results/queryResults.A.Intravenous.tab &> log/exampleQuery.009.-r_Intravenous_-d_A_results..queryResults.A.Intravenous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intravenous -d B results/queryResults.B.Intravenous.tab &> log/exampleQuery.010.-r_Intravenous_-d_B_results..queryResults.B.Intravenous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intravenous -d C results/queryResults.C.Intravenous.tab &> log/exampleQuery.011.-r_Intravenous_-d_C_results..queryResults.C.Intravenous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intravenous -d D results/queryResults.D.Intravenous.tab &> log/exampleQuery.012.-r_Intravenous_-d_D_results..queryResults.D.Intravenous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intravenous -d E results/queryResults.E.Intravenous.tab &> log/exampleQuery.013.-r_Intravenous_-d_E_results..queryResults.E.Intravenous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intravenous -d F results/queryResults.F.Intravenous.tab &> log/exampleQuery.014.-r_Intravenous_-d_F_results..queryResults.F.Intravenous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intravenous -d G results/queryResults.G.Intravenous.tab &> log/exampleQuery.015.-r_Intravenous_-d_G_results..queryResults.G.Intravenous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intravenous -d H results/queryResults.H.Intravenous.tab &> log/exampleQuery.016.-r_Intravenous_-d_H_results..queryResults.H.Intravenous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intravenous -d I results/queryResults.I.Intravenous.tab &> log/exampleQuery.017.-r_Intravenous_-d_I_results..queryResults.I.Intravenous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Subcutaneous -d A results/queryResults.A.Subcutaneous.tab &> log/exampleQuery.018.-r_Subcutaneous_-d_A_results..queryResults.A.Subcutaneous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Subcutaneous -d B results/queryResults.B.Subcutaneous.tab &> log/exampleQuery.019.-r_Subcutaneous_-d_B_results..queryResults.B.Subcutaneous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Subcutaneous -d C results/queryResults.C.Subcutaneous.tab &> log/exampleQuery.020.-r_Subcutaneous_-d_C_results..queryResults.C.Subcutaneous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Subcutaneous -d D results/queryResults.D.Subcutaneous.tab &> log/exampleQuery.021.-r_Subcutaneous_-d_D_results..queryResults.D.Subcutaneous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Subcutaneous -d E results/queryResults.E.Subcutaneous.tab &> log/exampleQuery.022.-r_Subcutaneous_-d_E_results..queryResults.E.Subcutaneous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Subcutaneous -d F results/queryResults.F.Subcutaneous.tab &> log/exampleQuery.023.-r_Subcutaneous_-d_F_results..queryResults.F.Subcutaneous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Subcutaneous -d G results/queryResults.G.Subcutaneous.tab &> log/exampleQuery.024.-r_Subcutaneous_-d_G_results..queryResults.G.Subcutaneous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Subcutaneous -d H results/queryResults.H.Subcutaneous.tab &> log/exampleQuery.025.-r_Subcutaneous_-d_H_results..queryResults.H.Subcutaneous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Subcutaneous -d I results/queryResults.I.Subcutaneous.tab &> log/exampleQuery.026.-r_Subcutaneous_-d_I_results..queryResults.I.Subcutaneous.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intramuscular -d A results/queryResults.A.Intramuscular.tab &> log/exampleQuery.027.-r_Intramuscular_-d_A_results..queryResults.A.Intramuscular.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intramuscular -d B results/queryResults.B.Intramuscular.tab &> log/exampleQuery.028.-r_Intramuscular_-d_B_results..queryResults.B.Intramuscular.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intramuscular -d C results/queryResults.C.Intramuscular.tab &> log/exampleQuery.029.-r_Intramuscular_-d_C_results..queryResults.C.Intramuscular.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intramuscular -d D results/queryResults.D.Intramuscular.tab &> log/exampleQuery.030.-r_Intramuscular_-d_D_results..queryResults.D.Intramuscular.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intramuscular -d E results/queryResults.E.Intramuscular.tab &> log/exampleQuery.031.-r_Intramuscular_-d_E_results..queryResults.E.Intramuscular.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intramuscular -d F results/queryResults.F.Intramuscular.tab &> log/exampleQuery.032.-r_Intramuscular_-d_F_results..queryResults.F.Intramuscular.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intramuscular -d G results/queryResults.G.Intramuscular.tab &> log/exampleQuery.033.-r_Intramuscular_-d_G_results..queryResults.G.Intramuscular.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intramuscular -d H results/queryResults.H.Intramuscular.tab &> log/exampleQuery.034.-r_Intramuscular_-d_H_results..queryResults.H.Intramuscular.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Intramuscular -d I results/queryResults.I.Intramuscular.tab &> log/exampleQuery.035.-r_Intramuscular_-d_I_results..queryResults.I.Intramuscular.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Topical -d A results/queryResults.A.Topical.tab &> log/exampleQuery.036.-r_Topical_-d_A_results..queryResults.A.Topical.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Topical -d B results/queryResults.B.Topical.tab &> log/exampleQuery.037.-r_Topical_-d_B_results..queryResults.B.Topical.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Topical -d C results/queryResults.C.Topical.tab &> log/exampleQuery.038.-r_Topical_-d_C_results..queryResults.C.Topical.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Topical -d D results/queryResults.D.Topical.tab &> log/exampleQuery.039.-r_Topical_-d_D_results..queryResults.D.Topical.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Topical -d E results/queryResults.E.Topical.tab &> log/exampleQuery.040.-r_Topical_-d_E_results..queryResults.E.Topical.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Topical -d F results/queryResults.F.Topical.tab &> log/exampleQuery.041.-r_Topical_-d_F_results..queryResults.F.Topical.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Topical -d G results/queryResults.G.Topical.tab &> log/exampleQuery.042.-r_Topical_-d_G_results..queryResults.G.Topical.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Topical -d H results/queryResults.H.Topical.tab &> log/exampleQuery.043.-r_Topical_-d_H_results..queryResults.H.Topical.tab.log &
nohup python3 ExampleQueryApp.py -p 1 -r Topical -d I results/queryResults.I.Topical.tab &> log/exampleQuery.044.-r_Topical_-d_I_results..queryResults.I.Topical.tab.log &
