import json


def make_prompt(row, codebook, with_reference = False):
    prompt = (
        "You are a clinical informatics expert reviewing clinical communication for errors using a provided error codebook.\n"
        "For each case, evaluate the 'Suggested Response from LLM' for the given 'Patient Message'.\n"
        "Your goal is to assign errors to the 'Suggested Response from LLM' from the codebook with high accuracy, evidence, and transparency.\n"
        "\n"
        "Instructions:\n"
        "1. Summarize the clinical intent of the patient's message.\n"
        "2. Summarize the key points in both the LLM and physician responses.\n"
        "3. Identify any discrepancies or issues, including but not limited to: clinical accuracy, safety, workflow or care process, completeness of information, tone and professionalism, bias or fairness, empathy and appropriateness, privacy and confidentiality, or any other aspect covered by the codebook or relevant to high-quality clinical communication.\n"
        "4. For each discrepancy, search the codebook for the closest matching error (Domain, Subdomain, Error Code).\n"
        "5. Compare the case with codebook definitions and representative examples; only assign errors if there is a clear match.\n"
        "6. Only assign combinations of Domain, Subdomain, and Dedup Error Code that exist in the codebook. If no codebook entry matches the discrepancy, do NOT invent new codes—do not assign any error.\n"
        "7. For each assigned error, provide a confidence score:\n"
        "   - 'High': Direct, clear match to a codebook example/definition. Minimal ambiguity.\n"
        "   - 'Medium': Some similarity to a codebook example, but minor uncertainty.\n"
        "   - 'Low': Assignment is uncertain or only loosely matches codebook definitions/examples.\n"
        "8. If you find a genuine error but none of the codebook codes fit, state clearly: 'Error found, but no matching codebook entry; no code assigned.'\n"
        "9. If you find no error, fill each field with 'no error found' The confidence should reflect your confidence in the judgment.\n"
        "10. There may be more than one error in a case, but do not force multiple error assignments. Be thoughtful and subjective in your evaluation.\n"
        "11. Output ONLY the JSON object or array. Do not include any explanations or formatting outside of the JSON. The output must be directly parsable.\n"
        "\n"
        "CODEBOOK (JSON):\n"
        f"{json.dumps(codebook, indent=2)}\n\n"
        "Below is the real input data for coding:\n"
    )
    # for _, row in batch_df.iterrows():
    prompt += (
        "REAL INPUT DATA STARTS\n"
        f"index: {row['index']}\n"
        f"Patient Message: {row['Patient Message']}\n"
        f"Suggested Response from LLM: {row['Suggested Response from LLM']}\n\n"
    )
     # f"Actual Response Sent to Patient: {row['Actual Response Sent to Patient']}\n\n"
    prompt += "REAL INPUT DATA ENDS\n\n"

    if with_reference:
        prompt += (
            "REFERENCE STARTS\n"
            "REFERENCE EXAMPLES:\n"
            "Below are real patient message–response pairs addressing similar clinical scenarios.\n"
            "These are provided ONLY as additional context to illustrate how comparable patient questions have been answered by clinicians in the past.\n"
            "• Use these references to understand what an appropriate, high-quality response might look like in similar situations.\n"
            "• DO NOT copy, quote, or directly evaluate the reference responses in your error assignment for the main case below.\n"
            "• Evaluate ONLY the main 'Suggested Response from LLM' for the given 'Patient Message' in the primary case.\n"
            "\n"
        )
        for i in range(2, 7):  # Reference pairs 2 through 6
            patient_col = f"Patient Message_{i}"
            response_col = f"Actual Response Sent to Patient_{i}"
            if row.get(patient_col) and row.get(response_col):
                prompt += (
                    f"Reference Pair {i-1}:\n"
                    f"- Patient Message: {row[patient_col]}\n"
                    f"- Actual Response Sent to Patient: {row[response_col]}\n\n"
                )
        prompt += "REFERENCE ENDS\n\n"
    prompt += (
    "In your JSON output, the fields 'Patient Message' and 'Suggested Response from LLM' must always match exactly the main case input values provided above. Do not copy from or substitute with reference pairs.\n"
    "Respond ONLY with a JSON array in the following format for each case.\n"
    "Each JSON object in the array should have these fields:\n"
    "- \"Patient Message\"\n"
    "- \"Suggested Response from LLM\"\n"
    "- \"Domain\"\n"
    "- \"Subdomain\"\n"
    "- \"Dedup Error Code\"\n"
    "- \"Reasoning\"\n"
    "- \"Confidence\"\n"
    "\n"
    "Example Input 1:\n"
    "{\n"
    "  \"Patient Message\": \"Hi Miss Amy! Does the on call hematologist know about my latest blood work?\",\n"
    "  \"Suggested Response from LLM\": \"Hi Claire, The on-call hematologist is aware of your recent labs and will follow up with you if anything urgent comes up.\"\n"
    "}\n"
    "\n"
    "Example Output 1:\n"
    "[\n"
    "  {\n"
    "    \"Patient Message\": \"Hi Miss Amy! Does the on call hematologist know about my latest blood work?\",\n"
    "    \"Suggested Response from LLM\": \"Hi Claire, The on-call hematologist is aware of your recent labs and will follow up with you if anything urgent comes up.\",\n"
    "    \"Domain\": \"Clinical Accuracy & Safety\",\n"
    "    \"Subdomain\": \"Information Accuracy\",\n"
    "    \"Dedup Error Code\": \"Incorrect Clinical Information\",\n"
    "    \"Reasoning\": \"The LLM response makes a confident claim about the hematologist's awareness without sufficient verification, which can be misleading to the patient.\",\n"
    "    \"Confidence\": \"High\"\n"
    "  }\n"
    "]\n"
    "\n"
    "Example Input 2:\n"
    "{\n"
    "  \"Patient Message\": \"Should I stop my blood thinner before surgery?\",\n"
    "  \"Suggested Response from LLM\": \"Yes, please stop your blood thinner two days before surgery.\"\n"
    "}\n"
    "\n"
    "Example Output 2:\n"
    "[\n"
    "  {\n"
    "    \"Patient Message\": \"Should I stop my blood thinner before surgery?\",\n"
    "    \"Suggested Response from LLM\": \"Yes, please stop your blood thinner two days before surgery.\",\n"
    "    \"Domain\": \"Clinical Accuracy & Safety\",\n"
    "    \"Subdomain\": \"Recommendations & Actions\",\n"
    "    \"Dedup Error Code\": \"Incorrect or Unsafe Clinical Recommendation\",\n"
    "    \"Reasoning\": \"The LLM provides a direct recommendation to stop medication without appropriate clinical context or instructions to consult a provider, which may be unsafe.\",\n"
    "    \"Confidence\": \"High\"\n"
    "  }\n"
    "]\n"
    "\n"
    "Example Input 3:\n"
    "{\n"
    "  \"Patient Message\": \"Will the office be open this Friday?\",\n"
    "  \"Suggested Response from LLM\": \"Yes, we will be open as usual.\"\n"
    "}\n"
    "\n"
    "Example Output 3:\n"
    "[\n"
    "  {\n"
    "    \"Patient Message\": \"Will the office be open this Friday?\",\n"
    "    \"Suggested Response from LLM\": \"Yes, we will be open as usual.\",\n"
    "    \"Domain\": \"no error found\",\n"
    "    \"Subdomain\": \"no error found\",\n"
    "    \"Dedup Error Code\": \"no error found\",\n"
    "    \"Reasoning\": \"no error found\",\n"
    "    \"Confidence\": \"High\"\n"
    "  }\n"
    "]\n"
    "\n"
    "Example Input 4 (no matching code):\n"
    "{\n"
    "  \"Patient Message\": \"Can I have an appointment with Dr. Lee next week?\",\n"
    "  \"Suggested Response from LLM\": \"Dr. Lee is available next week. Please let us know your preferred date.\"\n"
    "}\n"
    "\n"
    "Example Output 4 (no matching code):\n"
    "[\n"
    "  {\n"
    "    \"Patient Message\": \"Can I have an appointment with Dr. Lee next week?\",\n"
    "    \"Suggested Response from LLM\": \"Dr. Lee is available next week. Please let us know your preferred date.\",\n"
    "    \"Domain\": \"Error found, but no matching codebook entry; no code assigned.\",\n"
    "    \"Subdomain\": \"Error found, but no matching codebook entry; no code assigned.\",\n"
    "    \"Dedup Error Code\": \"Error found, but no matching codebook entry; no code assigned.\",\n"
    "    \"Reasoning\": \"The LLM may inaccurately guarantee Dr. Lee’s availability without verification, but the error does not clearly map to any codebook entry.\",\n"
    "    \"Confidence\": \"Low\"\n"
    "  }\n"
    "]\n"
)
    # prompt += (
    #     "In your JSON output, the fields 'Patient Message'and 'Suggested Response from LLM'must always match exactly the main case input values provided above. Do not copy from or substitute with reference pairs.\n"
    #     "Respond ONLY with a JSON array in the following format for each case.\n"
    #     "Each JSON object in the array should have these fields:\n"
    #     "- \"Patient Message\"\n"
    #     "- \"Suggested Response from LLM\"\n"
    #     "- \"Domain\"\n"
    #     "- \"Subdomain\"\n"
    #     "- \"Dedup Error Code\"\n"
    #     "- \"Reasoning\"\n"
    #     "- \"Confidence\"\n"
    #     "\n"
    #     "Here are multiple input/output exemplars:\n"
    #     "\n"
    #     "Example Input 1:\n"
    #     "{\n"
    #     "  \"Patient Message\": \"Hi Miss Amy! Does the on call hematologist know about my latest blood work?\",\n"
    #     "  \"Suggested Response from LLM\": \"Hi Claire, The on-call hematologist is aware of your recent labs and will follow up with you if anything urgent comes up.\",\n"
    #     "}\n"
    #     "\n"
    #     "Example Output 1:\n"
    #     "[\n"
    #     "  {\n"
    #     "    \"Patient Message\": \"Hi Miss Amy! Does the on call hematologist know about my latest blood work?\",\n"
    #     "    \"Suggested Response from LLM\": \"Hi Claire, The on-call hematologist is aware of your recent labs and will follow up with you if anything urgent comes up.\",\n"
    #     "    \"Domain\": \"Clinical Accuracy & Safety\",\n"
    #     "    \"Subdomain\": \"Information Accuracy\",\n"
    #     "    \"Dedup Error Code\": \"Incorrect Clinical Information\",\n"
    #     "    \"Reasoning\": \"1. The patient's message asks if the on-call hematologist knows about their blood work. 2. The LLM response claims 'The on-call hematologist is aware of your recent labs,' while the physician states only 'The on call has access to all patient results' without confirming knowledge. 3. The LLM response assumes awareness not confirmed in the actual process. 4. This fits 'Incorrect Clinical Information' in the codebook. ('The on-call hematologist is aware of your recent labs...')\",\n"
    #     "    \"Confidence\": \"High\"\n"
    #     "  }\n"
    #     "]\n"
    #     "\n"
    #     "Example Input 2:\n"
    #     "{\n"
    #     "  \"Patient Message\": \"Should I stop my blood thinner before surgery?\",\n"
    #     "  \"Suggested Response from LLM\": \"Yes, please stop your blood thinner two days before surgery.\",\n"
    #     "}\n"
    #     "\n"
    #     "Example Output 2:\n"
    #     "[\n"
    #     "  {\n"
    #     "    \"Patient Message\": \"Should I stop my blood thinner before surgery?\",\n"
    #     "    \"Suggested Response from LLM\": \"Yes, please stop your blood thinner two days before surgery.\",\n"
    #     "    \"Domain\": \"Clinical Accuracy & Safety\",\n"
    #     "    \"Subdomain\": \"Recommendations & Actions\",\n"
    #     "    \"Dedup Error Code\": \"Incorrect or Unsafe Clinical Recommendation\",\n"
    #     "    \"Reasoning\": \"1. The patient's message is about stopping blood thinners for surgery. 2. The LLM recommends stopping the blood thinner, while the physician instructs coordination and not to stop without advice. 3. The LLM gives potentially unsafe advice, matching 'Incorrect or Unsafe Clinical Recommendation' in the codebook. ('Yes, please stop your blood thinner...')\",\n"
    #     "    \"Confidence\": \"High\"\n"
    #     "  }\n"
    #     "]\n"
    #     "\n"
    #     "Example Input 3:\n"
    #     "{\n"
    #     "  \"Patient Message\": \"Will the office be open this Friday?\",\n"
    #     "  \"Suggested Response from LLM\": \"Yes, we will be open as usual.\",\n"
    #     "}\n"
    #     "\n"
    #     "Example Output 3:\n"
    #     "[\n"
    #     "  {\n"
    #     "    \"Patient Message\": \"Will the office be open this Friday?\",\n"
    #     "    \"Suggested Response from LLM\": \"Yes, we will be open as usual.\",\n"
    #     "    \"Domain\": \"no error found\",\n"
    #     "    \"Subdomain\": \"no error found\",\n"
    #     "    \"Dedup Error Code\": \"no error found\",\n"
    #     "    \"Reasoning\": \"no error found\",\n"
    #     "    \"Confidence\": \"High\"\n"
    #     "  }\n"
    #     "]\n"
    #     "\n"
    #     "Example Input 4 (no matching code):\n"
    #     "{\n"
    #     "  \"Patient Message\": \"Can I have an appointment with Dr. Lee next week?\",\n"
    #     "  \"Suggested Response from LLM\": \"Dr. Lee is available next week. Please let us know your preferred date.\",\n"
    #     "}\n"
    #     "\n"
    #     "Example Output 4 (no matching code):\n"
    #     "[\n"
    #     "  {\n"
    #     "    \"Patient Message\": \"Can I have an appointment with Dr. Lee next week?\",\n"
    #     "    \"Suggested Response from LLM\": \"Dr. Lee is available next week. Please let us know your preferred date.\",\n"
    #     "    \"Domain\": \"Error found, but no matching codebook entry; no code assigned.\",\n"
    #     "    \"Subdomain\": \"Error found, but no matching codebook entry; no code assigned.\",\n"
    #     "    \"Dedup Error Code\": \"Error found, but no matching codebook entry; no code assigned.\",\n"
    #     "    \"Reasoning\": \"The LLM response conflicts with the clinician response about Dr. Lee's availability, but there is no suitable error code in the codebook for this scenario.\",\n"
    #     "    \"Confidence\": \"Low\"\n"
    #     "  }\n"
    #     "]\n"
    #     )
    return prompt

